libobs: Use uuids for all contexts
obsproject/obs-studio pull request #10052
Opened 2023-12-30 02:25 UTC by cg2121

### Description
This adds uuids to outputs, encoders and services.

### Motivation and Context
This will help me in the output wrapper PR (#8918), so I can store/find outputs by their uuid. UUIDs are a better way of looking up contexts, as the uuid never changes.

These are currently not using hash tables. As there are far less of these than sources, lookup times shouldn't be impacted.

### How Has This Been Tested?
Retrieved uuid from virtual camera output and also found that output by that uuid. Haven't tested with encoders or services but the code is basically the same, so they should also work.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-01-06 23:41 UTC, derrod requested changes
In documentation and commit title "UUID" should be all-uppercase as it's an acronym, otherwise seems fine though. Using a hash table for everything shouldn't be a ton of overhead but I agree it's probably overkill.

2024-01-06 23:41 UTC, WizardCM commented
Please capitalise UUID in all places where possible (commit title, documentation, comments).

2024-01-09 21:52 UTC, cg2121 commented
UUID strings are now all capitalized.

2024-11-23 20:45 UTC, cg2121 commented
Closing, as UUIDs are only currently useful for sources.

2024-11-23 20:45 UTC, closed without merging