libobs: Copy both converted textures on stall
obsproject/obs-studio pull request #10154
Opened 2024-01-28 03:21 UTC by kkartaltepe

### Description

As the comment mentions this only occurs during an encoder stall on the first frame. With opengl texture encoders we might have multiple planes and need to copy both of them.

### Motivation and Context

On very low power devices this happens once in a while, and it consistently happens on a very terrible egpu configuration.

### How Has This Been Tested?

Fixes the first frame only containing the Luma plane on the egpu setup where I can trigger this consistently.

### Types of changes

 - Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-01-29 06:49 UTC, lextra2 commented
`On other platforms these are to distinct textures`

`to` should say `two`

2024-01-29 17:23 UTC, RytoEX requested changes
Commit message nits:
* d3d -> D3D
* opengl -> OpenGL

2024-01-29 17:23 UTC, RytoEX commented on libobs/obs-video.c
> +		// that must be copied separately.
```suggestion
		// Y and UV textures are views of the same texture on D3D, and
		// gs_copy_texture will copy all views of the underlying
		// texture. On other platforms, these are two distinct textures
		// that must be copied separately.
```

2024-01-30 00:28 UTC, derrod approved these changes

2024-01-30 02:53 UTC, kkartaltepe commented
Typos fixed

2024-01-30 06:04 UTC, RytoEX approved these changes
Nits fixed. Leaving to others to finish review/merge.

2024-01-31 04:15 UTC, merged