fix yuy2 line size error
obsproject/obs-studio pull request #10203
Opened 2024-02-05 12:16 UTC by vico-shang

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2024-02-05 12:21 UTC, vico-shang commented
nv12 to yuy2 scale will crash with error yuy2 line size

2024-02-05 12:47 UTC, WizardCM commented
Please fill in the PR template and name your commit based on the contributing guidelines.

2024-02-06 01:10 UTC, RytoEX requested changes
Please change the PR title and commit message subject to comply with our [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/66978c4d23e32d0f67ec5ac7246a8fea01bf4740/CONTRIBUTING.rst#commit-guidelines):
1. Use the correct prefix ("win-dshow: ")
2. Use a present tense verb as the first word after the commit prefix ("fix" is probably fine, "bugfix" is not)

Additionally, please properly capitalize "YUY2".

2024-02-07 18:27 UTC, Lain-B approved these changes

2024-02-07 18:27 UTC, merged