CI: Use flathub-infra Flatpak actions
obsproject/obs-studio pull request #10232
Opened 2024-02-10 23:25 UTC by GeorgesStavracas

### Description

It's a ultimately a temporary workaround while the whole situation with libappstream, Flatpak, and flatpak-builder isn't figured out. But it does seem to work.

### Motivation and Context

The Flathub publishing workflow is broken due to an odd flatpak-builder / appstream impedance mismatch, and this works around that.

### How Has This Been Tested?

It hasn't (yet)

### Types of changes

 - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-02-10 23:28 UTC, tytan652 reviewed
I'm *fine* with it as long we don't switch to the pre-included `flatpak-builder-lint` installation for this image.

2024-02-10 23:29 UTC, tytan652 commented
I forgot, we need Github CLI for our CIs.

2024-02-13 12:19 UTC, tytan652 commented on .github/actions/flatpak-builder-lint/action.yaml
v2.1.5 is a broken version to be used with a JSON parser

2024-02-13 12:27 UTC, tytan652 commented
You can check #10234 for the needed error filter change.

2024-02-13 13:22 UTC, tytan652 commented on .github/workflows/build-project.yaml
Beside swapping images and removing dnf usage, the action as no need to be swapped to the fork.

2024-02-13 14:52 UTC, GeorgesStavracas commented on .github/workflows/build-project.yaml
Done

2024-02-13 14:58 UTC, tytan652 commented
Note: `CI: Use flatpak-builder-lint from the image` can break CI if an update of the tool from upstream introduces new errors.

2024-02-13 15:00 UTC, GeorgesStavracas commented
> Note: CI: Use flatpak-builder-lint from the image can break CI if an update of the tool from upstream introduces new errors.

Yes. In which case, we adjust to the linter error.

2024-02-13 20:02 UTC, Fenrirthviti commented
This workaround seems fine, and further discussions around the best long-term solution can happen off-thread. This gets us builds working again. 

It seems we all collectively agree this isn't ideal, but it gets us from broken to not broken for now, and shouldn't have any meaningful impact on the longer term solutions. We accept the risk that this might not be as stable as other solutions, but those require more time we don't have, as we need testing ASAP for our shortened beta period.

2024-02-13 20:30 UTC, RytoEX requested changes
Nit on second commit:
* setup -> set up

Other than that, so long as each commit works on its own, these are fine.

2024-02-13 20:43 UTC, RytoEX approved these changes

2024-02-13 20:44 UTC, merged