UI: Fix `Start Virtual Camera` Text Cut Off in Corresponding Button
obsproject/obs-studio pull request #10318
Opened 2024-03-02 02:10 UTC by powersagitar

### Description

The text `Start Virtual Camera` might be too long to be fully displayed in some cases. A new wrapper around `QPushButton` named `OverflowButton` is thus introduced to replace the overflown text with ellipsis when appropriate.

Old:
<div style="layout: flex;">
<img width="166" alt="ui before fix, text gets truncated" src="https://github.com/obsproject/obs-studio/assets/114868133/4810f478-4c6b-4954-9a2c-5a8eaa708faa">

<img width="223" alt="ui before fix, text does not get truncated" src="https://github.com/obsproject/obs-studio/assets/114868133/9e9d4951-332a-468e-b531-d3c91b17169a">
</div>

New:
<div style="layout: flex;">
<img width="180" alt="ui after fix, overflown text gets replaced by ellipsis" src="https://github.com/obsproject/obs-studio/assets/114868133/f4148b6e-36e5-4285-80cf-9986243c62f3">
<img width="223" alt="ui after fix, text does not get truncated" src="https://github.com/obsproject/obs-studio/assets/114868133/9e9d4951-332a-468e-b531-d3c91b17169a">
</div>

### Motivation and Context

This PR fixes #10210.

### How Has This Been Tested?

Tests are conducted by manually resizing `Controls` panel.

Environment:  
- macOS Ventura 13.6.4 (22G513)
  Arch: x86_64
- Xcode 15.2
  Build version 15C500b

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-03-02 02:22 UTC, gxalpha requested changes

2024-03-02 02:22 UTC, gxalpha commented on AUTHORS
> + powersagitar
Don't add yourself to the authors list. It’s generated automatically and any manual changes will get lost.

2024-03-02 03:42 UTC, Fenrirthviti commented
I'm confused why this is creating an entire new class of button for a single button, instead of applying this attribute to the existing button. Can you please provide more context on why it was solved this way?

Was this also tested with other non-English languages (specifically, RTL languages) as you are explicitly setting `Qt::TextElideMode::ElideRight` which will break with any non-RTL language handlings.

This solution, to me, seems like the incorrect approach.

2024-03-02 14:19 UTC, powersagitar commented
> why this is creating an entire new class of button for a single button, instead of applying this attribute to the existing button.

I created a new button since 
1. With the assumption that the "attribute" you mentioned being something like `text-overflow: ellipsis`, I didn't find any, so the solution I came up with was to listen to the resize event manually and change the text displayed. 
2. The means I found to listen to resize events is to either override `QPushButton::resizeEvent` or `QPushButton::paintEvent`, but in either way a new derived class is required.
3. Right now only `Start Virtual Camera` button has overflowed text, but there could be more buttons requiring the same feature in the future, so I thought it would be better to extract this feature into its own class.

> will break with any non-RTL language handlings

As I personally cannot speak such languages so forgot accounting for them. The solution could be calling `QPushButton::locale().textDirection()` and set `Qt::TextElideMode` accordingly.

Please let me know if you think or find there's better implementations.

2024-03-03 07:12 UTC, Warchamp7 commented
I'm fairly sure fixing the SizePolicy on these buttons should handle overflowing text properly. This fix is incredibly overkill and not the right approach at all.

2024-03-03 22:50 UTC, powersagitar commented
`SizePolicy` does fix this bug by not allowing `Controls` panel to shrink beyond the minimum width of the widget. It also works for both LTR and RTL languages (tested). I think this one is good to be merged if we don't want specifically ellipsis but only a fix for text clipping.

E.g., this is the new minimum width of `Controls` panel.
<img width="215" alt="Screenshot 2024-03-03 at 5 45 24 PM" src="https://github.com/obsproject/obs-studio/assets/114868133/3caab48f-439a-49c5-bf59-ef31b331d46d">

2024-03-09 22:52 UTC, WizardCM commented
Please squash your commits.

2024-03-10 03:30 UTC, powersagitar commented
Done.

2024-03-25 21:06 UTC, Warchamp7 requested changes

2024-03-25 21:06 UTC, Warchamp7 commented on UI/window-basic-main.cpp
> +	buttonSizePolicy.setHorizontalPolicy(QSizePolicy::Minimum);
It should be possible to trim this PR down to simply one line

```vcamButton->first().setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);```

or similar

2024-03-29 07:51 UTC, Warchamp7 approved these changes

2024-04-10 00:57 UTC, merged