UI: Fix bug with mp4 warning
obsproject/obs-studio pull request #10337
Opened 2024-03-06 14:22 UTC by GPattenden

### Description
Add a new QVBoxLayout to OBSBasicSettings.ui to show the warnings in the output advanced recording settings.

**Old layout for warnings in advanced recording settings:**
![AdvancedOldSettings](https://github.com/obsproject/obs-studio/assets/119502068/f1278012-0f27-4748-8239-adc56d23a4a3)

**New layout for warnings in advanced recording settings:**
![AdvancedNewSettings](https://github.com/obsproject/obs-studio/assets/119502068/7eeca6bd-7b91-43d8-99da-4d2b752b644c)

### Motivation and Context
This PR fixes isssue #9276
It also improves the UI so the warnings shown in the advanced Output Recording Settings are consistent with the ones shown in the simple Output tab.

**Simple Output settings (old and new):**
![SimpleOutputSettings](https://github.com/obsproject/obs-studio/assets/119502068/b24cc38a-4a0a-4d2c-9b29-d0b5645b4051)

### How Has This Been Tested?

Tests are conducted by manually entering MPEG-4 (.mp4) in the recording format and resizing the settings window.

**Environment:**

- windows 11 Version 10.0.22631 Build 22631

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-03-11 21:45 UTC, Warchamp7 requested changes
Outside of the margins on the new QVBoxLayout this looks good to me

2024-03-11 21:45 UTC, Warchamp7 commented on UI/forms/OBSBasicSettings.ui
> +                    </item>
Can you remove these margin values?

2024-04-02 09:13 UTC, GPattenden commented
@Warchamp7 I've commited the changes. Is everything ok or does it need any modifications?

2024-04-07 03:49 UTC, Warchamp7 commented
> @Warchamp7 I've commited the changes. Is everything ok or does it need any modifications?

Taking a deeper look, did you hand edit this XML or did you use Qt Creator? That element structure does not look valid to me.

2024-04-07 04:26 UTC, Warchamp7 commented
I adjusted the PR to use a widget with a layout. Technically still hand edited only this change after making the adjustment in Qt Designer so as not to affect #10419 too heavily

2024-04-07 04:39 UTC, merged

2024-04-07 08:56 UTC, GPattenden commented
I had hand edited the XML file. Thank you

2024-04-08 06:31 UTC, noah9444 commented
I tried Nightly Build.
The warning is still displayed even after changing to "Custom Output (FFmpeg)".

https://github.com/obsproject/obs-studio/assets/37494132/ee5b28a0-aae9-4507-9578-9a60c63daf52

2024-04-08 17:30 UTC, RytoEX commented
@noah9444 This PR didn't remove the warning. It moved its location.

2024-04-08 17:42 UTC, Warchamp7 commented
> @noah9444 This PR didn't remove the warning. It moved its location.

When set to Custom Output you're no longer using stream encoder. It looks like we don't properly remove that warning from the warning list when switching, but because it was inside the Standard mode, it wasn't visible.

This is a bug that this PR has exposed and should get it's own issue @noah9444