UI: X11: Linux: Size the abstract-socket address properly
obsproject/obs-studio pull request #10375
Opened 2024-03-14 16:56 UTC by nabijaczleweli

### Description
Unlike filesystem addresses, which are paths, abstract addresses are blobs.

### Motivation and Context
This means that the address wasn't "\0/com/obsproject 2413747 version", but rather "\0/com/obsproject 2402613 version\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"; this is reflected in both /proc/net/unix:
```
000000001bf56057: 00000002 00000000 00000000 0002 01 56719817 @/com/obsproject 2402613 version@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
000000003e897b41: 00000002 00000000 00000000 0002 01 56730132 @/com/obsproject 2413747 version
```
and ss -l:
![](https://github.com/obsproject/obs-studio/assets/6709544/4b20fe3c-570f-407e-8e1a-7d1e033b7354)
extending the whole address column to the point of unusability.

This size calculation follows trivially from the manual, and naturally behaves correctly, as above.

This is the same issue as nfs-utils fsidd: https://lore.kernel.org/linux-nfs/b38ecca96762d939d377c381bf34521ee5945129.1700601199.git.nabijaczleweli@nabijaczleweli.xyz/T/#u

### How Has This Been Tested?
Ex-situ.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-03-16 23:11 UTC, RytoEX requested changes
Please use `UI: ` for the commit message prefix and PR title prefix.

2024-03-16 23:30 UTC, GeorgesStavracas requested changes
Code LGTM, but the commit message must be formatted according to the [Commit Guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst#commit-guidelines).

2024-03-17 08:48 UTC, nabijaczleweli commented
Message reformatted to 72 columns; subject prefix already as-desired.

2024-03-17 17:03 UTC, RytoEX commented
> Message reformatted to 72 columns; subject prefix already as-desired.

No. I am a project maintainer and I am telling you it is not.

2024-03-18 20:29 UTC, nabijaczleweli commented
Strictly, removing just the "X11: " would've sufficed, but sure; updated.

2024-03-18 20:58 UTC, GeorgesStavracas commented
The commit title is still incorrect. Please change the title of your commit to **exactly** this: `UI: Size the abstract-socket address properly`. Please use this title exactly as written, without changes.

2024-03-18 21:24 UTC, nabijaczleweli commented
ah yeah, updated to the wrong ref; fixed

2024-03-18 23:17 UTC, GeorgesStavracas approved these changes
Thanks!

2024-03-18 23:18 UTC, merged