UI: Fix scene rename on tab
obsproject/obs-studio pull request #10426
Opened 2024-03-24 23:32 UTC by howellrl

### Description
Tab key press event was triggering default Qt behavior and selecting next item in scene list before rename event could complete. This caused the incorrect scene to become the target of the rename method. Consumed the tab key event and observed that tab now completes the edit and leaves the current scene selected. This is in alignment with how tabbing away from a rename affects renaming of sources.

### Motivation and Context
Fixed issue: [#10090](https://github.com/obsproject/obs-studio/issues/10090)

### How Has This Been Tested?
Built and ran locally on Windows 11 machine before code change, observed incorrect behavior tabbing from rename. Modified code, observed tabbing from rename completes edit as expected.

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x ] The code has been tested.
- [x ] All commit messages are properly formatted and commits squashed where appropriate.
- [x ] I have included updates to all appropriate documentation.

2024-03-26 16:18 UTC, Warchamp7 commented
This fixes hitting Tab but the same error still happens when pressing Shift + Tab

2024-03-26 16:23 UTC, PatTheMav commented
What happens on macOS without this fix is that the scene is renamed, _but also the scene being switched to_. So both scenes will have the changed name of the first scene.

With only a single scene the renaming is successful by just pressing `<TAB>`.

Pressing `<SHIFT>+<TAB>` only finishes renaming the current scene.

2024-03-26 18:13 UTC, Warchamp7 commented
> What happens on macOS without this fix is that the scene is renamed, _but also the scene being switched to_. So both scenes will have the changed name of the first scene.
> 
> With only a single scene the renaming is successful by just pressing `<TAB>`.
> 
> Pressing `<SHIFT>+<TAB>` only finishes renaming the current scene.

With 3 scenes and the middle scene in the list selected, Shift + Tab doesn't cause the double rename on the current scene and the one above it?

2024-03-26 18:16 UTC, PatTheMav commented
> > What happens on macOS without this fix is that the scene is renamed, _but also the scene being switched to_. So both scenes will have the changed name of the first scene.
> > With only a single scene the renaming is successful by just pressing `<TAB>`.
> > Pressing `<SHIFT>+<TAB>` only finishes renaming the current scene.
> 
> With 3 scenes and the middle scene in the list selected, Shift + Tab doesn't cause the double rename on the current scene and the one above it?

My bad, I didn't consider that `<SHIFT>+<TAB>` would actually move the selection up - the issue occurs as you expected. Interestingly renaming the bottom source again (and naming it "Scene 3" again) triggers a "Name already in use" error.

2024-03-27 22:49 UTC, RytoEX commented
> This fixes hitting Tab but the same error still happens when pressing Shift + Tab
> 
> Will need to check for any similar issues on Mac @PatTheMav

I'm actually surprised at that. I would expect `keyEvent->key()` to always be `Qt::Key_Tab` regardless of additional modifiers. Would probably need to dump out all the keypress events during testing to see what's happening.

That said, I think it's more likely that users are hitting Tab than Shift+Tab, so I'd be inclined to accept this fix (after my own review/testing) if it fixes one known bad case, and we can return to fix other known bad cases later.

2024-03-28 00:43 UTC, howellrl commented
I was able to take a look at this and I noticed there is a separate key press event for back tab that handles the shift + tab key press combination. It appears to handle the back tab correctly now. I have updated my PR.

2024-03-28 00:48 UTC, RytoEX requested changes
Could you squash the commits into a single commit and place the cases in this order:
```cpp
case Qt::Key_Escape
case Qt::Key_Tab
case Qt::Key_Backtab
```

2024-03-28 00:54 UTC, howellrl commented
Absolutely - I have squashed the commits and re-arranged the case statements.

2024-03-29 00:09 UTC, RytoEX approved these changes
Tested on Windows 11. Seems to fix the buggy behavior in the linked Issue.

2024-03-29 00:12 UTC, RytoEX commented
In the future, you can use GitHub closing keywords to automatically link a PR to an Issue:
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue

Waiting on retests from @Warchamp7 and @PatTheMav , or for their review requests to be removed.

2024-03-29 16:58 UTC, Warchamp7 approved these changes

2024-03-30 23:09 UTC, Lain-B approved these changes

2024-03-30 23:09 UTC, merged