game-capture: Update hooked state before unhooked signal
obsproject/obs-studio pull request #10460
Opened 2024-03-30 12:31 UTC by EZ64cool

### Description

Move the `gc->capturing = false` update to before the unhooked signal is sent. This replicates the behaviour of window-capture.

### Motivation and Context

If the get_hooked procedure is called during the unhooked signal the source would still report that it's hooked because `gc->capturing` hasn't been updated yet.

### How Has This Been Tested?

Tested on windows 10 x64 and it now works as expected. It's a very isolated change so easy to test.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

2024-03-30 15:44 UTC, RytoEX requested changes
The correct commit/PR prefix is "win-capture", the name of the plugin and folder. Please use that.

2024-03-31 00:27 UTC, norihiro commented
In the commit message of 6cde4b131, the 2nd line is not empty.

2024-08-17 09:42 UTC, EZ64cool commented
Hey, any chance this could make it in?

It's stopped me from using signals and I'm instead spinning up my own update thread to query the state, which feels a bit overkill for what I need.

2025-02-15 23:37 UTC, EZ64cool commented
Hey @RytoEX sorry to necro this but I just spent some time updating this to latest.

I think your review is the last thing blocking this, if you wouldn't mind taking a look again.

Thanks.

2025-03-22 11:09 UTC, EZ64cool commented
Hey this has been up for review for almost a year now.

Any chance it can make it's way in?
@derrod @Lain-B @RytoEX 

Thanks

2025-04-01 09:28 UTC, closed without merging