UI: Use selected file path when opening file dialogs
obsproject/obs-studio pull request #10485
Opened 2024-04-06 01:13 UTC by Warchamp7

### Description
Updates the properties view to use the existing path of a selected file when creating file dialogs, rather than relying on logic existing where `obs_properties_add_path` is called.

### Motivation and Context
Fixes #6777 at a deeper level compared to the approach in #6786

Currently, file dialogs for property views reference default_path for their working directory. However, this is set only when the property view is being created. Selecting a file or resetting to defaults does not update this value. Due to most places in the the code having a default_path of NULL, behaviour was _usually_ as expected, as re-opening the file dialog would simply fall back to the last location browsed (on Windows at least).

In the case of the LUT filter, we specify a default_path where the default LUT files are located. This meant that after selecting a LUT file outside that folder, immediately re-opening the file dialog would start in the LUT folder again, rather than the directory of the selected file. The default_path would only get updated to the selected files location when the Filters dialog is re-opened or the filters properties are reloaded via switching off of it and back.

Rather than making sure we update default_path anywhere a file selection can happen, update properties view itself to use the selected path when creating the file dialog, allowing default_path to act strictly as the fallback when there is nothing selected.

### How Has This Been Tested?
Opened the file selectors for the LUT filter, Image slideshow properties, Image source properties, and Image source context bar. Ensured that the file dialog always opened to the location of the specified file if set, the default_path if it's not NULL, and native OS fallback in the case of neither.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-04-06 01:14 UTC, RytoEX requested changes
The second commit should either use the prefix "plugins: " or be split into two commits, one for "image-source: " and one for "obs-filters: ".

2024-04-06 01:21 UTC, derrod requested changes

2024-04-06 01:21 UTC, derrod commented on UI/properties-view.cpp
> +	const char *last_path = obs_data_get_string(view->settings, setting);
This seems unused.

2024-04-09 00:49 UTC, norihiro commented
The commit 7b72331f0 should have the prefix `plugins:` instead of `Plugins:`.

2024-04-09 23:31 UTC, derrod approved these changes
Seems fine aside from the commit message complaints.

2024-04-10 01:10 UTC, merged