UI,docs: Send a custom event to the dock widget when closing
obsproject/obs-studio pull request #10516
Opened 2024-04-11 14:56 UTC by tytan652

### Description

Send a custom event to the OBSDock widget when the dock (from `obs_frontend_add_dock_by_id`) is closed, which allow plugin authors to potentially save resources while the dock is closed.

A QShowEvent is already sent to the widget when the dock is (re-)openned.

### Motivation and Context

Motivation related to:
- https://github.com/obsproject/obs-browser/pull/431

Enabling a way closing browser from a plugin dock when the said dock is closed, since OBS Studio completely owns the access to the dock object.

### How Has This Been Tested?

Disabled the `closeBrowser()` call in BrowserDock `closeEvent()` impl and added the following to QCefWidgetInternal for testing purpose:
```cpp
bool QCefWidgetInternal::event(QEvent *event)
{
	if (event->type() == (QEvent::User + QEvent::Close))
	{
		closeBrowser();
		return true;
	}

	return QCefWidget::event(event);
}
```
The browser is closed when the dock is closed thanks to the event as expected.

### Types of changes

- New feature (non-breaking change which adds functionality)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-04-13 23:58 UTC, WizardCM approved these changes

2024-04-14 00:56 UTC, RytoEX requested changes

2024-04-14 00:56 UTC, RytoEX commented on docs/sphinx/reference-frontend-api.rst
> +   is sent to the widget to enable it to react to the event (e.g. unload elements
```suggestion
   is sent to the widget to enable it to react to the event (e.g., unload elements
```

2024-04-14 00:56 UTC, RytoEX commented on docs/sphinx/reference-frontend-api.rst
> +   shown (e.g. dock openned).
```suggestion
   shown (e.g., dock opened).
```

2024-04-14 07:43 UTC, tytan652 commented on docs/sphinx/reference-frontend-api.rst
> +   is sent to the widget to enable it to react to the event (e.g. unload elements
Done

2024-04-14 07:43 UTC, tytan652 commented on docs/sphinx/reference-frontend-api.rst
> +   shown (e.g. dock openned).
Done

2024-08-04 00:18 UTC, merged