libobs: Export nv12/p10 functions
obsproject/obs-studio pull request #10567
Opened 2024-04-18 15:51 UTC by kkartaltepe

n

### Description

v12 and p10 device functions were not exported on all platforms, instead windows was exporting from C files. After cmake 3.0 when we started hiding symbols these began failing to resolve.

This resulted in obs crashing since fallback encoders were not used.

### Motivation and Context

Fixes texture encoders on opengl

### How Has This Been Tested?

Launched a texture encoder.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-04-18 16:12 UTC, tytan652 approved these changes
LGTM

2024-04-18 16:33 UTC, RytoEX requested changes
Nits:
* nv12 and p010 -> NV12 and P010
* nv12/p010 -> NV12/P010

Other than that, seems okay.

2024-04-18 21:04 UTC, PatTheMav approved these changes

2024-04-19 02:57 UTC, kkartaltepe commented
Updated

2024-04-19 19:23 UTC, RytoEX approved these changes

2024-04-19 19:23 UTC, merged