libobs: Fix grouped encoders never starting again after disconnect
obsproject/obs-studio pull request #10573
Opened 2024-04-19 15:42 UTC by palana

(based on <https://github.com/amazon-contributing/upstreaming-to-obs-studio/commit/340c205ce28adad2de103fa99276b9182ce28c38>)

### Description
Fix grouped encoder disconnect/reconnect behavior; this was included in all public Enhanced Broadcasting builds (original commits was <https://github.com/amazon-contributing/upstreaming-to-obs-studio/commit/340c205ce28adad2de103fa99276b9182ce28c38>), but missed in <https://github.com/obsproject/obs-studio/pull/10349>

### Motivation and Context
Follow-up to <https://github.com/obsproject/obs-studio/pull/10349>, fixes encoders never receiving frames again after e.g. the multitrack output disconnected and tries to reconnect

### How Has This Been Tested?
Twitch Enhanced Broadcasting beta

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-04-19 16:18 UTC, RytoEX requested changes
Nit.

2024-04-19 16:18 UTC, RytoEX commented on libobs/obs-encoder.c
>  		pthread_mutex_unlock(&encoder->encoder_group->mutex);
Nit: line break after un-enclosed `if` statements.

2024-04-19 16:21 UTC, palana commented on libobs/obs-encoder.c
>  		pthread_mutex_unlock(&encoder->encoder_group->mutex);
@RytoEX: added a line break

2024-04-19 17:55 UTC, derrod approved these changes

2024-04-19 18:37 UTC, RytoEX approved these changes

2024-04-20 23:54 UTC, Lain-B approved these changes

2024-04-20 23:54 UTC, merged