obs-filters: Add white balance to color filter
obsproject/obs-studio pull request #10695
Opened 2024-05-19 14:00 UTC by mar10iana

### Description

We added three white balance sliders to the color correction filter, as shown on the screenshots below:

![IMG_8447](https://github.com/obsproject/obs-studio/assets/119081577/2dc281c7-21ef-4671-bc6e-4cfb760d0e58)
![IMG_1899](https://github.com/obsproject/obs-studio/assets/119081577/59e5d4be-24ac-469e-97fe-8f9f2201c85d)

The following changes have been made to the code:
- Added new settings for red, green, and blue white balance adjustments.
- Updated the color_correction_filter_data structure to include white balance variables.
- Modified the create functions to initialize the white balance values.
- Implemented white balance matrix computation in the update functions.
- Integrated the white balance matrix into the final matrix used for color correction.
- Updated the properties functions to add sliders for white balance adjustments.
- Set default values for the new white balance settings.

### Motivation and Context

Currently, OBS offers a variety of color correction filters, but lacks a dedicated white balance feature, which is essential for many users. This feature aims to address this problem by introducing three white balance sliders (red, green and blue) that adjust the color temperature. 

Ideas website link: https://ideas.obsproject.com/posts/2582/white-balance

### How Has This Been Tested?

We tested our feature in a macOS environment. 
To test this feature you should go to the color correction filter and check the newly added sliders. If you change the value of the slider, the colours of your source will be updated.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-05-25 23:23 UTC, WizardCM commented
Is it common for white balance to be split into three separate sliders? Keeping in mind OBS is used by a variety of users, some with very intricate knowledge of video/colour and others who just want to make it look good with as little configuration as possible.

2024-05-25 23:25 UTC, RytoEX requested changes
Do not use merge commits to catch up on branch/repo history. Use `git rebase`.

2024-05-26 11:27 UTC, mar10iana commented
> Is it common for white balance to be split into three separate sliders? Keeping in mind OBS is used by a variety of users, some with very intricate knowledge of video/colour and others who just want to make it look good with as little configuration as possible.

This method offers the highest level of control, allowing precise fine-tuning of color balance across the spectrum. It's ideal for professional users who need to correct complex color casts or achieve specific color grading effects.
For regular users, like myself, despite not being the simplest option, I still find this method pretty straightforward to use.
But ultimately it is up to you guys! We can change it if needed :)

2024-06-03 15:20 UTC, Warchamp7 commented
I'm wondering if this makes sense as part of the color correction filter or if it should be a separate filter of it's own.

2024-06-04 11:08 UTC, mar10iana commented
> I'm wondering if this makes sense as part of the color correction filter or if it should be a separate filter of it's own.

White balance is usually under the color correction tab on photo and video editing programs such as Adobe Photoshop, After Effects, and others. Our decision was based on this and the fact that changing the white balance is color correcting the image.

2024-06-04 20:26 UTC, Fenrirthviti commented
Just putting my vote that I agree on the above. I've actually several times added an OBS color correction filter mistakenly thinking it had white balance in the past, heh. I think it's a common enough paradigm that users would expect to find it there.

2024-07-24 20:41 UTC, Warchamp7 commented
Gonna stick to my original feedback here. I think it is fine to keep the 3 channels for the options but I think this should be moved into a new separate `White Balance Filter` option instead of crowding the Color Correction one even further.

This will also allow better control for whether to white balance before or after a Color Correction filter, for example.

2025-01-23 13:55 UTC, mar10iana commented
> Gonna stick to my original feedback here. I think it is fine to keep the 3 channels for the options but I think this should be moved into a new separate `White Balance Filter` option instead of crowding the Color Correction one even further.
> 
> This will also allow better control for whether to white balance before or after a Color Correction filter, for example.

Should implement this change?

2025-02-06 23:55 UTC, Warchamp7 requested changes
Create a separate White Balance filter for this functionality instead

2025-02-07 07:48 UTC, mar10iana commented
> Create a separate White Balance filter for this functionality instead

I will do it this weekend, thank you.

2025-02-07 11:06 UTC, closed without merging

2025-02-09 17:59 UTC, mar10iana commented
> Create a separate White Balance filter for this functionality instead

Sorry for making another PR instead of updating the last one, but this way was just easier for me.
https://github.com/obsproject/obs-studio/pull/11850