Reset YouTube Live Chat dock on `StreamingStop`.
obsproject/obs-studio pull request #10709
Opened 2024-05-22 23:08 UTC by msuman-google

### Description
This will use the same placeholder URL that is used before a stream is started.

### Motivation and Context
When a stream ends, the input bar for sending chat messages should no longer
be active. It wouldn't work even if it was active.

### How Has This Been Tested?
Built OBS locally on Linux workstation, started and stopped a live stream.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2024-05-24 00:09 UTC, RytoEX requested changes
Do not use merge commits to catch up on branch/repo history. Use `git rebase`.

Do not use final punctuation in PR titles or commit message subjects (the first line of a commit message).

2024-05-25 23:41 UTC, tytan652 commented
This reset the chat dock even if the broadcast has not been ended, which is wrong.
A user can still stream to the same broadcast if it has not been ended (autostop on ended manually).

2024-05-28 17:24 UTC, msuman-google commented
> This reset the chat dock even if the broadcast has not been ended, which is wrong. A user can still stream to the same broadcast if it has not been ended (autostop or ended manually).

Interesting. I was going by the prompt that is shown right after clicking `Stop streaming` (see https://ibb.co/XC477pD). I will close this pull request based on this comment.

2024-05-28 17:24 UTC, closed without merging

2024-05-28 17:55 UTC, tytan652 commented
This prompt is when the broadcast has autostop enabled indeed, but when it's not present there is a "end broadcast" button and the user can re-stream to this broadcast.