UI:Implement drag-and-drop from sources to scenes
obsproject/obs-studio pull request #10713
Opened 2024-05-23 11:34 UTC by Diog0o

### Description

The Drag-and-Drop feature allows users to effortlessly move sources or groups of sources into scenes within the user interface. This intuitive functionality enhances user interaction by providing a visual and interactive way to organize and customize content.

The feature mimics the behaviour of a copy and paste. For example if we drag a "Input Audio Device" from Scene 1 to Scene 2, after the event, both Scene 1 and Scene 2 will have the "Input Audio Device" source.

Start:
State of Scene 1 and Scene 2
![image](https://github.com/obsproject/obs-studio/assets/75538603/0d8368f1-3ca8-4f54-9c00-b133b8557e10)
![image](https://github.com/obsproject/obs-studio/assets/75538603/0bb627ea-97f9-4afc-bbd7-8bf6b4b79098)

During the Drag and Drop from the "Audio Input Capture" from Scene 1 to Scene 2:
![Imagem WhatsApp 2024-05-23 às 12 20 10_d1a6b6ce](https://github.com/obsproject/obs-studio/assets/75538603/c942af01-4891-4666-a56c-571bfe916c32)

After the drag and drop operation:
![image](https://github.com/obsproject/obs-studio/assets/75538603/4dfd7a32-0ebd-4efd-9c17-e7ed23802506)

### Motivation and Context

As live streaming and digital content creation grow, efficient tools are essential. The Drag-and-Drop feature in OBS simplifies the organization of sources, mimicking copy-and-paste behavior. By allowing users to easily duplicate sources between scenes, it improves workflow and ensures consistency, making OBS even more user-friendly and effective.

We got this feature idea from the Ideas page, and here is the link to the post: https://ideas.obsproject.com/posts/225/drag-and-drop-sources-into-other-scenes

### How Has This Been Tested?

We conducted extensive manual testing to ensure the reliability and functionality of the Drag-and-Drop feature. The testing process was carried out on Windows 11 to verify compatibility and performance, ensuring a seamless user experience across different scenarios.

### Types of changes

New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-05-23 12:13 UTC, tytan652 requested changes
Don't reorder includes if you add some at the same time, it add *noise* to the readability of the PR.

Please for each added include check if the compiler requires them to be added.

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.cpp
> +
Unnecessary whitespace

2024-05-23 12:13 UTC, tytan652 commented on UI/scene-tree.cpp
> +
```suggestion
```

This has nothing to do here, I guess this is why `<obs-module.h>` was added.

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.cpp
> +
Unnecessary whitespace

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.cpp
> +	Qt::DropAction dropAction = drag->exec(supportedActions);
```suggestion
	drag->exec(supportedActions);
```
The returned object is unused

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.cpp
> +
Unnecessary whitespace

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.hpp
> +#include <QVector>
Don't reorder includes

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.cpp
> +bool SourceTree::get_selected_source_names(obs_scene_t *scene,
```suggestion
static get_selected_source_names(obs_scene_t */*scene*/,
```

This static function has no reason to be made public.

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.hpp
> +					      void *param);
```suggestion
```
I think declaring the static function as public is not needed at at all.

2024-05-23 12:13 UTC, tytan652 commented on UI/source-tree.hpp
> +	QPoint dragStartPosition;
Move it before the first `public:`, it's private by default.

2024-05-23 12:13 UTC, tytan652 commented on UI/scene-tree.cpp
> +#include "obs.h"
Those includes are wrong. And before fixing them check if those are necessary.

2024-05-23 12:13 UTC, tytan652 commented on UI/scene-tree.cpp
> +#include <obs-module.h>
```suggestion
```

Unnecessary include addition, this one is meant for mainly plugins

2024-05-23 13:20 UTC, gxalpha requested changes
> The Drag-and-Drop feature allows users to effortlessly move sources or groups of sources into scenes within the user interface. This intuitive functionality enhances user interaction by providing a visual and interactive way to organize and customize content.

I would dispute the word "intuitive" here. Personally I'm against this change, if anything I feel like a source should be moved to the other scene, not copied. But scenes aren't groups, personally I'd rather not have either.
Though to be clear, this isn't my call to make, I just wanted to voice my opinion. For now there's no need to act on the above (any action would just be closing the PR anyways).


As for the implementation:
It removes any indication of where an internal move (from source-tree to source-tree) lands - this isn't great. Additionally, there's no indication for where a copied source ends up and whether it succeeds.
Additionally, it appears to be quite buggy. Dragging a source onto the current scenes duplicates it, but then removing the second source either deletes both or straight up crashes the app. Please look into that, as well as the consequences for the undo/redo (I don't believe it's implemented at all; but it should be). For reference, I tested this on macOS.

Also, I'd recommend using the C++-Objects `OBSSource` and `OBSSourceAutoRelease` to avoid `obs_source_release` calls (this might even fix the other problem if you're lucky).

2024-07-24 20:55 UTC, Warchamp7 commented
While I understand the desire here, there needs to be more structural changes to the Scenes dock before I'd be comfortable supporting this.

Right now the Scenes dock changes the active scene upon item selection when not in Studio mode. In the context of this PR it leads to one of two outcomes:

- Scene becomes active: Inadvertent scene change to the scene the source was dragged to
- Scene does not become active: Lack of feedback on user action

We may revisit this functionality in the future if/when such adjustments to the Scenes dock functionality happens.

2024-07-24 20:55 UTC, closed without merging