Implement `DeleteCookies` for the YT Service dock.
obsproject/obs-studio pull request #10710
Opened 2024-05-22 23:21 UTC by msuman-google

### Description
Implement `DeleteCookies for YT service integration dock, similar to other service integration docks.

### Motivation and Context
This will enable centralized cookie management for YouTube/Google account logins for other browser docks using the shared cookie manager.

### How Has This Been Tested?
Built OBS locally on Linux workstation, connected YouTube account (via OAuth), disconnected YouTube OAuth, verified no cookies were remaining. For purposes of testing, I copied over cookies from the YTCP cookie manager after logging into YouTube Studio.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-05-24 00:10 UTC, RytoEX requested changes
Do not use merge commits to catch up on branch/repo history. Use `git rebase`.

Do not use final punctuation in PR titles or commit message subjects (the first line of a commit message).

2024-05-24 20:27 UTC, msuman-google commented
> Do not use merge commits to catch up on branch/repo history. Use `git rebase`.
> 
> Do not use final punctuation in PR titles or commit message subjects (the first line of a commit message).

Done.

2024-05-28 20:34 UTC, RytoEX commented
> Do not use final punctuation in PR titles or commit message subjects (the first line of a commit message).

This is still using final punctuation (a period at the end) of the commit message subject.

```
UI: Implement DeleteCookies for YT Service dock.

This will enable centralized cookie management for YouTube/Google
account logins for other browser docks using the shared cookie manager.
```

Could you elaborate on how this enables "centralized cookie management for YouTube/Google account logins"?

2024-05-30 19:45 UTC, RytoEX commented
> Done. Fixed, sorry, I did not realize that was disallowed.

For what it's worth, our [Contributing Guidelines](https://github.com/obsproject/obs-studio/blob/9eca7b75252666f2c9790adbce497f52cf72b41f/CONTRIBUTING.rst) cover this in the linked ["How to Write a Git Commit Message"](https://cbea.ms/git-commit/#end).

> Yes, see #10747. I'm working on another change to improve the chat UX when the user is signed-in, will send the pull request shortly.

Ideally, the context and "why" should be provided here, at least in summary form. If you must point to another PR for additional context, it should be linked in the Motivation section. In this case, this seems more like these changes "enable a future implementation of centralized cookie management" rather than enabling such itself, which was the main point of confusion internally while reviewing this. This by itself only "implements DeleteCookies", and the question brought up in review was, "why?" If you could answer "why?" in the PR's Motivation section, that would be helpful to reviewers.

2024-05-30 22:49 UTC, msuman-google commented
> > Yes, see #10747. I'm working on another change to improve the chat UX when the user is signed-in, will send the pull request shortly.
> 
> Ideally, the context and "why" should be provided here, at least in summary form. If you must point to another PR for additional context, it should be linked in the Motivation section. In this case, this seems more like these changes "enable a future implementation of centralized cookie management" rather than enabling such itself, which was the main point of confusion internally while reviewing this. This by itself only "implements DeleteCookies", and the question brought up in review was, "why?" If you could answer "why?" in the PR's Motivation section, that would be helpful to reviewers.

Done. Updated the motivation section.

2024-06-05 21:57 UTC, msuman-google commented
Gentle ping for review, please LMK if the PR's motivation section looks better.

2024-07-24 20:55 UTC, closed without merging