obs-webrtc: Do not use curl_easy_nextheader
obsproject/obs-studio pull request #10786
Opened 2024-06-06 18:33 UTC by Sean-Der

### Description
API not available in Ubuntu 22.04 which ships 7.81 this API was first available in 7.83

### Motivation and Context
Fixes build on Ubuntu 22.04

### How Has This Been Tested?
Tested against WHIP server with TURN
Tested against Broadcast Box
Tested against Twitch

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2024-06-06 18:33 UTC, Sean-Der commented
@tt2468

2024-06-07 09:10 UTC, tt2468 requested changes

2024-06-07 09:10 UTC, tt2468 commented on plugins/obs-webrtc/whip-output.cpp
> +		if (value == "") {
Nitpicks:
- `value == ""` -> `value.empty()`
- No brackets since it's just a single statement

2024-06-07 09:10 UTC, tt2468 commented on plugins/obs-webrtc/whip-output.cpp
> +	std::string last_location_header = "";
std::string does not require initialization, it is initialized on declare.

2024-06-07 09:10 UTC, tt2468 commented on plugins/obs-webrtc/whip-output.cpp
> +		if (value == "") {
Same nitpicks from above here

2024-06-07 09:25 UTC, tt2468 commented
Other than those nitpicks, the code looks good to me. It builds for me now on Ubuntu 22.04. Unfortunately, I am unable to test it at the moment due to `master` locking up somewhere in the EB code when I try to go live.

2024-06-07 15:17 UTC, Sean-Der commented
All fixed! Can I get another review @tt2468 

WHIP output has been fixed in master with da8fc0d5166e81788cc47ffab0dde4d29b3fb790

2024-06-07 19:34 UTC, DDRBoxman approved these changes

2024-06-07 19:35 UTC, RytoEX approved these changes

2024-06-07 19:36 UTC, merged