UI: Check VC++ Runtime version on startup
obsproject/obs-studio pull request #10809
Opened 2024-06-09 01:18 UTC by derrod

### Description

Adds a check on startup that ensures a compatible Visual C++ runtime is being used.

The user is given the option to automatically open our existing VC runtime download page (https://obsproject.com/visual-studio-2019-runtimes),

### Motivation and Context

Due to backwards-incompatible changes in MSVC 14.40 OBS crashes on startup for some users that do not have up to date runtimes installed.

We should also adjust the updater and installer to check for these older versions, but that will be a larger undertaking and also does not cover the use case of portable ZIPs (unlike this PR).

### How Has This Been Tested?

Tested on Windows VM with outdated vc runtime:

![warning](https://github.com/obsproject/obs-studio/assets/3123295/53412cf9-4f6e-482b-afe1-d1d127d7d527)

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-06-09 14:23 UTC, notr1ch commented on UI/obs-app.cpp
> +#elif defined(_WIN32)
```suggestion
#else
```

2024-06-09 19:58 UTC, derrod commented on UI/obs-app.cpp
> +#elif defined(_WIN32)
Whoops, fixed.

2024-06-09 20:11 UTC, RytoEX requested changes

2024-06-09 20:11 UTC, RytoEX commented on UI/obs-app.cpp
> +static constexpr char vcRunErrorTitle[] = "Outdated Visual C++ Run Version";
```suggestion
static constexpr char vcRunErrorTitle[] = "Outdated Visual C++ Runtime Version";
```

2024-06-10 01:36 UTC, notr1ch commented
Perhaps the wording could be changed to "You will now be directed to the download page." with OK / Cancel buttons. Currently it's unclear that pressing "No" will exit OBS.

2024-06-10 19:08 UTC, derrod commented
I updated the wording (not the screenshot though). I also wasn't super happy with it, but I didn't have any better ideas. Perhaps @Warchamp7 has a suggestion as well.

Either way I'd like to have this for beta2 (alongside the updater/installer changes) so we can mitigate the VC runtime mess as much as possible.

2024-06-10 20:51 UTC, RytoEX approved these changes
Maybe there's a better way to handle this, but if we figure that out, we can make further changes later. Let's mitigate this as much as we can.

2024-06-10 20:51 UTC, merged

2024-06-13 06:57 UTC, wang-bin commented
I my project I find out the std::mutex is incompatible with old msvcp140.dll, I tested with the simplest mutext code. Adding `-D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` can fix the incompatibility

2024-06-13 15:24 UTC, RytoEX commented
> I my project I find out the std::mutex is incompatible with old msvcp140.dll, I tested with the simplest mutext code. Adding `-D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` can fix the incompatibility

We considered this and decided against it.