UI: Translate Multitrack Video error dialog buttons
obsproject/obs-studio pull request #10823
Opened 2024-06-10 22:46 UTC by RytoEX

### Description

UI: Translate Multitrack Video error dialog buttons

The Yes and No standard buttons are not translated unless we manually set the translated text ourselves.

### Motivation and Context

A user reported to us in OBS Studio 30.2.0-beta1 that these buttons were not translated. We already use this pattern elsewhere in the codebase.
https://github.com/obsproject/obs-studio/blob/0680b642e9cb85101971e8e03bbcd9b574cff6f7/UI/ui-validation.cpp#L47-L49

### How Has This Been Tested?

I've built this locally on Windows 11, but I could not seem to get this specific dialog to pop up.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-06-10 22:48 UTC, RytoEX commented
For further cleanup, we could probably move `QMessageBox mb` into the first `if` branch, and change the second branch to use `OBSMessageBox::critical` instead. We don't have an OBSMessageBox function that uses the Warning icon that uses Yes/No buttons, or I would suggest we use that. We could add one, but that was more work than I wanted to do this moment.

2024-06-10 22:48 UTC, derrod commented on UI/multitrack-video-error.cpp
> +			return true;
Just use `return mb.clickedButton() == yesButton;`

2024-06-10 22:49 UTC, RytoEX commented on UI/multitrack-video-error.cpp
> +			return true;
Done.

2024-06-10 23:10 UTC, derrod requested changes
Based on the documentation you'd still need to call `exec`, otherwise thid will always return null: https://doc.qt.io/qt-6/qmessagebox.html#clickedButton

2024-06-10 23:46 UTC, RytoEX commented
> Based on the documentation you'd still need to call `exec`, otherwise thid will always return null: https://doc.qt.io/qt-6/qmessagebox.html#clickedButton

Whoops. Fixed.

2024-06-11 00:26 UTC, derrod approved these changes
Seems fine but unable to test right now

2024-06-11 15:58 UTC, gxalpha approved these changes

2024-06-11 17:22 UTC, merged