UI: Add supported codecs to GetClientConfiguration request
obsproject/obs-studio pull request #10879
Opened 2024-06-18 15:46 UTC by palana

### Description
Communicate available codecs to configuration API for multitrack video output streams

The default value for this according to the current (still WIP) version of the Twitch/IVS integration guide is `['h264']`, so enabling HEVC or AV1 will require this at some point in the future

### Motivation and Context
OBS built without HEVC support does not(?) support HEVC, even though e.g. hardware encoders may be capable of producing HEVC bitstreams; also, codecs may not be supported in case hardware encoders are disabled on startup or similar

### How Has This Been Tested?
Twitch Enhanced Broadcasting beta internal testing

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-06-18 18:19 UTC, RytoEX requested changes
Seems okay at a glance, aside from the one question I posed about `qstricmp` vs. `astrcmpi`.

2024-06-19 11:03 UTC, palana commented on UI/goliveapi-postdata.cpp
> +		} else if (qstricmp(codec, "av1")) {
I keep forgetting about it (and it requires another include, thus increasing the chances of me forgetting about it 😅)

will add a fixup commit if you'd rather have this use `astrcmpi`

2024-06-19 11:25 UTC, palana commented on UI/goliveapi-postdata.cpp
> +		} else if (qstricmp(codec, "av1")) {
@RytoEX: pushed a fixup commit; feel free to squash or remove

2024-06-19 16:07 UTC, RytoEX commented on UI/goliveapi-postdata.cpp
> +		} else if (qstricmp(codec, "av1")) {
We'll drop the fixup and keep `qstricmp` here to avoid the extra header inclusion.

2024-06-19 16:07 UTC, RytoEX approved these changes

2024-06-19 16:27 UTC, merged