cmake: Fix ffmpeg version regex
obsproject/obs-studio pull request #10919
Opened 2024-06-25 23:22 UTC by Penwy

### Description

This adds `~` to the list of characters accepted as part of a correct version name for ffmpeg in `/cmake/finders/FindFFmpeg.cmake`.

### Motivation and Context

Ffmpeg version `6.1-1build2~22.04` (from https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/ffmpeg6) failed to be found while setting up cmake, due to the `~` character in the version name. Tildes are frequent enough in linux version names that I feel their inclusion here is warranted.
Legacy cmake hasn't been changed as it correctly finds that ffmpeg version.

### How Has This Been Tested?

Verified that it was still correctly compiling, both with that ffmpeg and the distro one (which doesn't have a tilde), both in legacy and modern cmake.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-06-25 23:28 UTC, PatTheMav approved these changes
Should be fine.

2024-06-26 03:11 UTC, RytoEX commented
Could you provide the full line in the header file that this targets?

2024-06-26 03:31 UTC, RytoEX requested changes
Nit:
* ffmpeg -> FFmpeg

2024-06-26 07:05 UTC, Penwy commented
> Could you provide the full line in the header file that this targets?

This targets line 4 of `ffversion.h`.
On the PPA version I linked : `#define FFMPEG_VERSION "6.1-1build2~22.04"`
On the base distro version : `#define FFMPEG_VERSION "4.4.2-0ubuntu0.22.04.1"`

> ffmpeg -> FFmpeg

Done

2024-06-26 16:26 UTC, RytoEX commented
Thanks. I see the issue now. The regex is quite strict and requires a matching pair of double-quotes (`"`) around the target version number string. This is why it won't simply match `6.1-1build2`, which would otherwise be valid. I do not remember why exactly we did this, but I have a vague recollection that we did it based on specific findings in the wild.

2024-06-26 16:26 UTC, merged