Updated text-functionality.c
obsproject/obs-studio pull request #10956
Opened 2024-07-08 10:26 UTC by Anurag-Modak

uppdated load_text_from_file function

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2024-07-08 15:08 UTC, derrod requested changes
- Fill out the PR template
- Fix the formatting 
- Fix the commit message

2024-07-09 06:48 UTC, Anurag-Modak commented
> If you are interested in working on this please read the previous discussions on what is actually required to fix the issue, [#7595 (comment)](https://github.com/obsproject/obs-studio/issues/7595#issuecomment-1977012523)

Can you elaborate the issue to me

2024-07-13 22:17 UTC, norihiro commented on plugins/text-freetype2/text-functionality.c
> +        srcdata->text[(filesize - 2) / sizeof(wchar_t)] = L'\0';
`bzalloc` initialize the allocated region with 0.
Why was this line added?

2024-07-30 02:43 UTC, kkartaltepe commented
Thanks for the interest in the issue, but im going to close this since I have gone ahead to implement the fix I was intending.

2024-07-30 02:43 UTC, closed without merging