libobs: Create unique groups when duplicating scene
obsproject/obs-studio pull request #11092
Opened 2024-08-08 00:25 UTC by Warchamp7

### Description
Updates `obs_scene_duplicate` to always duplicate groups within the duplicated scene.

This fixes the weird behavior of groups in Studio Mode when Duplicate Scenes is ON and Duplicate Sources is OFF (These are the default settings)

### Motivation and Context
Studio mode allows users to modify a scene without the changes happening live in Program.

Since we default to Duplicate Scenes enabled and Duplicate Sources disabled, sources that are nested in a scene (or a group) still have their changes reflected immediately in program. In some cases, this is desirable behavior.

However, this has two drawbacks.

1. The size and position of a group updates based on its contents. This leads to extremely unpredictable behavior for groups with Studio Mode enabled on the default settings, as the groups size and position effectively desyncs
2. Most users don't realize that groups are scenes, and not a UI abstraction, meaning the nested scene behavior is usually confusing and undesirable

### How Has This Been Tested?
Adjusted the size and position of a group as well as it's contents in normal mode and studio mode.

Tested with all combinations of Duplicate Scenes and Duplicate Sources ON and OFF

CURRENT ISSUES:
Duplicating a scene via normal methods expectedly creates a new copy of the group, instead of a reference as might be expected. 

Current thought is to extend the `obs_scene_duplicate_type` enum with new entries specifically for Studio Modes duplication to be checked instead

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2026-06-08 18:38 UTC, Warchamp7 commented
This PR was originally Drafted due to duplicating a scene causing any groups in it to be created as duplicates rather than references.

However since this PR, our envisioned UX around groups has changed to prefer duplication and the new add source flow actively discourages group references.

Situations where users want a collection of sources that can be referenced in multiple places and updated once should use Scenes as sources and improvements around that workflow are planned. Groups should remain as strictly an organizational tool within a particular scene.

2026-08-26 14:37 UTC, PatTheMav requested changes
Also amend commit message with clear explanation for the "why" per our contribution guidelines.

2026-08-26 14:37 UTC, PatTheMav commented on libobs/obs-scene.c
> +		source = make_unique || item->is_group ? dup_child(&items, i, new_scene, make_private)
```suggestion
		source = (make_unique || item->is_group) ? dup_child(&items, i, new_scene, make_private)
```
Probably not necessary for the compiler, but as code is written for humans and just incidentally executed by a computer, the parens make it easier to read for  the former.

2026-08-26 14:37 UTC, PatTheMav commented on libobs/obs-source.c
> +			new_name = obs_source_get_name(source);
How is this change related to the other changes?

2026-09-03 22:15 UTC, Warchamp7 commented on libobs/obs-source.c
> +			new_name = obs_source_get_name(source);
I think this was leftover from a different approach I had tried? Not sure. It's removed now.

2026-09-03 23:03 UTC, Warchamp7 commented on libobs/obs-scene.c
> +		source = make_unique || item->is_group ? dup_child(&items, i, new_scene, make_private)
Updated.

2026-09-04 16:40 UTC, PatTheMav approved these changes

2026-09-08 21:14 UTC, RytoEX approved these changes

2026-09-10 17:45 UTC, merged