UI: Log sceneitem and filter enabled state on load
obsproject/obs-studio pull request #11135
Opened 2024-08-14 03:53 UTC by Penwy

### Description

This logs whether sceneitems and filters are enabled on scene collection load.
Inactive ones are prefaced with a `o` and active ones by a `*`.
An example log can be found [here](https://obsproject.com/logs/KMZMUjXiwl12Xg9d)

### Motivation and Context

Whether or not sceneitems/filters are enabled is often an important matter in support, having it logged would greatly simplify some support workflows.

### How Has This Been Tested?

Running obs, checking it logs correctly.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-08-14 04:07 UTC, prgmitchell commented
This is just my opinion of course but I think if this PR is introducing state logging on load it should also include logging of state changes.

2024-08-14 04:33 UTC, alinsavix commented
Would it perhaps be better to identify enabled or disabled filters just by adding `(disabled)` or `(enabled)` somewhere on the line? Or even just `(disabled)` for the disabled ones, with lack of it implying not-disabled?

That way no special knowledge is needed to read that information in the log, the filter lines are just self-explanatory.

2024-08-14 14:18 UTC, Penwy commented
> This is just my opinion of course but I think if this PR is introducing state logging on load it should also include logging of state changes.

I considered it but it is IMO, too verbose, and not that useful, in the same vein that, for example sceneitem order changes aren't logged, only sceneitem order on load.

> Would it perhaps be better to identify enabled or disabled filters just by adding `(disabled)` or `(enabled)` somewhere on the line? Or even just `(disabled)` for the disabled ones, with lack of it implying not-disabled?
> 
> That way no special knowledge is needed to read that information in the log, the filter lines are just self-explanatory.

Quite in the same vein, my goal was to preserve simplicity and keep verbosity at a minimum. I feel that the way it is is *decently* self explanatory, but am deffo open to other alternatives.

2024-08-14 15:19 UTC, prgmitchell commented
> > This is just my opinion of course but I think if this PR is introducing state logging on load it should also include logging of state changes.
> 
> I considered it but it is IMO, too verbose, and not that useful, in the same vein that, for example sceneitem order changes aren't logged, only sceneitem order on load.

I disagree with the comparison and don't think it would be very verbose unless someone is constantly enabling/disabling sources and filters. If the motivation for this change is to assist with support then having a way to determine the current state is more valuable then just knowing the initial state at load.

2024-08-14 22:40 UTC, Penwy commented
> > > This is just my opinion of course but I think if this PR is introducing state logging on load it should also include logging of state changes.
> > 
> > 
> > I considered it but it is IMO, too verbose, and not that useful, in the same vein that, for example sceneitem order changes aren't logged, only sceneitem order on load.
> 
> I disagree with the comparison and don't think it would be very verbose unless someone is constantly enabling/disabling sources and filters. If the motivation for this change is to assist with support then having a way to determine the current state is more valuable then just knowing the initial state at load.

After sleep and reconsideration, yeah, fair. Added.

2024-08-15 02:02 UTC, prgmitchell commented
I will also add that I agree with @alinsavix on using (disabled) for the disabled items only and logging nothing for something that is enabled.

2024-08-16 18:12 UTC, Penwy commented
Done.
I still personally dislike the way it prints, but if you two agree on this, I'll bow to the majority.
example log [here](https://obsproject.com/logs/F4xbYMrLA0Dh7nTz)

2026-02-27 21:34 UTC, Warchamp7 commented
@Penwy Can you fix up the conflict on this?

2026-05-08 20:36 UTC, RytoEX requested changes
Commit prefixes and PR prefix will need to be updated to "frontend: ".

Requested relevant reviews.

2026-05-08 20:36 UTC, RytoEX commented on frontend/components/SourceTreeItem.cpp
> +				     item_name, (long)id, name, enabled);
While clever, I think I'd just prefer the clarity of the string being "enabled" or "disabled":

```suggestion
				const char *enabled = val ? "enabled" : "disabled";
				const char *item_name = obs_source_get_name(obs_sceneitem_get_source(si));
				const char *name = obs_source_get_name(s);
				blog(LOG_INFO, "User set sceneitem '%s' (%li) on scene '%s' to %s (undo_redo)",
				     item_name, (long)id, name, enabled);
```

Or if it just did this in the blog call, unless @PatTheMav has any insight as to why we'd want an intermediate variable holding the value:
```suggestion
				const char *item_name = obs_source_get_name(obs_sceneitem_get_source(si));
				const char *name = obs_source_get_name(s);
				blog(LOG_INFO, "User set sceneitem '%s' (%li) on scene '%s' to %s (undo_redo)",
				     item_name, (long)id, name, val ? "enabled" : "disabled";);
```

2026-05-08 20:36 UTC, RytoEX commented on frontend/components/SourceTreeItem.cpp
> +		     enabled);
Same.

2026-05-08 20:36 UTC, RytoEX commented on frontend/components/VisibilityItemWidget.cpp
> +		blog(LOG_INFO, "User set filter '%s' on source '%s' to %sabled", filter_name, source_name, enabled);
Same.

2026-05-10 17:46 UTC, Penwy commented on frontend/components/SourceTreeItem.cpp
> +				     item_name, (long)id, name, enabled);
I forgot my reasoning for the intermediate variable, so I'll do it in the blog, as far as I can see that is no issue.

2026-05-10 17:52 UTC, Penwy commented
Upon revisiting it I realised this leaves one logging without that info :
When creating a new source or a sceneitem of an existing source through the "add source" dialog, the created sceneitem can be created disabled.
It is however impossible to log this in one line as the visibility is set *after* the creation of the sceneitem, and hence the logging of its creation.
Rather than add a second line of log for this, I think it is preferrable to not log the visibility status in that instance.

2026-05-18 03:08 UTC, norihiro commented on frontend/widgets/OBSBasic_SceneCollections.cpp
> +	blog(LOG_INFO, "%s- source: '%s' (%s) %s", indent.c_str(), name, id, enabled);
Can we avoid the unnecessary trailing space?

```suggestion
	blog(LOG_INFO, "%s- source: '%s' (%s)%s", indent.c_str(), name, id, obs_sceneitem_visible(item) ? "" : " (disabled)");
```

2026-07-02 23:30 UTC, Fenrirthviti approved these changes
I agree with the above comment, this seems fine as-is and if we run in to issues with readability or end-user confusion, we can always make adjustments later.

2026-08-19 17:22 UTC, RytoEX requested changes
This has a merge conflict.

2026-08-19 20:40 UTC, Penwy commented
Conflict fixed and took the opportunity to rename a couple variables to adhere to the new naming style

2026-08-19 21:16 UTC, Warchamp7 requested changes

2026-08-19 21:16 UTC, Warchamp7 commented on frontend/components/SourceTreeItem.cpp
> +				     item_name, (long)id, name, val ? "enabled" : "disabled");
If we **_are_** fixing up these names here the correct style would be camelCase.

`sceneItem`, `itemName`, `sceneSource`

2026-08-19 21:18 UTC, Penwy commented on frontend/components/SourceTreeItem.cpp
> +				     item_name, (long)id, name, val ? "enabled" : "disabled");
oh mb, forgot

2026-08-26 15:17 UTC, PatTheMav reviewed
I'm a bit unhappy about the semantics of "enabling" meaning actually "enabling" in the case of a filter, but just setting visibility of a scene item.

Wouldn't it make more sense to treat this consistently as "enabling" and "disabling" in the API and thus also use `obs_source_set_enabled` for scene items?

What's the difference between enabling a scene item and changing its visibility? And if there is a difference, why should we conflate those two things in the log, particularly as the log is not meant for end users but for technical support (it is far too spammy and unkempt for actual end users).

I can see a decent reason to conflate these things in "public" communication (dialog boxes, UI) because users might think about things visually ("I just hide the visual results of the filter by hiding the filter").

---

Ideally the function that sets visibility would log the visibility change and the function that enables or disables something logs its effect itself rather than punting this responsibility to the caller.

2026-08-27 04:57 UTC, Warchamp7 commented
> I'm a bit unhappy about the semantics of "enabling" meaning actually "enabling" in the case of a filter, but just setting visibility of a scene item.
> 
> Wouldn't it make more sense to treat this consistently as "enabling" and "disabling" in the API and thus also use `obs_source_set_enabled` for scene items?

I'm unclear what this suggestion is asking. One interpretation is sceneitems should pass the enable call to the sceneitems source which would not work thr way you think?

The other interpretation is purely a naming semantic suggestion (obs_sceneitem_set_enable vs obs_sceneitem_set_visible) which I think is a semantic difference we _should_ have.

> What's the difference between enabling a scene item and changing its visibility? And if there is a difference, why should we conflate those two things in the log, particularly as the log is not meant for end users but for technical support (it is far too spammy and unkempt for actual end users).

There is no difference because there is only a singular functionality. You cannot 'enable' a sceneitem. That is equivalent to it's visible state.

A sceneitem is a layer within a scene. It says "Take the output of 'source' and draw it at this coordinate and size".

Enabling a source on the other hand says "Render this sources output".

Calling enable/disable on a source when toggling a sceneitem visibility would mean EVERY sceneitem pointing to that source would change.

> Ideally the function that sets visibility would log the visibility change and the function that enables or disables something logs its effect itself rather than punting this responsibility to the caller.

This part I can agree with and only boils down to our other precedents for logging like this.

2026-08-27 07:48 UTC, Penwy commented
I feel there might be a misunderstanding about the purpose of this PR.
The goal of this isn't to log changes in libobs sceneitem/filter state. That would be pretty useless and very spammy as, for example every scene change would log a message for every single filter in that scene as their libobs enable state changes.

The goal of this is to log the *user-set* state of sceneitems/filters. Basically, whether the eye icon in the UI is on or off. This is strictly a frontend concept and that's why this PR is a frontend PR that doesn't touch libobs.

I chose to use the word "enable" instead of "visible" because functionally this "eye icon toggling" is the same frontend concept, and the fact it makes use of two different libobs concepts to apply itself onto libobs is not, to me, relevant to the frontend.

Furthermore, on the matter of " the log is not meant for end users but for technical support", I will however remark that most of the people performing technical support are not developers, and that in the current situation, they cannot be expected to have deep knowledge of the intricacies of obs' code structure. As such, splitting the logging between "visible" and "enabled" for a reason that is only apparent to those with knowledge of libob's naming structure felt unnecessary to me.

It's also why I chose to have the logging be in the frontend and not in the libobs functions it calls that set the libobs visibility.

---

I do agree that there are quite a few kerfuffles on naming and function conflation between frontend and libobs in this area, but I did not feel it was the purbview of this PR to address them.

2026-08-28 14:46 UTC, PatTheMav commented
So my confusion mostly stemmed from the fact that we make filters "invisible" by disabling the actual source, but we make scene items "invisible" by actually setting their visibility, which is fine insofar as we're interacting with two different objects here.

> There is no difference because there is only a singular functionality. You cannot 'enable' a sceneitem. That is equivalent to it's visible state.

If I'm not mistaken that's the verbiage this PR uses however - it uses "enable" and "disable" to describe both toggling the "visibility" (as the "eye" icon suggests) of a filter as well as a scene item.

And if we add code that uses this language in log output, then we effectively make it official that you enable/disable scene items the same way you enable/disable filters.

In principle I'm fine with that because that's also how I personally think about it, but I'm not sure whether other project members agree. And if we make this verbiage official, then I'd be right back to low-key complain that while we do say that scene items are "enabled" that on an API level I have to `set_visible` it and we use an "eye" icon as the UI element to change it instead of a checkbox.

I would not hoist the expectation to fix that onto this PR, but I wanted to point out the possible inconsistencies and check whether we'd be "happy" with them.

---

> The goal of this is to log the user-set state of sceneitems/filters. Basically, whether the eye icon in the UI is on or off. This is strictly a frontend concept and that's why this PR is a frontend PR that doesn't touch libobs.

What are the support use-cases this can help with? I'm not opposed to it in principle (and indeed if we had structured logging it would make it easier to log even more "stuff" while making it a whole lot easier for supporters to filter, parse, and work with them).

Right now there is no way to properly distinguish many log messages (e.g. whether the event was triggered by the "system" or whether it's something that was triggered by the user) and I have no grasp on how much we already log frontend actions by the user.

But in this case I agree that the log calls should remain in the frontend then.

2026-08-28 15:58 UTC, Penwy commented
> we effectively make it official that you enable/disable scene items the same way you enable/disable filters.

Not as an argument for/against, more of a fyi, the project already uses the wording "enabled" to describe sceneitem visibility [in obs-websockets](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#setsceneitemenabled).

> What are the support use-cases this can help with?

I'd say the most "classical" one is "why is this source not showing"/"why is that filter not working" which can often lead into rabbit holes of trying to figure out why it doesn't before the support volunteer remembers to check enabled state (which, currently can only be done with a screenshot of the sceneitem/filter list).

There's a couple other, like, not looking into possible interferences and such if the sceneitems of the corresponding sources are disabled, etc.
It is a general help to understanding the user's setup and giving more accurate answers/suggestions

2026-09-02 14:22 UTC, PatTheMav commented on frontend/components/VisibilityItemWidget.cpp
> +		const char *sourceName = obs_source_get_name(parent);
If a source has two filters applied (which makes one filter the parent of another at least from the POV of the renderer), does `obs_filter_get_parent` still return the scene item's source?

2026-09-02 15:36 UTC, Penwy commented on frontend/components/VisibilityItemWidget.cpp
> +		const char *sourceName = obs_source_get_name(parent);
From what I could see when first testing this, and as shown in the log below, at least for the purposes of getting the source's name, yes.
https://obsproject.com/logs/34hYi177xvJIVbfa

Edit: and from what I can see, while `filter_target` is set to the next filter in the scene if any, `filter_parent` [is set to the source the filter is added to](https://github.com/obsproject/obs-studio/blob/a2400fe9803811b6e691a019e8bc2b1acfaf6250/libobs/obs-source.c#L3141), and never changed to be the previous filter in the chain if any.

2026-09-02 16:57 UTC, PatTheMav approved these changes
Seems fine overall, I'll leave verbiage approval to @Warchamp7.

2026-09-18 20:12 UTC, Warchamp7 approved these changes

2026-09-18 20:23 UTC, RytoEX approved these changes

2026-09-18 20:32 UTC, merged