Bye bye jammy
obsproject/obs-studio pull request #11147
Opened 2024-08-18 01:15 UTC by derrod

### Description

Remove Ubuntu 22.04 support and workarounds. Update CI to 24.04.

### Motivation and Context

22.04 is old and having to deal with its old dependencies (especially Qt) is becoming increasingly burdensome.

### How Has This Been Tested?

Hasn't.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)
- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-08-18 17:57 UTC, Warchamp7 commented
Noting that we have planned and communicated to do this 12~ months after 24.04 which would be April

https://github.com/obsproject/obs-studio/discussions/9055

2024-08-20 22:00 UTC, RytoEX requested changes
Might be one other place to remove the jansson macro.

2024-08-20 22:01 UTC, PatTheMav requested changes
You forgot to remove the lower compatible FFmpeg target in `plugins/obs-ffmpeg/cmake/dependencies.cmake`.

2024-08-21 06:13 UTC, derrod commented on UI/update/models/whatsnew.hpp
> -#endif
Yep, this was copied there too.

2024-08-21 06:14 UTC, derrod commented
> You forgot to remove the lower compatible FFmpeg target in `plugins/obs-ffmpeg/cmake/dependencies.cmake`.

Bumped the minimum to `6.1` there and in the libobs `CMakeLists.txt`.

2024-08-21 18:33 UTC, RytoEX approved these changes
Tentatively LGTM

2024-08-22 18:58 UTC, Gol-D-Ace approved these changes
Like already discussed internally I'm fine with ending support for 22.04 now because people should or will very shortly have an official upgrade path from 22.04 to 24.04.

We also offer alternatives (Flatpak) in case you don't want to upgrade your LTS yet but still prefer to have new obs features

2024-08-22 20:03 UTC, Gol-D-Ace commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
From my memory they get handled by ffmpeg now. At least I don't have them in my PPA config either.

2024-08-22 20:06 UTC, RytoEX commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
This does seem to suggest that libavformat depends on librist and libsrt, unless I'm misreading it.
https://packages.ubuntu.com/noble/libavformat60

2024-08-22 20:10 UTC, RytoEX commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
In any case, there should be no harm in explicitly moving the `UBUNTU_2210_OR_LATER` section into this section.

2024-08-22 20:12 UTC, derrod commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
The setup script already installs those for recent enough Ubuntu versions, though we could move these items to the main apt command now.

https://github.com/obsproject/obs-studio/blob/46b5f7e6d079f06f2a0ca426d89b429c5013e097/.github/scripts/utils.zsh/setup_ubuntu#L108

2024-08-22 20:37 UTC, RytoEX commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
> though we could move these items to the main apt command now.

I think that's the suggestion.

2024-08-22 21:13 UTC, PatTheMav commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
Yep I couldn't find the `UBUNTU_2210_OR_LATER` in the changed files, but that's what I was aiming at - the whole check is unnecessary with a move to 24.04.

2024-08-23 08:05 UTC, derrod commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
Updated the scripts

2024-08-23 17:37 UTC, RytoEX approved these changes
LGTM

2024-08-23 17:37 UTC, RytoEX commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
The update looks good to me.

2024-08-23 17:41 UTC, RytoEX commented on .github/scripts/utils.zsh/setup_ubuntu
> +  libffmpeg-nvenc-dev
Going to make the call to resolve this feedback thread.

2024-08-23 17:44 UTC, merged