UI: Add preview zoom widgets
obsproject/obs-studio pull request #11182
Opened 2024-08-24 04:15 UTC by cg2121

### Description
This adds preview zoom out and zoom in buttons next the the scaling percent label. This also adds these as actions in the scaling menu, along with a reset zoom action.

![Screenshot from 2024-08-23 22-24-45](https://github.com/user-attachments/assets/58642e98-c197-4473-9400-9ffb07c4e7e5)

### Motivation and Context
Makes the scaling UI better

### How Has This Been Tested?
Zoomed in and out the preview

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-10-07 20:43 UTC, Warchamp7 commented
This was something on my todo list for after the Preview controls were added. Will need a visual pass from myself at some point

2025-02-08 23:22 UTC, Warchamp7 approved these changes
I've rebased and modified this PR with some small adjustments and cleanup

2025-02-12 19:03 UTC, RytoEX requested changes

2025-03-13 20:10 UTC, RytoEX commented on frontend/data/themes/Yami.obt
> +}
I have force pushed these changes.

2025-03-14 12:42 UTC, RytoEX approved these changes

2025-04-01 21:31 UTC, merged