libobs: Deprecate obs_get_transition_by_[name|uuid]
obsproject/obs-studio pull request #11206
Opened 2024-08-28 00:38 UTC by gxalpha

### Description

`obs_get_transition_by_name` is very problematic because transitions are always private and their names aren't unique. This means that the method iterates over all private sources and then takes the first that both is a transition and matches the name we're looking for. However, this could be from anywhere - it could be a frontend transition, but also a source transition, quick transition, or even one from third-party plugins. This is always never what is intended.

As such, this method (which should never have been added in the first place) needs to go. In its place, `obs_frontend_get_transitions` returns a list of all frontend transitions (which is usually what people are looking for), and alternatively `obs_get_source_by_uuid` also provides access to private sources.

While we're at it, `obs_get_transition_by_uuid` is basically a wrapper for `obs_get_source_by_uuid` and not really necessary. UUID's are unique and a source doesn't suddenly change its type, so if you have a transition's UUID you can be pretty sure that when you do `obs_get_source_by_uuid`, it will still be a transition.

I optimistically set 31.0 as the deprecation version in the docs but will update once that is no longer possible.

### Motivation and Context

#11200 revealed that this method did make it in (#5504, c36a5ae92b32d7b8401c468c7f20fabeb05d775f). While its usages were quickly removed after the accompanying browser PR got merged (because of the aforementioned problems), the method stayed (I really should have removed it, this is my fault. Or better yet, not even have written it. Three years ago me was a bad programmer (me in three years will probably say the same about current me!)).

### How Has This Been Tested?

Checked GitHub code search to find no usages of these methods (besides the usual forks and bindings), which is good.
Dokumentation no longer appears to build on forks, so will need this PR to see whether it worked as I want.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-08-31 23:30 UTC, WizardCM commented
I absolutely agree with deprecating `obs_get_transition_by_name`, but have less confidence in deprecating `obs_get_transition_by_uuid`, as the internals could change in the future and having them separate could be useful. Generally if a user is interacting with a transition, the API scope should reflect that.

2024-09-01 11:26 UTC, gxalpha commented
> as the internals could change in the future

Which internals are you thinking of here specifically? If `source_by_uuid` suddenly stops returning internal sources that would be quite the breaking change anyways, so would UUIDs changing internally.

2025-01-23 19:38 UTC, RytoEX requested changes
Seems straightforward. Change the "deprecated version" to 31.1. I'd appreciate an approval from someone else before I merge this.

2025-01-24 14:58 UTC, gxalpha commented
Updated.

2025-02-15 01:14 UTC, Lain-B approved these changes

2025-03-13 21:25 UTC, RytoEX approved these changes

2025-04-01 21:07 UTC, merged