UI: Change clip level to 0.0 dB
obsproject/obs-studio pull request #11230
Opened 2024-09-01 01:16 UTC by cg2121

### Description
This changes the clip level of the volume meters from -0.5 dB to 0.0 dB.

### Motivation and Context
I think the original intention was to tell users they had too loud of audio without actually clipping the audio. But if audio was intended to be this high of level, such as music, it would show it was clipping without it actually clipping. 

Brought up by @PatTheMav off thread.

### How Has This Been Tested?
Tested audio with a high dB level, but not clipping, to make sure the volume controls didn't show the clipping indicators.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-09-02 09:01 UTC, SuslikV commented
Right now it affects only input meter (small rectangle).

2024-09-03 01:33 UTC, cg2121 commented
Fixed the code now, so the clip level affects both the input and output meters.

2024-09-29 23:30 UTC, Warchamp7 approved these changes

2024-10-10 20:28 UTC, DeeDeeG commented
Hi all, I have a rebased copy of this PR's commits, in case it saves anyone the time/tedium. Feel free to grab from there if it's helpful. (If not, apologies for the noise.) Best regards.

https://github.com/obsproject/obs-studio/compare/master...DeeDeeG:obs-studio:cg2121_clip-level_PR11230_rebased

<details>

Rebase was a little involved due to https://github.com/obsproject/obs-studio/pull/9407 landing.

One line originally in this PR has already been done separately in another PR, which has already landed on `master`, so the line does not appear in the rebased version's diff. https://github.com/obsproject/obs-studio/pull/11209

</details>

2024-11-04 20:30 UTC, Warchamp7 approved these changes
Fine with this on a conceptual level. The rebased PR above will need to be looked at

2024-11-14 00:20 UTC, norihiro commented
I manually resolved the conflict with the laster master on local host and tested.
Because of changing `peakPosition` to `peak` in the conditions, the meter gets flashing when the audio level is very close to the clipping level.

https://github.com/user-attachments/assets/b91d3572-cc30-4763-ac8f-a902899eedc4

Screen recording above is tested with Asynchronous Audio Source plugin (an 100-Hz 0-dB sine wave) + Gain Filter (-0.4 dB).

2024-11-15 14:08 UTC, cg2121 commented
@norihiro could you check if the latest code in this PR fixes the issue you were having?

2024-11-16 02:28 UTC, norihiro commented
The behavior on the horizontal meter looks good. Though, the vertical meter should be updated as well.

2024-11-23 20:55 UTC, cg2121 commented
Updated to fix the vertical mixer as well.

2025-01-23 21:00 UTC, RytoEX commented
This needs a rebase.

2025-01-25 23:47 UTC, cg2121 commented
Updated to latest master

2025-01-27 21:46 UTC, Warchamp7 commented on frontend/widgets/VolumeMeter.cpp
> +	if (peak < minimumLevel) {
What's the reason for these other changes within the paint methods?

2025-08-08 20:18 UTC, PatTheMav requested changes
Seems fine overall, please rebase and address review comments.

2025-08-08 20:18 UTC, PatTheMav commented on frontend/widgets/VolumeMeter.cpp
> +		peak = clipLevel + 0.1f;
```suggestion
	if (clipping) {
		peak = clipLevel + 0.1f;
	}
```
I prefer (and think it's good practice) to demarcate blocks explicitly with curly braces even for single instructions (the changed code did so already).

2025-08-08 20:18 UTC, PatTheMav commented on frontend/widgets/VolumeMeter.cpp
> +		peak = clipLevel + 0.1f;
```suggestion
	if (clipping) {
		peak = clipLevel + 0.1f;
	}
```

2025-10-23 22:23 UTC, Warchamp7 approved these changes
Good with this once all feedback is addressed.

2025-11-27 17:04 UTC, Warchamp7 commented
Superseded by #12735

2025-11-27 17:04 UTC, closed without merging