CI: Minor update of build scripts and GitHub Actions workflows and actions
obsproject/obs-studio pull request #11282
Opened 2024-09-13 22:00 UTC by PatTheMav

### Description
Updates the following aspects of the current build scripts and GitHub Actions workflows and actions:

* Build scripts on Linux require Ubuntu 24.04 and x86_64 - any preliminary/experimental support for aarch64 was removed
* Qt6 is used by Ubuntu builds by defaults, associated build spec settings are thus superfluous and have been removed
* Build scripts on macOS and Linux require Zsh 5.9
* macOS builds use Xcode 15.4 by default
* Experimental support for CCache on Windows was removed
* `qt-xml-validator` now uses the `check-changes` action to check for and get a list of changed UI files
* Several complex shell script snippets have been documented in-line
* XSLT stylesheets used by `sparkle-appcast` action have been updated with doc comments to explain how they work (XSLT and XPATH are remnants of a past age of Java, SOAP, and XHTML, so not many might be familiar with these)
* `sphinx-publish-action` has been updated to use the precise commit hash of version 1.2.0
* `wrangler-action` has been updated to commit hash of version 3.7.0

### Motivation and Context
Regular maintenance of CI workflows and build scripts.

### How Has This Been Tested?
Will need some actual CI runs to test.

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-09-13 23:08 UTC, RytoEX requested changes
The changes to pinned third-party actions look fine. The changes to Zsh and Ubuntu version requirements look fine. The documentation updates are largely fine. I don't know if anyone will have opinions about the other changes, but I'll let it sit at least overnight.

2024-09-13 23:08 UTC, RytoEX commented on .github/workflows/scheduled.yaml
> +          # element in the array, thus the sha-1 hash of the commit used for
This seems like an awkward use of "thus". I would just use, "which should be" or "which will be".

2024-09-13 23:08 UTC, RytoEX commented on .github/workflows/scheduled.yaml
> +          # element in the array, thus the sha-1 hash of the commit used for
```suggestion
          # element in the array, thus the SHA-1 hash of the commit used for
```

2024-09-13 23:08 UTC, RytoEX commented on .github/workflows/scheduled.yaml
> +          # element in the array, thus the sha-1 hash of the commit used for
Same about "thus".

2024-09-13 23:08 UTC, RytoEX commented on .github/workflows/scheduled.yaml
> +          # element in the array, thus the sha-1 hash of the commit used for
```suggestion
          # element in the array, thus the SHA-1 hash of the commit used for
```

2024-09-13 23:08 UTC, RytoEX commented on .github/actions/flatpak-builder-lint/action.yaml
> +        # If no warnings and/or errors were found, only empty arrays were used for 'map' and thus
Probably doesn't need "and/or" here. Can just use "or".

2024-09-16 21:49 UTC, Vainock commented
If you are on it, could you take a look at why https://github.com/obsproject/obs-studio/blob/61d74fb4ab41370ab31a6eb185d18e946e4c8d7f/.github/workflows/scheduled.yaml#L135 causes this failure? https://github.com/obsproject/obs-studio/actions/runs/10875623224/job/30174384982

This line was changed by https://github.com/obsproject/obs-studio/pull/11253.
Rather than not triggering the upload action, it now causes this issue.

2024-09-17 13:19 UTC, PatTheMav commented
> If you are on it, could you take a look at why
> 
> https://github.com/obsproject/obs-studio/blob/61d74fb4ab41370ab31a6eb185d18e946e4c8d7f/.github/workflows/scheduled.yaml#L135
> 
> causes this failure? https://github.com/obsproject/obs-studio/actions/runs/10875623224/job/30174384982
> This line was changed by #11253. Rather than not triggering the upload action, it now causes this issue.

That's because the check never ran, so there is no `steps.check` and thus the expression probably yields `null` and it cannot be used with `fromJSON`.

In theory we could use `if: steps.checks.outputs.hasChangedFiles && fromJSON(steps.checks.outputs.hasChangedFiles)`, if the runtime short-circuits the condition:

* If the step hasn't run, then the value itself should be `null`, which is interpreted as `false` and the check short-circuits
* If the step has run, the value itself will be non-null, so it's "truthy" and the `fromJSON` check converts only the string "true" into the actual boolean `true`.

2024-09-18 20:08 UTC, RytoEX approved these changes

2024-09-18 20:08 UTC, merged