Support GPU format/colourspace conversion
obsproject/obs-studio pull request #11337
Opened 2024-10-02 16:11 UTC by dsaedtler

### Description

Extends GPU scaling to also handle colourspace or format conversions to enable shared-texture encoding with heterogenous output formats.

Note: Includes #11336

### Motivation and Context

#11336 falls back to shared memory encoders, which are less efficient, this aims to fix that by extending the conversion capabilities.

In theory this would also allow recording HDR locally and streaming SDR, among other use cases that people might have.

Will need some additional discussion related to function naming and implemenation of the new texture availability check.

### How Has This Been Tested?

Streamed to Twitch while recording 444 locally as well as streaming SDR while recording HDR locally.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-10-05 23:25 UTC, Lain-B approved these changes

2024-10-05 23:25 UTC, Lain-B commented
Haven't tested it but this seems straight forward and simple.

2024-10-22 18:48 UTC, derrod reviewed
I amended this PR based on Twitch beta feedback.

2024-10-22 18:48 UTC, derrod commented on UI/multitrack-video-output.cpp
> +	obs_encoder_set_preferred_range(video_encoder, encoder_config.video_range.value_or(VIDEO_RANGE_PARTIAL));
Suggested by @palana to make this configurable as well in case somebody wants to do HDR on their platform.

2025-01-23 22:58 UTC, RytoEX requested changes
Commits previously using the `UI: ` prefix should now use `frontend: `.

2025-01-23 22:58 UTC, RytoEX commented on libobs/obs.h
> + * If GPU scaling is enabled conversion will happen on the GPU.
```suggestion
 * If GPU scaling is enabled, conversion will happen on the GPU.
```

2025-01-23 22:58 UTC, RytoEX commented on libobs/obs-encoder.c
> +	uint32_t width, height;
```suggestion
	uint32_t width;
	uint32_t height;
```

2025-01-27 21:20 UTC, RytoEX approved these changes
Seems okay.

2025-01-29 20:01 UTC, merged