UI: Add support for TEB/Multitrack Video to macOS (arm64 only)
obsproject/obs-studio pull request #11440
Opened 2024-10-22 20:53 UTC by dsaedtler

### Description

Adds TEB support for macOS on Apple Silicon.

### Motivation and Context

Want to support all users, including macOS/Linux (Linux tbd).
The small number of SKUs makes Apple Silicon easy, and since Intel Macs are losing support it seems fine to only support ARM.

**Note:** GetClientConfiguration API changes have not yet rolled out into production.

### How Has This Been Tested?

Locally with Twitch staging environment.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-10-26 20:24 UTC, Lain-B approved these changes

2024-10-29 07:56 UTC, dsaedtler commented
Configuration API support for macOS is now rolling out into production, within the next few days this PR should be testable by anyone.

2024-10-30 18:43 UTC, dsaedtler commented
The server-side changes have now rolled out, so this PR can be tested by anybody who wishes to do so!

2025-01-23 21:08 UTC, RytoEX requested changes
We should probably add a license header to `frontend/utility/system-info-macos.mm`. That need not be done here, but it would be fine to include here.

Prefix should be `frontend: `.

@PatTheMav I'd appreciate a quick glance to make sure the includes/imports are as preferred.

2025-01-23 21:08 UTC, RytoEX commented on frontend/utility/system-info-macos.mm
> +// Apple Silicon Macs have a single SoC that contains both GPU and CPU, the same information is valid for bith.
```suggestion
// Apple Silicon Macs have a single SoC that contains both GPU and CPU, the same information is valid for both.
```

2025-01-23 21:08 UTC, RytoEX commented on frontend/utility/system-info-macos.mm
> +    // Getting the frequency is not supported on Apple Silicon
```suggestion
    // Getting the frequency is not supported on Apple Silicon.
```

2025-01-24 14:53 UTC, PatTheMav commented on frontend/utility/system-info-macos.mm
> +#include <util/platform.h>
You can just use `#import` everywhere, there is no technical reason not to for ObjC except for possible cosmetic reasons.

Also correct order per the new rules (case-sensitive sort if there is no technical reason for a different order) should be:

```
#import <Foundation/Foundation.h>
#import <Foundation/NSProcessInfo.h>
#import <sys/sysctl.h>
#import <sys/types.h>
```

2025-01-24 15:08 UTC, dsaedtler commented on frontend/utility/system-info-macos.mm
> +#include <util/platform.h>
> You can just use #import everywhere, there is no technical reason not to for ObjC except for possible cosmetic reasons.

Yeah I just kept using include for C and import for ObjC, but I can change it for both.

> Also correct order per the new rules (case-sensitive sort if there is no technical reason for a different order) should be:

Are thewe "rules" documented anywhere?

2025-01-25 15:47 UTC, PatTheMav commented on frontend/utility/system-info-macos.mm
> +#include <util/platform.h>
Only by example, all new frontend files' includes have been arranged that way (and if they aren't it'd be an error).

The general order:

1. Header associated with source file
2. Other header files from the same project
3. Header files from non-standard library
4. Header files from standard library

Is more or less an established good-practice anyway. Sorting case-sensitive has the additional benefit of putting C++ classes (or in this case ObjC frameworks) as high-level language objects before low-level language objects almost automatically.

Thus the order of includes on a micro-level align neatly with the order of includes on a macro-level:

1. Headers associated with larger frameworks or classes, mostly OO
2. Headers associated with bare code and type definitions, mostly non-OO

So the further down in the includes, the more "low-level" the include is.

2025-01-30 15:17 UTC, PatTheMav commented on frontend/utility/system-info-macos.mm
> +static std::optional<std::string> getCpuName()
Not a blocker, but iirc it is more idiomatic in C++ to use anonymous namespaces instead of static function/variable declarations (it was only un-deprecated because of pesky C-compatibility but for pure C++ it is considered problematic as `static` has context-specific meanings).

2025-01-30 15:20 UTC, PatTheMav commented on frontend/utility/system-info-macos.mm
> +#ifdef __aarch64__
I'd find it more coherent to add the "full" variant of the function into the preprocessor conditional block above and provide a slim version in the `#else` branch that uses just `void system_info(GoLiveApi::Capabilities &)` (and thus the unused parameter dance can be avoided) and maybe even defined as a `constexpr`.

(Having to compile a source file that conditionally might only provide a no-op is smelly in and of itself, but there's currently no obviously better way in OBS to do arch/platform specific code).

2025-02-01 13:37 UTC, PatTheMav approved these changes

2025-02-11 20:43 UTC, merged