obs-transitions: Fix stinger showing count for update during transition
obsproject/obs-studio pull request #11512
Opened 2024-11-12 10:15 UTC by exeldro

### Description
Fix stinger showing count for update during transition

### Motivation and Context
When a transition is updated while a transition is running the `obs_source_remove_active_child` was called on an other source than `obs_source_add_active_child`
the `show_refs` counter gets to -1, because `obs_source_deactivate` does only check if it is above 0 for the source it is called on, not for the tree items in `hide_tree`

### How Has This Been Tested?
On windows 11 in combination with move transition having matched items doing a stinger transition

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-11-16 20:04 UTC, Lain-B commented
I think this looks right. The whole active child thing is annoying and really unsafe. Good catch. Probably good to do some testing though.

2025-08-20 03:34 UTC, RytoEX requested changes

2025-08-20 03:34 UTC, RytoEX commented on plugins/obs-transitions/transition-stinger.c
> +		obs_source_remove_active_child(s->source, s->media_source);
Prefer an empty line after an unenclosed `if`, or else enclose the if with curly braces.

2025-08-20 03:34 UTC, RytoEX commented on plugins/obs-transitions/transition-stinger.c
> +		obs_source_add_active_child(s->source, s->media_source);
Prefer an empty line after an unenclosed `if`, or else enclose the if with curly braces.

2025-08-20 03:34 UTC, RytoEX commented on plugins/obs-transitions/transition-stinger.c
> +			obs_source_remove_active_child(s->source, s->matte_source);
Prefer an empty line after an unenclosed `if`, or else enclose the if with curly braces.

2025-08-20 06:03 UTC, exeldro commented
Rebased and added the requested empty lines after an unenclosed if

2025-08-20 17:08 UTC, RytoEX approved these changes

2025-08-20 17:34 UTC, merged