obs-ffmpeg: Add AMD AV1 B-frame support
obsproject/obs-studio pull request #11521
Opened 2024-11-13 19:43 UTC by rhutsAMD

### Description

- Adds AMD AV1 B-frame support on supported GPUs
- Defaults to 2 B-frames and is enabled when supported
- Depends on AMF SDK header file updates in https://github.com/obsproject/obs-deps/pull/268

### Motivation and Context

- Enable support for upcoming AV1 B-frame feature

### How Has This Been Tested?

- Tested on local AMD systems with and without AV1 B-frame support

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2024-11-16 20:18 UTC, Lain-B approved these changes
Looks good, rebase after feature freeze and after the deps update is merged.

2024-12-12 20:24 UTC, rhutsAMD commented
Rebased to pull in latest changes from base branch

2025-02-26 22:20 UTC, RytoEX commented
> Rebased to pull in the AMF dependency upgrade

The dependency update was only just merged on the obs-deps repo. There is no obs-deps release containing the update itself.

2025-03-11 20:32 UTC, RytoEX commented
Please rebase this now that the updated dependencies have landed.

2025-03-11 21:43 UTC, RytoEX requested changes
Nit.

2025-03-11 21:43 UTC, RytoEX commented on plugins/obs-ffmpeg/texture-amf.cpp
> +		     bf);
This line can be unwrapped now that the column limit is 120 characters.

2025-03-12 15:08 UTC, rhutsAMD commented on plugins/obs-ffmpeg/texture-amf.cpp
> +		     bf);
unwrapped line in commit [24fe571](https://github.com/obsproject/obs-studio/pull/11521/commits/24fe571a110706f71b38ac95783a6f2f211e6d20)

2025-03-12 20:29 UTC, RytoEX approved these changes

2025-03-13 20:53 UTC, merged