Set the codec level for AMF encoders
obsproject/obs-studio pull request #11548
Opened 2024-11-21 17:50 UTC by lexano-ivs

### Description
The default "level" setting was being used for each codec (AVC, HEVC, AV1) supported by AMF. For example, all HEVC encoders were using level 6.2 and this caused some playback devices to reject decoding the bitstream because the device reported a maximum decode level lower than 6.2. 

This PR adds functionality to determine the best match for the codec level instead of relying on the defaults, for AMF encoders.

### Motivation and Context
The default behaviour of setting the codec level to the maximum resulted in several Android-based devices failing to decode HEVC streams in the TEB (Twitch Enhanced Broadcasting) beta program, which is currently testing HEVC compatibility. Adjusting the level appropriately instantly fixed the decode failures.

Also, most APIs (such as NVENC and VAAPI) have an "Auto" option for setting the codec level, in which case the driver or library code adjust the level. This Auto option doesn't seem to be available for AMF, hence the need to implement something at the application layer.

### How Has This Been Tested?
Several local unit tests were carried out by using a configuration override with Enhanced Broadcasting to verify the selected level is accurate. The code has been (and continues to be) tested in the TEB beta builds.

### Types of changes
- Enhancement (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-11-24 22:01 UTC, Lain-B approved these changes

2025-02-12 17:04 UTC, RytoEX commented
To check this, can I just record locally with AMF and check the codec level with FFmpeg or MediaInfo?

Is this something that can be fixed in a driver or AMF update, or is this always expected to be handled by the encoder implementation?

Should be there bugs filed at https://github.com/GPUOpen-LibrariesAndSDKs/AMF?

2025-02-12 18:24 UTC, RytoEX requested changes
Comment lines can be expanded to up to 120 columns.

2025-02-12 18:26 UTC, lexano-ivs commented
> To check this, can I just record locally with AMF and check the codec level with FFmpeg or MediaInfo?

Yes that would work. If you stream using TEB you can also check the log message when streaming starts; I added the "level" output to confirm this was working.

> 
> Is this something that can be fixed in a driver or AMF update, or is this always expected to be handled by the encoder implementation?

All AMF documentation and source code indicates the encoder implementation should set this. There is no "Auto" setting. Refer to `AMF_VIDEO_ENCODER_HEVC_PROFILE_LEVEL` at [https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/master/amf/doc/AMF_Video_Encode_HEVC_API.md](AMF HEVC docs).

> 
> Should be there bugs filed at https://github.com/GPUOpen-LibrariesAndSDKs/AMF?
Yeah probably, but it's an enhancement, not a bug. I'll take a shot at opening a report.

2025-02-12 18:41 UTC, lexano-ivs commented on plugins/obs-ffmpeg/texture-amf-opts.hpp
> +			set_hevc_opt(PROFILE_LEVEL, level * 3);
If someone is entering the options manually and uses the same syntax as AVC, it won't work properly. The HEVC level definitions are 3x the AVC level definitions. Refer to the following:

AMF AVC level definitions: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/681af0dcfc8b88d8c6634f259e2f9e60a54f5a42/amf/public/include/components/VideoEncoderVCE.h#L69

AMF HEVC level definitions: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/blob/681af0dcfc8b88d8c6634f259e2f9e60a54f5a42/amf/public/include/components/VideoEncoderHEVC.h#L60

2025-02-12 19:43 UTC, RytoEX commented on plugins/obs-ffmpeg/texture-amf-opts.hpp
> +			set_hevc_opt(PROFILE_LEVEL, level * 3);
I have mixed feelings on this. There is no way for us to know if they specified the level values as AVC or correctly as HEVC (or tried to specify AV1 levels, which this function does not seem to handle). If the user correctly specifies HEVC levels, this will make the values nonsense.

2025-02-12 20:10 UTC, lexano-ivs commented on plugins/obs-ffmpeg/texture-amf-opts.hpp
> +			set_hevc_opt(PROFILE_LEVEL, level * 3);
Yes, I agree with the general sentiment that without some form of input validation, having a free-form input options box means that anything goes. I don't have a good sense for how many users are using the advanced "AMF/FFmpeg Options" input.

2025-02-12 20:15 UTC, RytoEX commented on plugins/obs-ffmpeg/texture-amf-opts.hpp
> +			set_hevc_opt(PROFILE_LEVEL, level * 3);
Generally speaking, we treat the freeform box as "you know what you're doing, and you're responsible for the values being valid". The only thing we might check are if the option names/keys are valid.

Additionally, the code you've added also tries to correct the values after ffmpeg_opts are processed, so I'm not sure it's worth trying to change the value an additional time here.

2025-02-12 20:59 UTC, lexano-ivs commented on plugins/obs-ffmpeg/texture-amf-opts.hpp
> +			set_hevc_opt(PROFILE_LEVEL, level * 3);
OK, I'll back out this change. It's a fraction of a fraction of users who might be using the free-form box anyway, and as you mentioned they are expected to know what they are doing.

2025-02-12 21:31 UTC, RytoEX commented
You will probably have to manually rewrap comments to 120 columns because I don't think clang-format will touch them with our settings.

2025-02-12 22:11 UTC, RytoEX commented
I confirmed that the HEVC level is incorrect before these changes. Will check with the changes at a later time.

I did also confirm that the AVC level does change based on the output settings (resolution+FPS) and seems to be _mostly_ what I'd expect (I got 5.1 when I expected 5.2, but this is still different from the default 4.2), so something within AMF appears to be changing that as needed for AVC, but not for HEVC.

2025-02-12 23:01 UTC, lexano-ivs commented
> You will probably have to manually rewrap comments to 120 columns because I don't think clang-format will touch them with our settings.

Reformatted the comments to 120 columns with latest push.

2025-02-12 23:07 UTC, lexano-ivs commented
> I confirmed that the HEVC level is incorrect before these changes. Will check with the changes at a later time.
> 
> I did also confirm that the AVC level does change based on the output settings (resolution+FPS) and seems to be _mostly_ what I'd expect (I got 5.1 when I expected 5.2, but this is still different from the default 4.2), so something within AMF appears to be changing that as needed for AVC, but not for HEVC.

We tripped over this issue when testing HEVC playback in the TEB beta program, where the HEVC level was set to the maximum by default, so it's consistent with your findings re: HEVC. I don't recall at the moment what AVC was reporting back, but given that HEVC needed to be adjusted to solve mobile player compatibility issues (i.e. the mobile app player is doing the right thing and rejecting levels it can't handle), I adjusted AVC, HEVC, and AV1 "just in case".

2025-02-12 23:45 UTC, RytoEX commented
> > I confirmed that the HEVC level is incorrect before these changes. Will check with the changes at a later time.
> > I did also confirm that the AVC level does change based on the output settings (resolution+FPS) and seems to be _mostly_ what I'd expect (I got 5.1 when I expected 5.2, but this is still different from the default 4.2), so something within AMF appears to be changing that as needed for AVC, but not for HEVC.
> 
> We tripped over this issue when testing HEVC playback in the TEB beta program, where the HEVC level was set to the maximum by default, so it's consistent with your findings re: HEVC. I don't recall at the moment what AVC was reporting back, but given that HEVC needed to be adjusted to solve mobile player compatibility issues (i.e. the mobile app player is doing the right thing and rejecting levels it can't handle), I adjusted AVC, HEVC, and AV1 "just in case".

My comment was more along the lines of "there may be a bug in AMF where HEVC levels are not set" since AVC levels do seem to be automatically adjusted, despite also having a default value (4.2). I would suggest testing their sample apps, which notably do _not_ all manually set levels. Since we do not currently set the AVC level in OBS Studio, that it adjusts on its own makes me think that AMF should be able to do this for HEVC and AV1. I could be wrong, but it seems odd.

2025-02-21 16:38 UTC, rhutsAMD commented
> > > I confirmed that the HEVC level is incorrect before these changes. Will check with the changes at a later time.
> > > I did also confirm that the AVC level does change based on the output settings (resolution+FPS) and seems to be _mostly_ what I'd expect (I got 5.1 when I expected 5.2, but this is still different from the default 4.2), so something within AMF appears to be changing that as needed for AVC, but not for HEVC.
> > 
> > 
> > We tripped over this issue when testing HEVC playback in the TEB beta program, where the HEVC level was set to the maximum by default, so it's consistent with your findings re: HEVC. I don't recall at the moment what AVC was reporting back, but given that HEVC needed to be adjusted to solve mobile player compatibility issues (i.e. the mobile app player is doing the right thing and rejecting levels it can't handle), I adjusted AVC, HEVC, and AV1 "just in case".
> 
> My comment was more along the lines of "there may be a bug in AMF where HEVC levels are not set" since AVC levels do seem to be automatically adjusted, despite also having a default value (4.2). I would suggest testing their sample apps, which notably do _not_ all manually set levels. Since we do not currently set the AVC level in OBS Studio, that it adjusts on its own makes me think that AMF should be able to do this for HEVC and AV1. I could be wrong, but it seems odd.

Hi @RytoEX , to clarify, AMF does currently adjust the profile levels based on the frame size however it does so by only increasing the profile level "upwards" and the current HEVC default profile level is set to the highest one. I have lowered the HEVC default profile level however this will only be take effect in a future public driver release.

2025-04-18 21:19 UTC, RytoEX requested changes
Nit.

I was wondering if we would keep the logging of `level` in the future after we can revert this (when there's an AMF update that automatically adjusts the level to the lowest applicable level for the content) and wondering if we should split this into more than one commit to make reverting the bulk of it easier, but that is probably unnecessary. We can just remove the parts we don't need when it comes to that.

Seems fine other than the nit.

2025-04-18 21:19 UTC, RytoEX commented on plugins/obs-ffmpeg/texture-amf.cpp
> + * codec level is higher than its decode abilities, which make sense.
```suggestion
 * codec level is higher than its decode abilities, which makes sense.
```

Or just remove `, which makes sense` entirely.

2025-04-22 13:26 UTC, lexano-ivs commented
> Nit.
> 
> I was wondering if we would keep the logging of `level` in the future after we can revert this (when there's an AMF update that automatically adjusts the level to the lowest applicable level for the content) and wondering if we should split this into more than one commit to make reverting the bulk of it easier, but that is probably unnecessary. We can just remove the parts we don't need when it comes to that.
> 
> Seems fine other than the nit.

I had wondered about the same thing originally while implementing the logic. I just split it into 2 commits with the latest push. Please take a look. It would be easy to squash back to one commit if needed.

2025-04-25 17:59 UTC, RytoEX approved these changes

2025-04-25 17:59 UTC, RytoEX commented
@lexano-ivs There are merge conflicts here.

2025-04-25 20:02 UTC, lexano-ivs commented
> @lexano-ivs There are merge conflicts here.

I just rebased to master, fixed it, built/tested, and pushed. Should be fine now.

2025-04-25 20:48 UTC, merged