UI: Adjust styling for Sources list
obsproject/obs-studio pull request #11555
Opened 2024-11-22 22:55 UTC by Warchamp7

### Description
Minor adjustment to the SourceTreeItem sizeHint calculation and styling rule cleanup.

This also fixes the items in the Sources list being different sizes than the Scene list, which is a bug.

### Motivation and Context
There are a few confusing SourceTree specific style rules to account for the fact it uses a QListView with custom widgets instead of a QListWidget. This PR tidies that up a little bit and also removes some unnecessary rules targeting the SceneTree widget.

### How Has This Been Tested?

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2025-02-12 19:17 UTC, RytoEX commented
Is there a visual difference with these changes? If so, could I get before and after images?

2025-02-12 19:22 UTC, Warchamp7 commented
> Is there a visual difference with these changes? If so, could I get before and after images?

Screenshots added

2025-02-15 01:12 UTC, Lain-B approved these changes

2025-04-02 19:32 UTC, RytoEX requested changes
Super nit, but could we instead order the selectors in each rule as:
```
QListView
QListWidget
```

Or would that be problematic?

2025-04-03 00:13 UTC, Warchamp7 commented
> Super nit, but could we instead order the selectors in each rule as:
> 
> ```
> QListView
> QListWidget
> ```
> 
> Or would that be problematic?

Updated

2025-04-03 17:49 UTC, RytoEX approved these changes

2025-04-03 18:18 UTC, merged