scripting: Fix macOS Python loading
obsproject/obs-studio pull request #11590
Opened 2024-12-06 19:37 UTC by jcm93

### Description

Use the explicit version number for the directory when dynamically loading Python inside a Framework bundle on macOS.

### Motivation and Context

No versions of Python supported by OBS seem to currently be loadable on macOS. When currently installed via Homebrew as of December 6th, 2024, supported Python versions (3.10 through 3.12 tested) do not contain a "Current" symlink inside their "Versions" folder, which is what OBS looks for when loading the dynamic library within the framework bundle.

Python 3.13 *does* contains a "Current" symlink. It also seems clear that at some point, past versions of Python also had this "Current" symlink. I do not know why Python is packaged in this way where the "Current" symlink will sometimes be there and other times not. Regardless, the Versions directory does seem to always contain the <major>.<minor> directory that "Current" symlinks to, so it seems safe to just load Python using this path, since we already have the version information explicitly available.

### How Has This Been Tested?

macOS 15.1.1, Apple Silicon; Python now loads with current installs of supported Python versions via Homebrew.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-12-06 19:40 UTC, RytoEX requested changes
The correct prefix would be `obs-scripting: `.

2024-12-06 20:36 UTC, alinsavix commented
If I'm reading the homebrew recipes correctly, this seems like a pretty reasonable and reliable way to deal with this, and also should still work with the python install provided by Apple in Xcode and such. 👍

(and the Xcode-bundled python version doesn't have a "Current" link, either)

2024-12-14 19:16 UTC, Lain-B approved these changes

2024-12-16 15:07 UTC, PatTheMav approved these changes
Should work fine. Has this been tested with existing setups? I'd guess because you usually only provided the Frameworks directory that contained the Python framework (and we produced a path from that at runtime) it should lead to no issues?

2024-12-16 19:21 UTC, jcm93 commented
> Should work fine. Has this been tested with existing setups? I'd guess because you usually only provided the Frameworks directory that contained the Python framework (and we produced a path from that at runtime) it should lead to no issues?

Correct; the only way OBS will load Python on macOS is by looking inside a Python.framework bundle in the directory the user provides in the Python configuration window. So there shouldn't be any way for this to break anything (that is, unless Python or Homebrew decide to violate the Framework bundle specification in a new and fun way in the future).

2024-12-16 20:45 UTC, jcm93 commented
As noted out-of-band, Python's [official installer](https://www.python.org/downloads/macos/) will still contain the `Current` symlink for supported versions. So for anyone happening on this issue thread looking for a fix, the workaround until this PR is merged is to use Python's installer from its website, and then point OBS toward the `/Library/Frameworks` folder when locating the Python install.

2025-01-23 21:53 UTC, RytoEX approved these changes
Seems fine at a glance.

2025-01-28 20:07 UTC, merged