libobs: Fix race when disconnecting raw video callbacks
obsproject/obs-studio pull request #11605
Opened 2024-12-08 20:22 UTC by derrod

### Description

Ensures `raw_active` counter is only incremented/decremented if a callback was actually added/removed.

### Motivation and Context

Fixes #11329

There is a race condition here where the encoder stopping due to failure will call `remove_connection()` from `full_stop()` and the output itself stopping will also call it from `end_data_capture_thread()`. This can  result in the `raw_active` counter being decremented twice to `-1`, so that the next time an output is started the counter will be incremented to `0` instead of `1`, which is treated as inactive.

### How Has This Been Tested?

Locally.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-12-10 00:28 UTC, DeeDeeG commented
The fix works for me, thanks!

(To be sure, I compiled OBS _without_ this change (revision https://github.com/obsproject/obs-studio/commit/fbf2ea1a82a72100b8d4c30eb113679989332383) and could reproduce the original issue https://github.com/obsproject/obs-studio/issues/11329. Recompiled _with_ this PR and the issue is gone, no hangs. 👍)

(With this PR/fix, OBS can start new recordings successfully, and can exit cleanly, even after an encoder times out while using Hybrid MP4.)

2024-12-14 19:24 UTC, Lain-B approved these changes

2025-01-23 22:59 UTC, RytoEX requested changes

2025-01-23 22:59 UTC, RytoEX commented on docs/sphinx/reference-libobs-media-io.rst
> +   :return:         *true* if callback was removed, *false* otherwise (e.g. already removed)
```suggestion
   :return:         *true* if callback was removed, *false* otherwise (e.g., already removed)
```

2025-01-27 21:22 UTC, RytoEX approved these changes

2025-01-28 22:36 UTC, merged