UI: Add various preview improvements
obsproject/obs-studio pull request #2212
Opened 2019-11-30 01:41 UTC by VodBox

### Description

Adds the following changes to the preview:
- Double clicking a source will open it's properties.
- Double clicking a group will open up that group for editing in the preview.
- Optional rotation handle can be enabled in settings.

### Motivation and Context

Double clicking a source to open properties saves needing to find the corresponding source in the sources list, and can be quicker to find the source you mean to change properties for. Editing groups are currently very finicky at best, since there's no way to click into them in the preview. Rotation handles, while unnecessary for most setups can be useful when needing to change rotations often, and not wanting to use the transform dialog.

### How Has This Been Tested?

This has been tested running Windows 10 64-bit, with many scene collections, old and new.

### Types of changes

 - New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

2019-12-02 14:46 UTC, hg-pyun commented on UI/forms/OBSBasicSettings.ui
> +				   <item row="3" column="1">
This line need to re-indentation.

2019-12-02 19:04 UTC, VodBox commented on UI/forms/OBSBasicSettings.ui
> +				   <item row="3" column="1">
This has been fixed in the latest push.

2019-12-10 19:55 UTC, RytoEX commented
If I'm not mistaken, this might address [Mantis 541](https://obsproject.com/mantis/view.php?id=541).

2019-12-10 21:39 UTC, jp9000 commented
When editing a group, you're unable to switch scenes.  Also I'm not sure how I feel about group editing in general.  Have people asked for this sort of thing?

2020-01-04 04:30 UTC, VodBox commented
@jp9000 I'll go ahead and fix the switch scenes things now.

As far as group editing, there's currently no easy way to select items in a group to edit them, since you need to select the item in the sources list. Clicking out in the preview, or clicking the source without dragging will deselect it and you need to go back to the sources list. It's really not a fun time to make changes.

In terms of a dedicated display for editing groups, it's partly my experience with After Effects in terms of what I find natural (double clicking on things to jump into precomps or edit that thing individually), but also just the idea that groups are still scenes and would be nice to edit as such, combined with making things still editable even if an alt crop has been applied.

2020-01-04 23:34 UTC, VodBox commented
Scene issues are now fixed.

2020-02-08 19:49 UTC, Warchamp7 commented
I don't know if I agree with double clicking the preview performing an action. Currently you can click multiple times to cycle through sources

I think a better solution is to scroll the Sources list to a selected sceneitem when it's clicked in the preview

2020-02-18 08:35 UTC, VodBox commented
@Warchamp7 

> I don't know if I agree with double clicking the preview performing an action. Currently you can click multiple times to cycle through sources

Double clicking the visual element of something to pull up closer details or to "open it up" is a very common design pattern used in a lot of programs. Most programs don't have cycling, and even in OBS it can still be annoying to get the source you actually want selected in a lot of cases through that method. I'd rather this as a more natural interaction take priority over something non-standard that gets avoided by people selecting with the sources list anyway.

> I think a better solution is to scroll the Sources list to a selected sceneitem when it's clicked in the preview

This really only works as a solution if you have enough sources for it to scroll. Clicking on a source will already make the source in the list active. Even then, it doesn't actually solve the problem I'm trying to solve, which is to have a natural way to open up a source without having to search through a list or jump between parts of the interface.

2020-07-18 01:36 UTC, WizardCM commented
Alright, I tested this a while ago and found a few issues. I've just pulled the latest to verify the quirks I ran into.

1. Group edit mode can get confusing if the group is canvas size, or if (like in my case) the group contains white text sources. It makes it super unclear that you're in group edit mode unless you know about it. In general it just feels unintuitive
2. I ran into one issue with Group edit mode that I cannot reproduce, where I could see both the actual group and the "active group" but both scaled at different sizes.
3. The rotation handle currently cannot be grabbed for some reason.

I am a huge fan of both double-click to open properties, and the rotate handle (though I think it should be on by default).

2021-03-06 16:32 UTC, PatTheMav commented
Just tested this rebased on current master and looks fine so far, except for

> Double clicking a group will open up that group for editing in the preview

which I haven't fully understood what it's supposed to do or how it works.

2021-09-02 03:24 UTC, Warchamp7 commented
Have not had the chance to test this yet but some upfront concerns:

- Double clicking a source will open it's properties.

I think this PR is originally from before some other preview improvements. How does double clicking a source interact with clicking multiple times in the preview cycling through all sources the cursor is over


- Double clicking a group will open up that group for editing in the preview.

The fade is a good touch but I don't think it does a good enough job of conveying the functionality. I think this should be broken out into a different PR with some more love to the UX for that kind of usage

- Optional rotation handle can be enabled in settings.
- Handles and lines will now scale depending on the DPI OBS is running at.

These sound good to me

2022-07-20 14:50 UTC, RytoEX requested changes
Noticed some places that can be simplified due to dropping support for older Qt versions.

Also, you may need to check for Qt5/6 compatibility in a few places. See:
* #6770

2022-07-20 14:50 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +#endif
This can be simplified, per:
* #4394

2022-07-20 14:50 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +#endif
This can be simplified, per:
* #4394

2022-07-20 14:50 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +#endif
This can be simplified, per:
* #4394

2022-07-20 14:50 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +#endif
This can be simplified, per:
* #4394

2022-07-20 14:50 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +#endif
This can be simplified, per:
* #4394

2022-07-27 20:00 UTC, cg2121 commented
Since we have undo / redo now, I don't think we need the option in the settings for the rotation handle anymore.

2022-07-27 20:05 UTC, RytoEX commented
> Since we have undo / redo now, I don't think we need the option in the settings for the rotation handle anymore.

I don't see the connection between undo/redo and whether or not this feature has a setting to enable/disable it.

2022-07-27 20:27 UTC, cg2121 commented
@jp9000 wanted the rotation handle to be an option, turned off by default, because people might rotate the item accidently and not know how to get it back. With the undo / redo this is no longer a concern.

2022-07-27 20:31 UTC, RytoEX commented
> @jp9000 wanted the rotation handle to be an option, turned off by default, because people might rotate the item accidently and not know how to get it back. With the undo / redo this is no longer a concern.

Ah, I see. That said, I'm not sure if I'm going to block on this.

2022-07-28 14:40 UTC, merged

2022-07-29 07:09 UTC, SuslikV commented
For the _Preview Scaling_ = _Scale to Window_, the rotation handle rendered outside the 10px border zone, thus it is cropped/almost invisible/inaccessible for full screen sources, or for any sources at the top.

Mentioned "border zone" size is hardcoded to the 10px in OBS:
https://github.com/obsproject/obs-studio/blob/8ef134be7955d3436282c85ff7e806bab2e6f28b/UI/window-basic-main.hpp#L74