UI: Update Edit Transform dialog on scene switch
obsproject/obs-studio pull request #4312
Opened 2021-03-09 07:46 UTC by offthegrid-mike

### Description

fixed transform panel windows can't update source's properties over different scene.

### Motivation and Context

Issue from #4291 
The reason behind is the notification of select signal from `OBSBasicTransform` is observing `OBSSource`. Thus changing the scene can't observe the notification to invoke the transform window update.

### How Has This Been Tested?

open `Edit Transform` window by selecting one of the sources (e.g.: Scene A, Source 1), select another source from the other scene(e.g.: Scene B, Source 2) without closing the transform window, the properties should be changed accordingly.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-03-11 12:44 UTC, WizardCM commented
Emitting a signal on the dialog seems unnecessary. Does the transform dialog even need to know what scene the source is in?

2021-03-12 04:58 UTC, offthegrid-mike commented
> Emitting a signal on the dialog seems unnecessary. Does the transform dialog even need to know what scene the source is in? If it does need to know the scene, maybe listening for the scene change event within the dialog would be a better solution.

Thanks! I've updated the branch, feel free to take a look on it!

2021-03-12 08:34 UTC, WizardCM requested changes
The rest seems fine to me, but I'd also change the commit message to something like:

> UI: Update Edit Transform dialog on scene switch

2021-03-12 08:34 UTC, WizardCM commented on UI/window-basic-main.cpp
> +		obs_scene_t *scene = GetOBSRef<OBSScene>(current);
This change is no longer required.

```suggestion
		obs_scene_t *scene;

		scene = GetOBSRef<OBSScene>(current);
```

2021-06-14 11:53 UTC, WizardCM commented
Heads up: there are merge conflicts.

2021-11-10 14:09 UTC, closed without merging

2021-11-10 14:10 UTC, jp9000 commented
Manually merged