UIL fixed can't paste removed item's filter issue
obsproject/obs-studio pull request #4328
Opened 2021-03-11 08:41 UTC by offthegrid-mike

### Description

Previously: Paste filters is clickable after removing source after copy, but doesn't do anything.
Now changed to disable paste filter action if the item is removed

### Motivation and Context

Refer to issue #4075.
It is due to missing out checking the source item is still existed when setting up the context menu

### How Has This Been Tested?

1. Add any source.
2. Add any filters to that source.
3. Add another source (that can have these filters, e.g. both sources can have video filters)
4. Copy filters from the first source.
5. Remove the first source.
6. Right click -> Paste Filters on the second source.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-03-11 08:48 UTC, RytoEX commented
As I mentioned in your other recent PR, please use an imperative verb in sentence case for the first word after the commit prefix ("Fix" instead of "fixed").

2021-03-11 08:55 UTC, RytoEX requested changes
Don't change whitespace in unrelated areas of code.

2021-03-11 08:55 UTC, RytoEX commented on UI/window-basic-main.cpp
> -
Don't make unnecessary whitespace changes.

2022-06-26 06:15 UTC, tt2468 commented on UI/window-basic-main.cpp
> +			obs_source_release(filterSource);
We recently added the OBSSourceAutoRelease wrapper, which avoid the need for the extra `obs_source_release()` call. As such, the wrapper should be used here.

2022-11-02 20:09 UTC, RytoEX commented
Closing this as the associated Issue that it was meant to fix has been fixed by refactoring the copy/paste systems for sources and filters to use weak sources instead of the strings of source/filter names.

2022-11-02 20:09 UTC, closed without merging