UI: reimplement closeEvent in missing files
obsproject/obs-studio pull request #4363
Opened 2021-03-17 23:30 UTC by cpyarger

### Description
This fixes #4359 by reimplementing close event and making all close responses "accept"
### Motivation and Context

Crashes on windows 10 when trying to click the close button. 
### How Has This Been Tested?

Tested on windows 10 works fine
### Types of changes

- Bug fix (non-breaking change which fixes an issue) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-03-17 23:34 UTC, RytoEX requested changes

2021-03-17 23:34 UTC, RytoEX commented on UI/window-missing-files.hpp
> +#include <QCloseEvent>
If there was a blank line here before, it should be retained.  This include should be grouped with the other Qt includes.

2021-03-18 01:03 UTC, notr1ch commented
I'm not too familiar with Qt but I would expect the `QDialog` class to handle a close event without crashing the whole app. Why is reimplementing the close event necessary here but not for other dialogs?

2021-03-18 01:22 UTC, cpyarger commented
I have no clue honestly. I just knew it had to be something involving this function due to the successful actions of each other method of closing the dialog. You are right, QT should not be doing this. and I could see no reason why It should be

2021-03-20 21:40 UTC, jp9000 commented
I don't like merging fixes where we don't know why it fixes something.

2021-03-20 21:41 UTC, jp9000 commented
In the first place, I'm having trouble reproducing #4359 -- it's frustrating that we don't have reproduction steps either. Can you provide the scene collection file somehow so we can try to reproduce it?

2021-04-19 00:19 UTC, closed without merging