obs-ffmpeg: Hangs when global_stream_key is not configured
obsproject/obs-studio pull request #4381
Opened 2021-03-21 07:56 UTC by floele

When not configuring global_stream_key and starting a recording, obs-ffmpeg-mux.exe will hang. Applied same check as seen in init_params() to prevent this.

2021-03-21 07:59 UTC, WizardCM commented
Please fill in the PR template.

2021-03-21 18:36 UTC, RytoEX commented
It should be noted that the described behavior and code path are _only_ encountered if you enable the `DEBUG_FFMPEG_MUX` CMake flag, which is disabled by default.  I was trying to figure out why I'd never seen this behavior before or why we hadn't received complaints about it.

2021-03-21 18:43 UTC, RytoEX requested changes
Use imperative mood for the commit subject message.  For example:

```
obs-ffmpeg: Fix hang when recording without global_stream_key
```

Then elaborate in the commit message body about DEBUG_FFMPEG_MUX being enabled, and reusing the check for global_stream_key from init_params.  For example:

```
obs-ffmpeg: Fix hang when recording without global_stream_key

If DEBUG_FFMPEG_MUX is enabled, when starting a recording without 
configuring global_stream_key, obs-ffmpeg-mux.exe will hang. Apply the 
same check as seen in init_params() to prevent this.

2021-03-27 10:51 UTC, floele commented
I did in fact not realize that DEBUG_FFMPEG_MUX was involved because that was pretty much the first thing I enabled so I did not notice it was ever not broken. Thanks for pointing that out.
Commit message should be fine now.

2021-03-30 11:55 UTC, merged