CI: use a stable version of the flatpak action
obsproject/obs-studio pull request #4572
Opened 2021-04-22 00:49 UTC by bilelmoussaoui

### Description

Switch from using the `master` branch of the flatpak-github-actions to the latest tagged release `v3`

### Motivation and Context

To avoid any future breakages as all futures needed such as caching are now part of the latest stable release

### How Has This Been Tested?

It needs the `Seeking Testers` label. Although, nothing changed between the `master` & `v3`. So no breakage is expected.

### Types of changes

Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-04-28 13:20 UTC, GeorgesStavracas approved these changes
LGTM

2021-04-28 20:15 UTC, RytoEX requested changes
Sorry, one minor nitpick:  capitalize the first word of the commit subject after the prefix.  In this case, change `use` to `Use`.

2021-04-28 23:52 UTC, bilelmoussaoui commented
Should be good now

2021-04-29 00:39 UTC, RytoEX approved these changes

2021-04-29 00:40 UTC, merged