UI: Display grayscale volume meter if muted
obsproject/obs-studio pull request #5181
Opened 2021-08-24 06:27 UTC by cg2121

### Description
Currently, the volume meters don't show volume levels when
muted. This shows the levels and makes it grayscale when
the source is muted.

Muted:
![Screenshot from 2021-08-24 01-10-37](https://user-images.githubusercontent.com/19962531/130565942-ffc77fd5-ab41-48eb-ac4e-46c929573802.png)

Not muted:
![Screenshot from 2021-08-24 01-11-14](https://user-images.githubusercontent.com/19962531/130565965-379178fb-f22b-41ba-99f0-10c226c9ffde.png)

### Motivation and Context
Give indication to users of volume levels, even if muted.

### How Has This Been Tested?
Muted/unmuted audio sources, to make sure volume meters updated properly.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-08-25 04:04 UTC, Warchamp7 commented
I think this should be the same grey color for the entire bar. The Yellows have a lot more luminance than green/red and it looks jarring with the bright grey chunk in the middle of the bar.

Not sure if you pulled this idea off my request list I posted on Discord but nevertheless this is great. Thanks!

2021-09-05 19:08 UTC, Warchamp7 requested changes
See previous comment regarding color adjustments

2021-12-13 12:31 UTC, cg2121 commented
Updated to make the grayscale meters customizable.

2021-12-15 00:25 UTC, WizardCM commented
Confirmed this works well.

![image](https://user-images.githubusercontent.com/941350/146100372-6c2d54b1-04e8-4f50-9f80-0a8ead901373.png)

2021-12-23 14:35 UTC, merged