win-wasapi: Reset audio monitor if defaut device is changed
obsproject/obs-studio pull request #5398
Opened 2021-10-11 03:33 UTC by walker-WSH

### Description

fix #4463 on Windows platform

### Motivation and Context

while using "default" for audio monitor, when the default output device is changed, audio monitor should be reset.

### How Has This Been Tested?

as steps in #4463

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-10-11 03:39 UTC, walker-WSH commented
Dodes window-basic-main.cpp include clang format error ?
There is no error on my PC, version of my clangformat is 12.0.0

2022-01-21 06:23 UTC, walker-WSH commented
@jpark37   
Hmm, could you help review this PR ?

2022-01-21 06:47 UTC, jpark37 commented
I don't have time to look at this, but you should at least squash your commits cleanly.

2022-01-21 07:05 UTC, walker-WSH commented
> I don't have time to look at this, but you should at least squash your commits cleanly.


There are too many conflicts while rebasing, since this branch is based on old master. 
if multiple commits must be merge as one, I have to create another branch.

2022-01-21 07:11 UTC, jpark37 commented
There are strategies to resolve conflicts. That's not a reason to leave a merge commit in your PR.

2022-01-21 07:15 UTC, walker-WSH commented
I  will try to do it

2022-01-23 23:00 UTC, RytoEX requested changes
See review comments.  Of particular note, I really don't think this plugin should be requiring Qt components to build.

2022-01-24 00:26 UTC, walker-WSH commented on plugins/win-wasapi/detect-default-device.cpp
> +					  Qt::QueuedConnection);
In callback of WASAPI, where is outside of UI thread, I don't like to call any interface of OBS which will request lock.
So here I post the event to UI thread for calling interface.

2022-01-24 00:27 UTC, walker-WSH commented on libobs/obs.c
> +void obs_default_output_audio_device_changed()
done

2022-01-24 00:29 UTC, walker-WSH commented on libobs/obs.c
> +	if (0 == strcmp(obs->audio.monitoring_device_id, "default")) {
I write const object at left side which help avoid treating "=" as "==". To keep code style as OBS, I will change it as your suggestion.

2022-01-24 00:30 UTC, walker-WSH commented on libobs/obs.c
> +		     "Default output audio device is changed, reset monitor if need.");
done

2022-01-24 00:31 UTC, walker-WSH commented on plugins/win-wasapi/audio-notify-client.cpp
> +	return temp;
done

2022-01-24 00:31 UTC, walker-WSH commented on libobs/obs.h
> +EXPORT void obs_default_output_audio_device_changed();
done

2022-01-24 00:32 UTC, walker-WSH commented on plugins/win-wasapi/audio-notify-client.cpp
> +	if (0 == temp)
done

2022-01-24 00:33 UTC, walker-WSH commented on plugins/win-wasapi/detect-default-device.cpp
> +	     "WASAPI: Default monitor device is changed. Try to reset monitor modules.");
this log has been removed

2022-01-24 03:05 UTC, RytoEX commented on plugins/win-wasapi/detect-default-device.cpp
> +					  Qt::QueuedConnection);
@notr1ch Can probably better discuss the preferred method of handling this.

2022-06-26 06:36 UTC, tt2468 commented on plugins/win-wasapi/audio-notify-client.cpp
> +STDMETHODIMP WASAPINotify::OnDeviceAdded(LPCWSTR)
If this is inherits a callback class, is having these empty callbacks necessary versus just not defining them?

2022-11-24 00:58 UTC, walker-WSH commented
close it since of https://github.com/obsproject/obs-studio/pull/6657

2022-11-24 00:58 UTC, closed without merging