win-dshow: Add option to save video device configuration properties
obsproject/obs-studio pull request #5480
Opened 2021-11-02 20:46 UTC by exeldro

### Description
Add option to save webcam settings/ video device configuration properties
![image](https://user-images.githubusercontent.com/5457024/139949040-e1953c78-4cef-4153-af4c-a140b44cef23.png)

### Motivation and Context
Some webcams don't save the settings and this allows you to have different webcam settings per scene collection

### How Has This Been Tested?
On windows 64 bit

### Types of changes
- New feature (non-breaking change which adds functionality) -->

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2021-11-03 11:09 UTC, cg2121 commented
Just my opinion, others can chime in: I think the settings should save automatically, so there shouldn't be a need for the checkbox.

2021-11-03 11:19 UTC, WizardCM commented
I know others have tried to implement something similar and ended up either reverting or disabling the capability because it was not saving correctly, or potentially corrupting data. I am OK with providing a checkbox to begin with to allow users to disable the functionality if it's not working as expected for them.

2021-11-03 21:35 UTC, Fenrirthviti commented
I agree that this should just be automatic without a checkbox. Plenty of applications accomplish this without corruption or failure saving, I'd prefer we just tested this thoroughly and made it automatic.

2021-11-04 07:23 UTC, exeldro commented
I think the seeking testers label needs to be added to this PR to allow users to test the change.

2021-11-23 08:15 UTC, exeldro commented
Tested and confirmed working with C910, C920, C922, C295
Reported not working C270

2021-11-23 09:46 UTC, WizardCM commented
@exeldro I own a C270. Anything specific you'd like me to try?

2021-11-23 09:52 UTC, exeldro commented
@WizardCM set some custom camera settings, check if there are settings stored when OBS is closed in the scene collection json, in arrays called `VideoProcAmp` and `CameraControl`. Restart computer or have an other way to change the camera settings. Start OBS to check if the camera settings are restored.

2021-11-25 17:46 UTC, exeldro commented
Removed the extra setting, now it is always enabled

2021-12-05 09:56 UTC, exeldro commented
All changed to not make it a setting, but always save and restore

2022-01-02 00:49 UTC, WizardCM commented
Heads up, this PR has a merge conflict with a submodule.

2022-02-15 02:29 UTC, mat1jaczyyy commented
is it possible for this feature to additionally re-activate the video once? so the full process for restoring would be:

1. first load/activation
2. restore settings
3. deactivate
4. activate again
5. restore settings again

This is due to some webcams (such as C920) having really low FPS on manual exposure -6 or below on the first load, but after the device is deactivated and reactivated once, the FPS works perfectly fine. As far as I understand the current system, this sort of fix wouldn't be able to be fully restored.

2022-02-26 04:54 UTC, Tod181 commented
Is there an updated version for OBS 27.2.1? When I updated OBS it removed the setting from my menu.

2022-03-21 10:22 UTC, johnebgood commented
> The latest test version including OBS 27.2.1 changes can be downloaded here: https://github.com/obsproject/obs-studio/actions/runs/1887279360

I think OBS 27.2.1 had an issue that was crashing my computer that was fixed in 27.2.2, would it be possible to get a build with 27.2.3? I can test with OBSBOT Tiny's, Feiyu Pocket 2S and some other oddball webcams.

2022-03-21 17:34 UTC, exeldro commented
The latest test version including OBS 27.2.3 changes can be downloaded here:
https://github.com/obsproject/obs-studio/actions/runs/2017636125

2022-05-29 06:29 UTC, exeldro commented
The latest test version can be downloaded here:
https://github.com/obsproject/obs-studio/actions/runs/2403350419

2022-06-14 09:12 UTC, gxalpha requested changes
There are quite a few cases here where to me it looks like OBSDataAutoRelease or OBSDataArrayAutoRelease could be used instead of manually releasing, which could improve code readability. Could you check where those can be used (or is there a specific reason why they aren’t)?

(Since this PR is open for quite a bit I think the AutoSelect classes just didn’t exist on the main branch when it was created)

2022-06-15 19:30 UTC, merged

2022-11-20 22:05 UTC, josiasmat commented
Hello.
Is there any chance this feature will be reenabled anytime soon? Because I'm sticking to version 28.0.0 and skipping all updates as I cannot live without this anymore. I use 3 cameras, and before 28.0.0 had to configure all of them every time.
Would it not be better if added as an experimental feature, available through a checkbox?
Many thanks.

2023-06-02 04:29 UTC, zacgoodwin commented
1 year on and crickets still? Setting settings on every reboot like it's the stone ages.