Add option to hide OBS windows from display capture
obsproject/obs-studio pull request #5698
Opened 2021-12-26 22:49 UTC by notr1ch

### Description
This PR adds a new setting to hide the OBS application window and sub-windows / dialog boxes from screen capture applications (including OBS itself). This unfortunately does not cover 100% of the different types of windows that could appear, for example, context menus and tooltips, as the underlying API does not work well on these types of windows, causing a black box or black lines to appear on the captured output.

Only Windows 10 2004 and later is supported as that's when the `WDA_EXCLUDEFROMCAPTURE` parameter was added to [SetDisplayAffinity](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity). Cross-platform support is simple to add if the underlying APIs exist to be able to hide specific windows from capture APIs.

Projectors are special-cased and this option is not applied to them, as they are often intended to be visible and capturable by other applications.

### Motivation and Context
Users with a single monitor often have trouble with video feedback when using display capture. This option allows single monitor users to be able to manipulate the OBS UI without having OBS itself appear in the preview or output.

Demo:

https://user-images.githubusercontent.com/876345/147421740-e8693ebe-63e2-406e-a222-884137c41f3e.mp4

### How Has This Been Tested?
Lots of testing on Windows 10 21H1. Tested behavior of the main window, dialog boxes, Qt message boxes, various sub-window, docks, projectors and browser docks. Further testing would be appreciated, PR is marked as draft for this reason.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-01-16 00:09 UTC, RytoEX requested changes
Minor nitpicks.

2022-01-16 00:09 UTC, RytoEX commented on UI/obs-app.cpp
> +// caring where they are coming from (eg plugins).
"eg" should be "e.g.,".

2022-01-16 00:09 UTC, RytoEX commented on UI/window-basic-settings.cpp
> +	HookWidget(ui->hideOBSFromCapture   ,CHECK_CHANGED,  GENERAL_CHANGED);
Fix comma placement.

2022-01-16 02:22 UTC, notr1ch commented on UI/data/locale/en-US.ini
> +Basic.Settings.General.HideOBSWindowsFromCapture="Hide OBS windows from display capture"
This affects all capture programs, not just OBS, so I intended it to be more generic.

2022-01-16 04:06 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +Basic.Settings.General.HideOBSWindowsFromCapture="Hide OBS windows from display capture"
Ah, I see.  Then this is fine as-is.

2022-01-16 11:12 UTC, flaeri commented
I really like it, and it seems to work really well for me, regardless of monitors and capture method.

Like you've noted, certain context menu / right click will show in preview and output, but no big deal imo. Big QOL add, and I would personally prefer it to be enabled by default.

I poked at it a fair amount, but couldn't really get it to misbehave in any way. Works well on my machine.
i7-8700, GTX 1070, Win 10 20H2

2022-01-16 11:30 UTC, WizardCM commented
Verified this works for most of the main windows. Also verified it doesn't work for context menus & dropdown menus, which is expected.

Fullscreen projectors work fine, as do VST windows.

However, it doesn't work for windowed projectors.

2022-01-16 14:29 UTC, notr1ch commented
> However, it doesn't work for windowed projectors. They still seem to be visible.

Projectors are intentionally excluded as there are cases of users capturing projectors with other apps, e.g. to show a PowerPoint presentation.

2022-01-16 18:16 UTC, Fenrirthviti commented
Just wanted to throw in feedback if we can confirm this works reliable and has no detrimental effects, I would prefer it was enabled by default as well.

2022-01-17 01:10 UTC, notr1ch commented
Pushed a new version with the changes requested above as well as new projector logic. Projectors now set a Qt property on the window handle so that they can easily be detected when the event handler finds a new window. This fixes the issue where fullscreen projectors also had their window affinity set to not capturable, since `showFullScreen()` was called before they were added to `allProjectors`, and it's nicer code overall.

2022-01-22 23:14 UTC, merged