obs-qsv11: Memory leak bug fix in QSV plugin module
obsproject/obs-studio pull request #5829
Opened 2022-01-20 01:44 UTC by cmlin2

### Description
This is a simple bug fix for a memory leak in the QSV plugin module

### Motivation and Context
Memory leaks (exacerbated by 4K and discrete graphics) will cause encoding failures on long recordings. These destructor checks/calls should have been in the original code but were missed and now fixed.

### How Has This Been Tested?
Re-tested on TGL and DG2 systems with QSV recording for 12+ hours to verify fix is working. 

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ X] My code is not on the master branch.
- [ X] The code has been tested.
- [ X] All commit messages are properly formatted and commits squashed where appropriate.
- [ X] I have included updates to all appropriate documentation.

2022-01-20 01:45 UTC, RytoEX commented
Can these be verified on non-TGL or DG2 systems?  If so, what are the steps-to-reproduce?

2022-01-20 01:50 UTC, RytoEX commented
The first commit here ("obs-qsv11: Remove Intel discrete device ID checking") was already merged into OBS from #5514 as https://github.com/obsproject/obs-studio/commit/3995326647f7255351a357b9f251659a3bdf75c7.  Was it mistakenly reincluded here?

2022-01-20 01:54 UTC, cmlin2 commented
Yes, it's most easy to reproduce (< 10 minutes) on a DG2 system only doing 4K recording. But a non-DG2 TGL system was able to reproduce it after 12 hours of 4K recording as well. The steps to reproduce on a non-DG2 or non-TGL system would just be to do 4K recording for a long period of time. But with the memory leak fix, it shouldn't happen anymore.

2022-01-20 03:56 UTC, cmlin2 commented
Sorry, my local branch was not updated, but I've fixed the issue and force pushed so that just the latest commit is included in the pull request (and not the one already merged into master).

2022-01-20 08:20 UTC, jpark37 commented
I wouldn't bother setting the variables to nullptr. They're invalid as soon as you exit the function anyway.

2022-01-20 08:21 UTC, jpark37 commented
Also don't need null checks because they have both been dereferenced by that point in the code.

2022-01-20 17:07 UTC, cmlin2 commented
Thanks, I've updated the code to just do the needed "->Release()" calls and re-pushed.

2022-01-20 17:08 UTC, hye5 approved these changes

2022-01-21 02:44 UTC, RytoEX requested changes
Please squash the two commits and use a commit subject that uses a verb after the prefix, such as:
> obs-qsv11: Fix memory leak in QSV plugin

2022-01-21 17:26 UTC, cmlin2 commented
I've squashed the commits and force pushed with correct verb in commit subject

2022-01-21 17:44 UTC, jpark37 commented
This is an OCD thing, but I prefer to release in reverse order of acquisition, mimicking RAII. If you could flip the two lines please. Commit looks good to me otherwise.

2022-01-21 18:29 UTC, jpark37 commented
Doesn't look like the flip was made.

> There isn’t anything to compare.

2022-01-21 20:57 UTC, cmlin2 commented
Oops, I forgot to do the "git add" before the "git commit --amend" and force push. Should be fixed now. :)

2022-01-22 23:30 UTC, merged