libobs: Fix overflow subtracting unsigned numbers
obsproject/obs-studio pull request #5946
Opened 2022-02-10 18:18 UTC by exeldro

### Description
Fix overflow subtracting unsigned numbers
When offset_size is greater than size, size would overflow.

### Motivation and Context
Don't like overflowing numbers causing crashes

### How Has This Been Tested?
On windows 64 bit

### Types of changes
- Bug fix (non-breaking change which fixes an issue) -->

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-02-10 19:28 UTC, exeldro commented
I have seen the error 3 times over the past 2 weeks on my debug environment. So rough estimate is 1 in 100 starts I get the error. My debug environment has a lot of plugins that might help causing the the error.

2022-02-10 21:21 UTC, WizardCM commented
I assume this is not new to 27.2?

2022-02-12 23:18 UTC, RytoEX requested changes
Just a simple spacing request.

2022-02-12 23:18 UTC, RytoEX commented on libobs/obs-encoder.c
>  	size -= offset_size;
To provide a distinct separation, I'd prefer a blank line between the `if` contents and the following line, or else wrap the `if` contents in curly braces.

2022-03-04 14:09 UTC, RytoEX approved these changes
Style is good. Seems functionally okay. I'll tentatively approve this based on those points, though further review is welcome.

Could you answer the earlier questions on this PR? Just seeking some clarity to make it easier to test and review.

1. Was this causing problems in practice or in the wild? (seems implied that people have only run into this in Debug builds so far)
2. Is this new to 27.2? Or has it been a problem before 27.2?
3. Is there an easy way to reproduce this?
4. What problems does it cause?

2022-03-04 17:40 UTC, exeldro commented
The cases I have seen have all been debug environment and OBS 27.2. I have not found an easy way to reproduce it. The problem is it will try to allocate close to max value of size_t in memory.

2022-03-08 20:31 UTC, merged