UI: Add ability to send messages from YouTube chat
obsproject/obs-studio pull request #6438
Opened 2022-05-08 16:49 UTC by gxalpha

### Description

Adds a custom text box to the YouTube chat which allows for sending messages using the YouTube API.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/59806498/167306352-0eed7ed2-78f4-4343-8198-1aebc5f70bbb.png">

#### Drawbacks
- Due to how the chat polls, after sending a message it takes 2-3 seconds for the message to appear in the chat. This would only be fixable by implementing a completely custom chat which has already been decided against in the past for various reasons (which still apply).
- The YouTube API doesn't appear to give you any info on whether the live chat is actually enabled on a stream (until you try to send a message). This means that when it's disabled, the text input field is still visible and users can still try to send messages. In that case, an error message will appear after sending.

TODO: There currently is an issue with the QLineEdit visually not losing focus (while it actually does lose focus). I'm opening this PR so that I have CI builds with which I can test if this is an issue on Windows as well or just on Mac (in which case it could be Qt's fault).
TODO: Replace "Send" button text with icon (and give it a localized accessible text)

### Motivation and Context

Users are used to being able to send messages to Twitch, they expect to be able to do so on YouTube as well.

### How Has This Been Tested?

macOS 12.4 Beta 4
Sending messages works!

Tests on Windows are still pending (they require PR artifacts, which hopefully have the secrets from my repo).

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-05-10 23:34 UTC, derrod commented
Since chat messages can have multiple lines, I think we should probably use a multiline editor, and then either have the button below (e.g. like twich where it's in the right of a vbox with a spacer on the left) or make it taller.

High quality paint-based concept art:
![concept](https://user-images.githubusercontent.com/3123295/167741211-3cc15df1-103c-49ef-8ff7-8e9d49090b4a.png)

I was also thinking that perhaps we can set a placeholder text in the text box starting with something like "Type here..." and changing it to something like "Message sent, it may take a few seconds for it to show up" (just shorter) after a message is sent so people aren't *as* confused when it takes a bit for it to show up.

2022-05-10 23:54 UTC, gxalpha commented
Are you sure that the YouTube chat allows multiline? I went for the single-line since when I tested this, pressing enter even with shift always sent the message, and the API seems to just ignore any `\n` newline.
<img width="222" alt="image" src="https://user-images.githubusercontent.com/59806498/167742605-f5f29980-a427-48ed-a4d8-9ad9f871a267.png">

Or do you just mean that the text can get so long that it could extend over multiple lines and it would be a better experience when typing to see everything?

2022-05-11 00:23 UTC, derrod commented
Mh I must've remembered wrong, I thought YouTube chat messages could contain newlines, but apparently that is not true.

As far as better visual presentation having a larger multi-line input box is probably still a good idea (not sure if you can disable newlines there and just have it break the text on the rendering side).

2022-05-11 11:11 UTC, gxalpha commented
> As far as better visual presentation having a larger multi-line input box is probably still a good idea (not sure if you can disable newlines there and just have it break the text on the rendering side).

Yeah that should be possible, albeit a bit complicated because this is Qt and Qt doesn't have such settings, meaning I might have to implement my own QTextBox.

2022-05-17 16:50 UTC, gxalpha commented
Added a three second `Sending...` placeholder text after the message got sent as discussed.

2022-05-31 15:05 UTC, RytoEX requested changes
Check opportunities for passing parameters as const, ref, or const-ref. I haven't compiled my suggestions, so please double check these when looking into them (no new warnings/problems).

2022-05-31 15:05 UTC, RytoEX commented on UI/window-youtube-actions.cpp
> +			std::string apiLiveChatId =
Could be const here?

2022-06-01 22:39 UTC, gxalpha commented
> Check opportunities for passing parameters as const, ref, or const-ref. I haven't compiled my suggestions, so please double check these when looking into them (no new warnings/problems).

Think I found them all. No new warnings.

2022-06-17 11:16 UTC, WizardCM approved these changes

2022-06-17 11:16 UTC, WizardCM commented on UI/data/locale/en-US.ini
> +YouTube.Errors.liveChatDisabled="The live chat has been disabled on this stream."
```suggestion
YouTube.Errors.liveChatDisabled="Live chat is disabled on this stream."
```

2022-06-17 11:16 UTC, WizardCM commented on UI/data/locale/en-US.ini
> +YouTube.Errors.liveChatEnded="The live chat is no longer live."
```suggestion
YouTube.Errors.liveChatEnded="Live stream has ended."
```

2022-06-25 19:57 UTC, Warchamp7 approved these changes

2022-06-25 22:09 UTC, RytoEX approved these changes
Finally tested this, and it works as advertised. May double check with Rich on one item before merging, but this is otherwise good to go.

2022-06-27 18:35 UTC, merged