UI: Update show/hide transitions for all selected items
obsproject/obs-studio pull request #6453
Opened 2022-05-11 09:04 UTC by cg2121

### Description
Instead of just updating the currently selected scene item's visibility
transition, when updating show/hide transition or duration, this updates
all of the selected items.

### Motivation and Context
Idea from @Warchamp7 

### How Has This Been Tested?
Made sure when updating show/hide transition, it affected all selected items.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-06-26 06:13 UTC, Warchamp7 commented
The transition choice seems to apply to all selected items, but not the configured options.

Ex. Applying a Slide transition to multiple selected items will put Slide on all of them, but only the one that was clicked will get configuration changes, such as swapping the slide direction in the transition settings.


Also got a crash while testing, trying to narrow it down

2022-07-24 01:16 UTC, cg2121 commented
Marking as draft, as it needs work with undo/redo. It undo/redos each source at a time instead of all of the selected ones.

2023-10-28 15:31 UTC, cg2121 commented
This now properly works with undo/redo.

2024-04-10 20:34 UTC, Warchamp7 commented
Looks to properly copy and paste transitions, but duration is incorrect. It always uses the global transition duration. However, that is not unique to this PR so may be out of scope to fix here.

2024-04-17 21:46 UTC, Warchamp7 commented
Will see if the above issue is solved naturally by #10511

2024-06-03 15:53 UTC, Warchamp7 requested changes
Issues still to be addressed:
- Copy duration as well when copying transition
- Don't display a checkmark in the list when the selected sources have mismatched selections

2026-09-09 17:02 UTC, Warchamp7 commented
This PR is being closed due to being stale. If you would still like to submit these changes, please open a new PR.

2026-09-09 17:02 UTC, closed without merging