UI: close display before native surfaces
obsproject/obs-studio pull request #6487
Opened 2022-05-16 02:59 UTC by kkartaltepe

### Description

This hooks the platform specific events in order to close the obs
display more accurately. Earlier attempts on hooking visiblity in Qt
does not ensure that visibility is changed before the surface is
destroyed. So we ended up racing with the egl driver, and on some
drivers if you lose the race they hang.

Also force closure of the main preview window earlier to avoid similar
ordering issues in qt.

Finally only force display creation if the display is actually visible.
When a source type is not video/drawable (or is missing) this would
force the display to be created for the blank window and also hang.

### Motivation and Context

People prefer if obs doesnt hang on their favorite proprietary drivers. Mostly resolves #6466 

### How Has This Been Tested?

Repeatedly opening and closing source and filter properties worked. Opening xcomposite source properties on wayland also didn't hang the render thread.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-05-16 03:03 UTC, kkartaltepe commented
This needs testing on Windows and Mac to make sure the early delete on the preview doesnt affect them

2022-05-21 00:57 UTC, RytoEX approved these changes
Tested the CI artifact on Windows with a debugger attached per @kkartaltepe 's instructions and I observed no adverse effects there. May still need macOS testing.

2022-05-21 00:58 UTC, kkartaltepe commented
To clarify the testing steps for mac/windows the changes related to that platform are for the main OBS display. So if you could just enable/disable the preview a few times and verify nothing looks different visually and nothing explodes. Similarly starting and closing obs with the preview enabled under a debugger to make sure nothing crashes on close.

2022-05-21 01:05 UTC, RytoEX requested changes
Commit message nits:
1. Qt
2. EGL
3. Use "Close" for the first word of the commit message subject.

Otherwise, my previous approval still stands.

2022-05-26 01:13 UTC, kkartaltepe commented
Thanks updated, there was one thing I missed which was testing studio mode. Unfortunately even with this change there is still a chance of hang on close for studio mode it seems (maybe 1/10 in my tests).

2022-05-26 02:33 UTC, kkartaltepe commented
Changed around the strategy for handling preview/program so this seems a bit more straightforward and works better in both cases i think. Also reworded the commit message a bit.

2022-05-28 23:54 UTC, merged