deps/media-playback: Revert optimization attempt
obsproject/obs-studio pull request #6488
Opened 2022-05-16 05:39 UTC by jpark37

### Description
Previous attempt causes short videos to loop improperly. Get rid of
extra allocations, and simplify logic some other day.

### Motivation and Context
Want video loop to look nice.

### How Has This Been Tested?
Video loop looks nice again.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-05-16 14:58 UTC, RytoEX approved these changes
I can confirm this fixes the issue I described off-thread, so I'm approving based on that. I'm still not sure if there should be a revert commit with the fixes/changes then committed after that (even after sleeping on it, I'm still not sure what's best for diff/blame), but don't let that hold this up if the code is otherwise fine.

2022-05-21 01:26 UTC, RytoEX requested changes
Just noticed that the commit message links to a commit on your fork instead of the commit on this repo. Please fix that, and then I'll move this back to approved from me.

2022-05-21 01:53 UTC, jpark37 commented
I think GitHub is being weird? It looks like the same hash to me.

2022-05-21 02:03 UTC, RytoEX commented
> I think GitHub is being weird? It looks like the same hash to me.

You might be right. Maybe it's just linking to your fork because the commit is technically coming from your fork. Never mind then.

2022-05-21 02:03 UTC, RytoEX approved these changes

2022-05-21 22:28 UTC, merged