libobs, win-wasapi: Handle changes to the default audio monitoring device
obsproject/obs-studio pull request #6657
Opened 2022-06-26 08:48 UTC by tt2468

### Description
todo

### Motivation and Context
When the default Windows output changes, OBS should switch to the new one if it is configured to use default.

### How Has This Been Tested?
todo

### Types of changes
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Documentation (a change to documentation pages)

### Checklist:
- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2022-06-26 10:03 UTC, jp9000 commented
Are you intending to share this code over multiple modules? An initial take I have of this is I'm not sure if it's really all that necessary to do so. Also, the wasapi code in libobs is not C++, so it will not work with STL callbacks. Plus I'm kind of wondering if the STL usage feels a bit excessive and possibly unnecessary, but maybe that's just my humble opinion on the matter.

Personally, I feel like this particular class (IMMNotificationClient I mean) is so trivial and never really used for any other purposes that I don't really mind if there's a little bit of code duplication just to separate the libobs code from the win-wasapi plugin code. That was kind of one of the issues I had with the implementation walker made as well. Sometimes there are times where trying to solve code duplication can *possibly* make things a little less pleasant than they would be if you just did the same thing twice. In those sort of situations it's not a big deal if you have two sets of code that basically do the same thing as long as it makes things cleaner and is highly unlikely to be modified/customized again. But again, that's just my personal philosophy with that sort of thing.

Sometimes certain approaches can be a bit subjective. For example I probably could have just written this plugin entirely in C, and sometimes I kind of wish I did, but I suppose it doesn't matter that much.

2022-07-14 23:28 UTC, RytoEX requested changes
Nit. Will try to test this at some later time.

2022-07-14 23:28 UTC, RytoEX commented on docs/sphinx/reference-core.rst
> +.. function:: boid obs_reset_audio_monitoring(void)
`boid` -> `void`

2022-07-24 21:36 UTC, RytoEX commented
With this PR, I can confirm that when the OBS audio monitoring device is set to Default, it now follows changes to Windows' default output device.

I understand that there is ongoing discussion about the structure of the code, so I will defer to others on when this is good to merge.

2023-11-07 07:26 UTC, Lain-B approved these changes

2023-11-07 07:32 UTC, Lain-B commented
Rebased and fixed up issues. The only issue I have with this is that it makes it so that the audio monitoring on windows is sort of dependent upon the win-wasapi to update it when the device has changed, but I suppose it's sufficient for now and keeps all the code in one place for it.

2023-11-07 07:32 UTC, merged

2023-11-07 08:26 UTC, tt2468 commented
I think it could be moved in the future easily to another place. To me, having the function to reset audio monitoring is helpful regardless of this specific usage of it here.