obs-qsv11: Fix timestamp for 59.94 fps
obsproject/obs-studio pull request #6679
Opened 2022-07-02 02:12 UTC by norihiro

### Description

Added a function `ts_mfx_to_obs` to convert the timestamp in MFX to OBS, which rounds timestamps to the closest multiple of `fps_den`.

FFmpeg uses `av_rescale_q`, which rounds to nearest and halfway cases away from zero at the code below.
https://github.com/FFmpeg/FFmpeg/blob/804bf898dad32813c6bc05ae19d0dcfd45cd8d8a/libavcodec/qsvenc.c#L1840-L1841

Also added a function `ts_obs_to_mfx` to convert that in OBS to MFX. The behavior is not changed but it will be better to understand the code.

(I didn't put `inline` since [Linux kernel coding style](https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#15-the-inline-disease) suggested not to. If `inline` is preferable, I will add it.)

### Motivation and Context

When frame rate is set to 59.94 fps (60000/1001), MFX cannot handle the timestamp accurately. That causes the timestamp converted back to OBS has an error.

With these settings, `Stop Recording` never stops recording.
- Frame rate is 59.94 (60000/1001) fps.
- File format is mp4.

### How Has This Been Tested?

The newly added functions are tested with code below on Linux.
```c
bool doit(int64_t ix_frame, const struct video_output_info *voi)
{
	int64_t ts_obs0 = ix_frame * voi->fps_den;
	mfxI64 ts_mfx = ts_obs_to_mfx(ts_obs0, voi);
	int64_t ts_obs1 = ts_mfx_to_obs(ts_mfx, voi);

	if (ts_obs0 == ts_obs1)
		return true;

	return false;
}
	
int main()
{
	const struct video_output_info vois[] = {
		{ 25, 1 },
		{ 30, 1 },
		{ 50, 1 },
		{ 60, 1 },
		{ 30000, 1001 },
		{ 60000, 1001 },
		{ 0, 0 }
	};

	for (int i = 0; vois[i].fps_num; i++) {
		for (int j = -2; j < 2003; j++) {
			if (!doit(j, &vois[i])) {
				printf("Error: ix_frame=%d fps=%d/%d\n",
						j, (int)vois[i].fps_num, (int)vois[i].fps_den);
				return 1;
			}
		}
	}

	return 0;
}
```

Set advanced output mode, then manually set `obs_qsv11_soft` by editing `basic/profiles/Untitled/basic.ini` and recorded for several minutes.
```
[AdvOut]
Encoder=obs_qsv11_soft
RecEncoder=obs_qsv11_soft
```

Unfortunately, I don't have a hardware that can run `obs_qsv11`. Most part of the code is shared between `obs_qsv11` and `obs_qsv11_soft` but it is better to test `obs_qsv11` by someone.

Checked the recorded file with FFprobe as below. Both pts and dts looks correct.
```
$ ffprobe -hide_banner -select_streams v -loglevel error -show_entries packet=codec_type,pts,dts,pts_time,dts_time -of compact 'recorded-fix-qsv11.mp4' | head
packet|codec_type=video|pts=0|pts_time=0.000000|dts=-2002|dts_time=-0.033367
packet|codec_type=video|pts=4004|pts_time=0.066733|dts=-1001|dts_time=-0.016683
packet|codec_type=video|pts=2002|pts_time=0.033367|dts=0|dts_time=0.000000
packet|codec_type=video|pts=1001|pts_time=0.016683|dts=1001|dts_time=0.016683
packet|codec_type=video|pts=3003|pts_time=0.050050|dts=2002|dts_time=0.033367
packet|codec_type=video|pts=8008|pts_time=0.133467|dts=3003|dts_time=0.050050
packet|codec_type=video|pts=6006|pts_time=0.100100|dts=4004|dts_time=0.066733
packet|codec_type=video|pts=5005|pts_time=0.083417|dts=5005|dts_time=0.083417
packet|codec_type=video|pts=7007|pts_time=0.116783|dts=6006|dts_time=0.100100
packet|codec_type=video|pts=12012|pts_time=0.200200|dts=7007|dts_time=0.116783
```

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-02 02:55 UTC, norihiro commented
I will close since Ryan has already investigated and about to make a fix.

2022-07-03 04:23 UTC, norihiro commented
When set to 29.97 fps (30000/1001 fps), `DecodeTimeStamp` returned from the encoder has sequence like this.
```
-6006 -3003 0 3003 6006 9008 12012 15015
```

It is expected to be the multiple of `fps_den` but actually sometimes slightly off. In above example, 9008 is supposed to be 9009. In the current implementation, `DecodeTimeStamp`=9008 causes `dts`=3002 in obs, which is wrong timestamp. With this PR, the `dts` in obs will be rounded to the nearest multiple of `fps_den` so that `dts` becomes 3003 at above example.

2022-07-03 04:29 UTC, norihiro commented on plugins/obs-qsv11/obs-qsv11.c
> +		       voi->fps_den * voi->fps_den;
If there is an issue at non-fractional frame rate, I think we should have rounding for dividing by 90000 as well.
```suggestion
	int64_t den = 90000 * voi->fps_den;
	/* Round to the nearest integer multiple of den */
	if (ts < 0)
		return (ts * voi->fps_num - den / 2) / den * voi->fps_den;
	else
		return (ts * voi->fps_num + den / 2) / den * voi->fps_den;
```

2022-07-03 04:33 UTC, RytoEX commented
> When set to 29.97 fps (30000/1001 fps), `DecodeTimeStamp` returned from the encoder has sequence like this.
> 
> ```
> -6006 -3003 0 3003 6006 9008 12012 15015
> ```
> 
> It is expected to be the multiple of `fps_den` but actually sometimes slightly off. In above example, 9008 is supposed to be 9009. In the current implementation, `DecodeTimeStamp`=9008 causes `dts`=3002 in obs, which is wrong timestamp. With this PR, the `dts` in obs will be rounded to the nearest multiple of `fps_den` so that `dts` becomes 3003 at above example.

Correct. That is in my prior notes on the subject.

2022-07-03 06:59 UTC, norihiro commented on plugins/obs-qsv11/obs-qsv11.c
> +		       voi->fps_den * voi->fps_den;
Implemented this change since I noticed DTS can be inaccurate even when the frame rate is integer but uncommon values such as 119 fps.

2022-07-09 23:04 UTC, RytoEX requested changes
If we assume these values:
```
ts = 0
voi->fps_num = 60000
voi->fps_den = 1001
div = 90090000
```
then:
```
(ts * voi->fps_num + div / 2) / div * voi->fps_den
(0 * 60000 + 90090000 / 2) / 90090000 * 1001
(0 + 45045000) / 90090000 * 1001
45045000 / 90090000 * 1001
```
Here, while one might think `45045000 / 90090000` would be `0.5`, it is `0` due to integer division rules in C:
> When integers are divided, the result of the / operator is the algebraic quotient with any
fractional part discarded.

So, continuing:
```
45045000 / 90090000 * 1001
0 * 1001
0
```

The next timestamp would be 1501, so:
```
(ts * voi->fps_num + div / 2) / div * voi->fps_den
(1501 * 60000 + 90090000 / 2) / 90090000 * 1001
(90060000 + 45045000) / 90090000 * 1001
135105000 / 90090000 * 1001
1 * 1001
1001
```
This also checks out.

I stepped through a small sample of resulting timestamps and they seemed correct to me. I have two questions (see inline review comments), but otherwise this is probably okay. I wish the match wasn't so verbose, but I can't change how math works.

2022-07-09 23:18 UTC, norihiro commented on plugins/obs-qsv11/obs-qsv11.c
> +	mfxU64 qsvPTS = ts_obs_to_mfx(frame->pts, voi);
I've revised the definition of `ts_obs_to_mfx` to return `mfxU64`.

2022-07-12 18:46 UTC, RytoEX commented on plugins/obs-qsv11/obs-qsv11.c
> +	mfxU64 qsvPTS = ts_obs_to_mfx(frame->pts, voi);
I think the only place this is used is to assign a value to an `mfxU64`, so this seems fine.

2022-07-14 23:19 UTC, RytoEX approved these changes
Comment is clarified. This has passed every test I had available, so this seems good to me.

2022-07-14 23:20 UTC, merged