graphics-hook: Unhook DXGI when using Vulkan
obsproject/obs-studio pull request #6698
Opened 2022-07-08 16:46 UTC by elaberge

### Description
Added an "unhook_dxgi" method to the DXGI handler.
That method restores the original DXGI calls.
It is called when successfully hooking the Vulkan API.
When the Vulkan API is hooked, mark the DXGI API as hooked, so it is not hooked again.

### Motivation and Context
Some Vulkan apps for Windows use a DXGI backend, which is called by the Vk "Present" API call. That makes OBS double-hooked during the same call, first by the Vulkan hook, which then call its native implementation, which then calls the DXGI hook in return.

That makes the Vulkan call to capture_should_init true, then the D3D11 call to capture_should_init false, causing the d3d11_capture method to call d3d11_shmem_capture (as data.using_shtex still having its default "false" value), which in turn uses an unititialized mutex as the d3d11_init method has not been called, and leads to a crash.

### How Has This Been Tested?
This was tested on Windows 10 20H2, on a RTX 2070 Super with driver version 516.40, with the project at the last tagged revision (27.2.4).
Tests were done with the stock version of the graphics-hook64.dll for comparison, and with Debug versions for development. Final tests were done back with a RelWithDebug version to confirm the fix.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-09 23:15 UTC, jp9000 commented
> Some Vulkan apps for Windows use a DXGI backend

Which ones?

2022-07-10 02:25 UTC, jpark37 requested changes
Not sure we want to detach the hook functions. Might be safer to signal to the DXGI hook functions that they should become passthroughs.

I'd also like to know if there are any popular games/applications to test this against because there is regression risk any time the handshaking is altered, and I'd rather not do this if this is just for a theoretical sample.

2022-07-10 13:22 UTC, elaberge commented
This happens with Rainbow Six Siege, when launched in Vulkan. Possibly related to issue #4653.
Launching R6, then OBS and starting game capture might or might not work, and just stopping and restarting capture while the game is running, even on the title screen, causes the game to crash easily, or at best, get a black screen.
With the fix (tested by turning off BattleEye with R6 option "/belaunch -be", required due to the custom build DLL being discarded by the anti-cheat system), I can toggle capture as long as I wish without the game ever crashing.

2022-07-10 13:26 UTC, elaberge commented
I agree it might be better to use a passthrough implementation, will do.

2022-07-10 17:08 UTC, jpark37 commented
Sorry, I missed that you said DXGI present was literally happening inside Vulkan present. Are you using DXVK on Windows?

2022-07-10 18:45 UTC, elaberge commented
> Sorry, I missed that you said DXGI present was literally happening inside Vulkan present. Are you using DXVK on Windows?

This is just plain nvidia drivers, with any extra layer disabled to make sure.

2022-07-10 19:47 UTC, elaberge commented
That last change is only to keep the history I force-pushed over the first implementation.

2022-07-10 20:14 UTC, jpark37 commented
I enabled HOOK_VERBOSE_LOGGING, and I'm not seeing any DXGI present logging. I'm launching the Vulkan build through Steam with BattlEye off. Vulkan capture seems to be working fine.

This also seems annoying to debug because the process seems to terminate when I attach VS debugger.

2022-07-10 21:01 UTC, elaberge commented
Yeah, debugging without a debugger is a PITA. I found that issue with game code I can actually compile, it's just that R6 seems to exhibit the same problem, and it actually helps me validate the issue.

For the record, here's a run with HOOK_VERBOSE_LOGGING without this fix:
[log-default-2022-07-10 16-45-52.txt](https://github.com/obsproject/obs-studio/files/9079886/log-default-2022-07-10.16-45-52.txt)

And here's with this fix:
[log-fixed-2022-07-10 16-53-20.txt](https://github.com/obsproject/obs-studio/files/9079885/log-fixed-2022-07-10.16-53-20.txt)

2022-07-10 21:37 UTC, elaberge commented
Here you go:
```
>	graphics-hook64.dll!hook_present(IDXGISwapChain * swap, unsigned int sync_interval, unsigned int flags) Line 206	C++
 	nvoglv64.dll!00007fff9c1022b3()	Unknown
 	nvoglv64.dll!00007fff9c1351e4()	Unknown
 	nvoglv64.dll!00007fff9c1131c2()	Unknown
 	nvoglv64.dll!00007fff9c136869()	Unknown
 	nvoglv64.dll!00007fff9c23128f()	Unknown
 	nvoglv64.dll!00007fff9c23da5a()	Unknown
 	nvoglv64.dll!00007fff9c2548b5()	Unknown
 	nvoglv64.dll!00007fff9c0d13c6()	Unknown
 	nvoglv64.dll!00007fff9c219f13()	Unknown
 	nvoglv64.dll!00007fff9c1f69a4()	Unknown
 	nvoglv64.dll!00007fff9c1f5f8f()	Unknown
 	nvoglv64.dll!00007fff9c47f169()	Unknown
 	nvoglv64.dll!00007fff9c4810ad()	Unknown
 	nvoglv64.dll!00007fff9c47bc93()	Unknown
 	nvoglv64.dll!00007fff9c563c5a()	Unknown
 	graphics-hook64.dll!OBS_QueuePresentKHR(VkQueue_T * queue, const VkPresentInfoKHR * info) Line 1226	C
```
Followed by game code calling vkQueuePresentKHR

2022-07-10 22:28 UTC, jpark37 commented on plugins/win-capture/graphics-hook/dxgi-capture.cpp
> +
Move this block to the top of the function.

2022-07-10 22:29 UTC, jpark37 commented on plugins/win-capture/graphics-hook/dxgi-capture.cpp
> +
Move this block to the top of the function.

2022-07-10 22:36 UTC, jpark37 commented
What an unexpected call stack... I guess we have to trust that this is legitimate. Just make or at least respond to the requested changes. As long as this doesn't cause a regression, I'll approve it.

2022-07-10 22:44 UTC, jpark37 commented
Should also update the PR description

2022-07-10 22:46 UTC, jpark37 commented
Should also squash your commits because we don't want to merge the history of your changes. This should just be one commit.

2022-07-29 15:22 UTC, jpark37 commented
There's still an item remaining.

2022-07-29 20:26 UTC, jpark37 commented
Apparently review comments are invisible to everyone except the reviewer until a review is started. Hopefully you can see the feedback now.

2022-07-30 00:44 UTC, elaberge commented on plugins/win-capture/graphics-hook/vulkan-capture.c
> +volatile int vk_presenting = 0;
That was my first idea, but the shared graphics-hook.h used by both plain C and C++ code disallowed using the straight thread_local specifier. The project configures pre-C11 compilation, which doesn't have that concept. I went with the __declspec(thread) extension which works with both, as that is Windows-code only anyway.

2022-07-30 00:59 UTC, jpark37 approved these changes

2022-07-30 04:54 UTC, merged