rtmp-services: Update ingest list for Livito.tv
obsproject/obs-studio pull request #6765
Opened 2022-07-19 06:57 UTC by vdavari

### Description
Add new rtmp service (Livito.tv)

2022-07-19 07:01 UTC, Fenrirthviti commented
Please properly fill out the PR template. In the future, do not just delete it.

Do you work for Livito.tv? Per the [service submission guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines) we can only accept new services directly from the service.

2023-02-03 16:04 UTC, RytoEX requested changes

2023-02-03 16:04 UTC, RytoEX commented on plugins/rtmp-services/data/package.json
> +}
Do not remove the blank line at the end of files.

2023-02-03 16:04 UTC, RytoEX commented on plugins/rtmp-services/data/services.json
> +}
Do not remove the blank line at the end of files.

2023-02-13 15:16 UTC, RytoEX requested changes
Per our [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines):
> The `rtmp-services` package version needs to be incremented for OBS to know that there has been an update, simply increment the version numbers in `plugins/rtmp-services/data/package.json` by 1.

In the future, please:
1. Do not use merge commits.
2. Do not make PRs from your master branch.
3. Do not delete the PR template.
4. Squash the commits into a single commit.

Regarding the PR template, it is still not filled out correctly. Please actually fill out the template as requested.

2023-03-01 22:05 UTC, Fenrirthviti commented
Closing due to lack of response.

2023-03-01 22:05 UTC, closed without merging