UI: Qt 6 deprecations, Part 1
obsproject/obs-studio pull request #6770
Opened 2022-07-19 16:11 UTC by gxalpha

### Description

Fixes deprecations for Qt.
There are more deprecations for setButtonText in `OBSMessageBox::question`, but solving this might contain changing every call to that function, which is a somewhat bigger change that can be done later.

### Motivation and Context

Less deprecations.

### How Has This Been Tested?

First commit:
- Undo/Redo hotkeys still work
- Moving items in the preview with arrow keys still works (with shift as well)

Second commit:
- Context Bar Media Slider (MediaSlider)
- Quick Transitions Button (MenuButton)
- Drag and Drop in Sources Dock and Scenes Dock (SourceTree and SceneTree)
- Interact Menu on Browser Source, with pointerpointer.com and webgl aquarium (OBSBasicInteraction)
- In preview, moving the mouse over items correctly highlights the item where the mouse is. When dragging a selection, that selection is in the correct place
- In multiview, clicking a scene correctly selects it for the preview. With "Transition to scene when double-clicked" enabled, double clicking a scene selects and transitions to it.

Third commit:
- Raised a sample information, warning, and critical message box

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-19 22:43 UTC, RytoEX requested changes
Did a quick visual review.

2022-07-19 22:43 UTC, RytoEX commented on UI/window-basic-preview.cpp
> +
Nit: can remove this blank line.

2022-07-21 05:48 UTC, tytan652 commented
Build against #6759 with Qt6 and got those lines as errors:
- https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L2127
- https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L2129
- https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main.cpp#L379 (Linux only)

Otherwise it builds fine.

2022-07-21 12:15 UTC, gxalpha commented
@tytan652 should be fixed, feel free to re-test

2022-07-21 12:22 UTC, tytan652 commented
I confirm that this now that this PR as it is builds against #6759 with no errors without any fix required.

2022-07-22 00:56 UTC, RytoEX approved these changes
All my tests in Qt 6.3.0-git (close to 6.3.1) worked fine. I think @gxalpha had tested this in Qt5 for good measure, and CI is still building against as well, so at minimum we know it builds without warnings/errors.

2022-07-22 13:37 UTC, RytoEX commented
Ran through the same tests I did yesterday, but with Qt 5.15.2. Everything seemed to work fine.

2022-07-22 13:37 UTC, merged