Allow HEVC on in streaming only if the service is compatible
obsproject/obs-studio pull request #6778
Opened 2022-07-21 06:59 UTC by tytan652

### Description

While the user change his streaming service, if an incompatible encoder was set the user will got this warning explaining that the encoder was changed because of the incompatibility.
![HEVC_Warning](https://user-images.githubusercontent.com/17492366/180148824-160cbcb5-e480-404c-8eb3-cf831e1a9270.png)

### Motivation and Context

When HEVC is enabled, HEVC encoder can be used with any service, this PR try to avoid this.
It also add HEVC as supported codec for mpeg-ts based protocols (HLS, RIST, SRT)

Also clear the issue I have with #6617.

This might be refactored afterward because of https://github.com/obsproject/rfcs/pull/45 and https://github.com/obsproject/rfcs/pull/39.

### How Has This Been Tested?

- Set a service compatible with HEVC
- Set an HEVC encoder (they are not shown if the service is not compatible)
- Change the service for one that does not support HEVC and a warning should show.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-21 07:11 UTC, tytan652 commented
Stupid me has forgot to stage some changes.

2022-07-21 09:09 UTC, SuslikV commented
In my opinion, if this kind of warning/forcing/restriction will be implemented. it should use already available control: _Ignore streaming service setting recommendations_

2022-07-21 09:11 UTC, tytan652 commented
> In my opinion, if this kind of warning/forcing/restriction will be implemented. it should use already available control: _Ignore streaming service setting recommendations_

Not for codecs, codecs are not a recommendation.

2022-07-21 12:25 UTC, tytan652 commented
Sidenote: I could improve this by adding codecs in the Service API, but since I made this https://github.com/obsproject/rfcs/pull/45, I don't this PR to be taken for a part of the implementation of this RFC.

2022-07-22 01:22 UTC, lextra2 commented
IMHO

```
The selected video encoder is not compatible with the streaming service.
Check your output settings.
```

sounds better.

2022-07-22 01:46 UTC, RytoEX requested changes
Just a quick visual review. Found some string nits.

2022-07-22 01:46 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +Basic.Settings.Stream.ChangeIncompatibleEncoder.Title="Incompatitle encoder changed"
Incompatitle -> Incompatible

2022-07-22 01:46 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +Basic.Settings.Stream.ChangeIncompatibleEncoder.Simple="The actually selected encoder is not compatible with the actual service.\nThe encoder in the output page was changed by its H264 version."
Not sure about "The actually selected encoder". Is this distinct somehow from "The selected encoder"? Same with "the actual service" vs. "the service".

2022-07-22 01:46 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +Basic.Settings.Stream.ChangeIncompatibleEncoder.Simple="The actually selected encoder is not compatible with the actual service.\nThe encoder in the output page was changed by its H264 version."
"changed by its H264 version." -> "changed to its H264 version." ?

2022-07-22 01:46 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +Basic.Settings.Stream.ChangeIncompatibleEncoder.Simple="The actually selected encoder is not compatible with the actual service.\nThe encoder in the output page was changed by its H264 version."
"H264" -> "H.264"

2022-07-23 14:02 UTC, RytoEX requested changes
String nit

2022-07-24 08:06 UTC, closed without merging

2022-07-29 09:06 UTC, SuslikV commented
Closed in favor of
https://github.com/obsproject/obs-studio/commit/48819def6df056f5aee58bebb05a64ca308aa378