UI: Fix current item on float-type combobox property
obsproject/obs-studio pull request #6788
Opened 2022-07-23 02:18 UTC by norihiro

### Description

When finding current item for a combobox on properties view, use `QVariant` type to hold current values instead of converting all types into string.

### Motivation and Context

A combobox created with `OBS_COMBO_FORMAT_FLOAT` cannot show the current item. When a modified callback for another item on the properties view returns true, the combobox is initialized again and the selection goes to the top item even though another item is selected.

When adding items into the combobox, `userData` is generated in the code below.
https://github.com/obsproject/obs-studio/blob/e3f416f3fc72db49d1ba71b8423454d053a9d6bf/UI/properties-view.cpp#L505-L523

| OBS's type | `userData` generation function |
| ---------- | --------- |
| `OBS_COMBO_FORMAT_INT`    | `QVariant::fromValue<long long>(long long)` |
| `OBS_COMBO_FORMAT_FLOAT`  | `QVariant::fromValue<double>(double)` |
| `OBS_COMBO_FORMAT_STRING` | `QByteArray(const char *)` |

### How Has This Been Tested?

OS: Fedora 35
Qt version: 5.15.2-31.fc35

Checked these steps for `xshm_input` (using `OBS_COMBO_FORMAT_INT`) and `slideshow` (using `OBS_COMBO_FORMAT_STRING`).
- Create a source.
- Open it's properties view.
- Choose another item in combobox.
- Close the properties view and open it again.
- Check the combobox shows the same item.
  - Before this bugfix, the top item is always selected at this step for the combobox with `OBS_COMBO_FORMAT_FLOAT`.

Also checked another source under development using `OBS_COMBO_FORMAT_FLOAT`.

Need to check autoselect functionality but only available on two sources `av_capture_input` on macOS and `dshow_input` on Windows.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
  - I didn't test autoselect functionality.
  - I didn't test on Windows though especially the behavior of `QT_UTF8` is different on Windows.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-23 02:29 UTC, RytoEX commented
> I've checked the signature and description of `QComboBox::findData` are same in between Qt5 and Qt6.
> Qt5: https://doc.qt.io/qt-5/qcombobox.html#findData
> Qt6: https://doc.qt.io/qt-6/qcombobox.html#findData

See [QTBUG-104990](https://bugreports.qt.io/browse/QTBUG-104990).
cc: @gxalpha

2022-07-23 02:51 UTC, norihiro commented
However [QTBUG-104990](https://bugreports.qt.io/browse/QTBUG-104990) claims the bug was introduced in Qt6, the issue was found in Qt5. Maybe `OBS_COMBO_FORMAT_INT` is broken by Qt6 but `OBS_COMBO_FORMAT_FLOAT` is not working in both Qt5 and Qt6.

2022-07-23 03:07 UTC, RytoEX commented
> However [QTBUG-104990](https://bugreports.qt.io/browse/QTBUG-104990) claims the bug was introduced in Qt6, the issue was found in Qt5. Maybe `OBS_COMBO_FORMAT_INT` is broken by Qt6 but `OBS_COMBO_FORMAT_FLOAT` is not working in both Qt5 and Qt6.

I'm saying that the behavior of `QComboBox::findData` changes between Qt5 and Qt6, which is why I highlighted the text saying that the function is the same between Qt5 and Qt6.

2022-07-28 05:39 UTC, jpark37 commented on UI/properties-view.cpp
> +		return QVariant::fromValue<long long>(get_int(data, name));
Template type should be inferred from get_int.

2022-07-28 05:39 UTC, jpark37 commented on UI/properties-view.cpp
> +		return QVariant::fromValue<double>(get_double(data, name));
Template type should be inferred from get_double.

2022-07-28 05:42 UTC, jpark37 commented
I know I just added two (optional) defects, but please merge this sooner than later. It's quite a nasty bug. The code looks good otherwise.

2022-07-28 06:05 UTC, jpark37 requested changes
Update the commit message. This is no longer just about OBS_COMBO_FORMAT_FLOAT.

2022-07-28 09:14 UTC, jpark37 approved these changes

2022-07-28 09:15 UTC, jpark37 commented
Looks good to me. Someone merge this ASAP as possible.

2022-07-28 16:21 UTC, merged