mac-capture: Add transparent background option to SCK App Capture
obsproject/obs-studio pull request #6862
Opened 2022-07-29 23:03 UTC by gxalpha

### Description

Adds an option to SCK Application Capture to make the background transparent.
Only available on macOS 13, because on 12.5 the desktop icons (like drives, files and folders) show. Should this get fixed with a macOS 12 update (like 12.6) we'll make it available there as well.

### Motivation and Context

Users might want transparency instead of just a black background.

### How Has This Been Tested?

macOS 13.
Tested that it doesn't work on 12 by changing the guards to check for macOS 14.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-07-30 12:06 UTC, PatTheMav requested changes
Just one thing/idea:

Maybe instead of storing a boolean in the `sc` struct, let's store the color ref (in this case the result of `CGColorGetConstantColor`) and pass that value to `setBackgroundColor`.

That way we could later add a colour picker and (though it probably should be a native colour picker or we'd have to transfer the colour codes given by Qt to create CGColorRefs) and not have to change the internal structure again.

2022-07-30 12:23 UTC, gxalpha commented
Would we want to allow custom background colors in the future? I feel users could just be adding a color source behind the SCK source if they need that

2022-07-30 13:31 UTC, PatTheMav commented
> Would we want to allow custom background colors in the future? I feel users could just be adding a color source behind the SCK source if they need that

Fair point, no further objections from my side then.

2022-07-30 13:32 UTC, PatTheMav approved these changes

2022-07-31 00:11 UTC, WizardCM approved these changes

2022-07-31 01:22 UTC, merged