UI/installer: Require Windows 10 64bit minimum
obsproject/obs-studio pull request #6929
Opened 2022-08-03 12:58 UTC by WizardCM

### Description

This updates the Windows Vista check to Windows 8.1 and lower.

![image](https://user-images.githubusercontent.com/941350/182612961-bbadd511-1ea8-4ba6-b8f2-ba145ba1e572.png)

This also improves the wording of the 32bit error.

Submitting this as a PR to get feedback on wording, and to determine if more 32bit/64bit code should be removed from the installer script.

### Motivation and Context

With Qt 6, Windows 8.1 and below are no longer supported.

Additionally, 32bit is no longer supported.

### How Has This Been Tested?

* Launch the installer on Windows 8.1.
* Click "Next" to go past the first screen
* See error message

### Types of changes
 - Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-08-03 13:54 UTC, RytoEX requested changes
Other than my one review comment, this looks fine. I don't think we need to roll a bigger cleanup into this. We should just keep it scoped as-is and deal with bigger cleanups later. In fact, I would defer huge cleanups until _after_ 28.0 is officially released, so that we don't run the risk of having a lot of stuff to roll back.

2022-08-03 13:54 UTC, RytoEX commented on UI/installer/mp-installer.nsi
> +		MessageBox MB_OK|MB_ICONSTOP "${APPNAME} is not compatible with your system's architecture."
Technically, it's the operating system's architecture and not necessarily the system's (hardware's) architecture. A person could, for _some_ reason, be running a 32-bit OS on 64-bit capable hardware.

2022-08-04 05:01 UTC, dodgepong commented
Have we confirmed that Qt 6 doesn't work on 8.1, or are we just taking Qt's word for it that it doesn't work on 8.1?

2022-08-04 05:05 UTC, WizardCM commented
> Have we confirmed that Qt 6 doesn't work on 8.1, or are we just taking Qt's word for it that it doesn't work on 8.1?

Yep, confirmed it myself just in case. This is the error users see:

![image](https://user-images.githubusercontent.com/941350/182767071-9da934b6-8dcd-4234-a341-ab514344a6ba.png)

2022-08-04 05:19 UTC, RytoEX commented on UI/installer/mp-installer.nsi
> +		MessageBox MB_OK|MB_ICONSTOP "${APPNAME} is not compatible with your system's architecture."
If it wasn't clear, I prefer this string:
```
"${APPNAME} is not compatible with your operating system's architecture."
```

2022-08-08 22:56 UTC, RytoEX approved these changes
Looks good to me.

2022-08-09 12:43 UTC, merged