UI: Fix source tree item color height
obsproject/obs-studio pull request #6985
Opened 2022-08-07 07:06 UTC by cg2121

### Description
This fixes an issue where the source tree item's widget
wouldn't expand to the size of the parent list item.

Due to some QT wonkiness, the widget inside the list item
cannot be resized, that's why padding only works on the item
not the widget inside. So we have to set a fixed height of list
items, and then the widget inside resizes properly,

This affected all themes that used padding with the list items.

Before:
![Screenshot from 2022-08-07 01-47-41](https://user-images.githubusercontent.com/19962531/183279281-937827fb-5756-49cf-a591-f84e2e829fc6.png)

After:
![Screenshot from 2022-08-07 01-45-46](https://user-images.githubusercontent.com/19962531/183279297-abcd73f5-2d66-43d1-b966-e0b6f11840c8.png)

### Motivation and Context
Fix theme bugs

### How Has This Been Tested?
Set scene item colors and made sure everything looked good.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-08-07 07:36 UTC, WizardCM commented
As we're partially breaking existing themes as part of 28 anyway, what if we just restructure this widget so that hacks like this aren't necessary any more? We've had to fight this particular element in various ways for ages.

2022-08-07 07:39 UTC, cg2121 commented
We can't restructure the widget, as it is a QT problem that it works this way, afaik.

2022-08-07 08:10 UTC, cg2121 commented
According to a bunch of forum posts, the only way to fix this without changing the qss would to create a delegate and override the paint event in the source tree, which I don't feel like doing. Just some dumb QT things.

2022-08-07 11:06 UTC, WizardCM commented
Ah, that's a bummer. Thanks for looking into it.

2022-08-07 11:41 UTC, SuslikV commented
The margins should be set in the .qss, not in the code.
Example, 3px from all sides:
```
SourceTree {
	margin: 3px;
}
```
At some point, you should decide either you using .qss or customizing the whole UI manually, in the code.

The padding works OK. Probably, you misunderstanding the box model of the widget. It is not known what the theme should look like (the author should say if the selection border wasn't intentional).

Also, please fix the "group"ed sign width (obviously, it is cut in Yami theme):
At least, like this:
```
SourceTreeSubItemCheckBox {
...
	min-width: 12px;
}
```

2022-08-07 12:20 UTC, SuslikV commented
Also, the string:
https://github.com/obsproject/obs-studio/blob/61e0d69779882fdbca2f38856237c7cd0bc4ca86/UI/data/themes/Yami.qss#L184
do nothing. It is seems to be leftover from the attempt to round the background color from the _Set Color_, isn't?

If so, then the:
```
*[bgColor="1"]
{
	border-radius: 4px;
}
```
may help (should be set for all 8 colors)

If not - the string can be removed (only Acri theme uses border here, and the style isn't preserved on theme change, for me at least).

2022-08-13 08:27 UTC, Warchamp7 approved these changes
Seems like the lesser of all evils for fixing this.

Pending code review I am fine with this being fixed.

2022-08-14 00:52 UTC, cg2121 commented
Fixed merge conflicts and restored the padding in the scene tree.

2022-08-15 19:21 UTC, GeorgesStavracas commented
Can source rows not lose their rounded corners? Can the scene list not lose its current padding?

2022-08-15 21:28 UTC, GeorgesStavracas commented
Apparently the hardcoded heights do not scale on DPI changes.

2022-08-18 07:29 UTC, Warchamp7 requested changes
We'll need to find a different approach that doesn't involve hardcoding height, so as not to break due to DPI scaling

2022-08-18 13:21 UTC, cg2121 commented
@GeorgesStavracas could you post a screenshot of what they look like under high dpi?

2022-08-18 21:31 UTC, cg2121 commented
I finally figured out a way of doing this without hardcoding the heights.

@GeorgesStavracas could you confirm it works with different dpis?

2022-08-24 17:44 UTC, cg2121 commented
Fixed merge commits.

2022-08-24 21:52 UTC, RytoEX commented
Here's how this PR currently looks on my laptop screen, which uses a 125% custom scaling factor.

![image](https://user-images.githubusercontent.com/624931/186530112-521d5bf1-72b5-49a7-924b-7799ce220782.png)

2022-08-24 23:47 UTC, GeorgesStavracas commented
Thanks @RytoEX, this looks good to me now - I wonder if the QSS changes here affect the menu style though, @cg2121 could you confirm menus still have the same style as of lists?

2022-08-25 01:55 UTC, Warchamp7 approved these changes

2022-08-25 02:39 UTC, cg2121 commented
@GeorgesStavracas the menu is styled correctly.

![Screenshot from 2022-08-24 21-38-18](https://user-images.githubusercontent.com/19962531/186561742-7dae097b-59c8-4c7a-a35b-a419702adb39.png)

2022-08-25 03:34 UTC, RytoEX commented
What was the purpose of this change after an approval was given? It looks like some stylistic preference rather than a functional change, so it _shouldn't affect anything, unless there's some importance to the order of identifiers here. At minimum, please point out that you pushed a change and what it was for so we don't miss the fact that a change was pushed after approval, so that we can ascertain if we need to retest or re-review.

https://github.com/obsproject/obs-studio/compare/2ae773a39ecf328c1db79f873450e81aeec7a430..76e8c3da14468c480afcfd9326b9bf85642183ef

2022-08-25 04:36 UTC, cg2121 commented
It was because of a bad rebase, as I didn't realize a line was removed.

2022-08-25 04:44 UTC, RytoEX commented
> It was because of a bad rebase, as I didn't realize a line was removed.

Ah, I see. Some lines were reordering, some were adding in the accidentally removed lines.

2022-08-27 23:45 UTC, merged

2022-08-28 07:24 UTC, SuslikV commented on UI/source-tree.hpp
> +class SourceTreeItem : public QFrame {
Changing the UI code after the release candidate issued is bad practice.