Fix resource leak v4l2 output
obsproject/obs-studio pull request #7358
Opened 2022-09-12 13:21 UTC by shoffmeister

### Description

Fix resource leak occurring on error path in Linux v4l2-output.

### Motivation and Context

Resource leaks generally are to be avoided.

### How Has This Been Tested?

Manual code review.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-09-12 16:40 UTC, RytoEX requested changes
Per our [Contributing guildelines](https://github.com/obsproject/obs-studio/blob/b1c65af2b1c2e7c3554efb0578ca92fd64c4519c/CONTRIBUTING.rst), please make these changes:
1. Use the correct commit prefix ("linux-v4l2: ").
2. Write commit message subjects in imperative mood (begin commit message subjects with a verb).

2022-09-12 18:33 UTC, shoffmeister commented
Many thanks for the feedback; I have adjusted the commit messages as requested.

2022-09-13 01:37 UTC, kkartaltepe approved these changes
Looks good to me, thanks.

2022-09-13 17:34 UTC, RytoEX approved these changes
Commit messages look good now. Deferring functional review to @kkartaltepe , who has approved.

2022-09-17 11:38 UTC, norihiro commented on plugins/linux-v4l2/v4l2-output.c
> +	fclose(fp);
When `fp` is NULL, `fclose` should not be called.
```suggestion
	if (fp)
		fclose(fp);
```

2022-09-17 23:14 UTC, merged

2022-09-17 23:14 UTC, WizardCM commented
Was this leak introduced in 28, or is it a longer-standing bug?

2022-09-17 23:45 UTC, kkartaltepe commented
Looks like the FD leak was there since the original commit.