UI: Fix in Light theme
obsproject/obs-studio pull request #7406
Opened 2022-09-19 13:20 UTC by shiina424

### Description

Scene Name Labels and T-Bar in Studio mode are not visible in the Light theme.
If this is incorrect, we would appreciate it if you could correct it.

Before
![Before](https://user-images.githubusercontent.com/24505855/191026601-87186759-5078-4c2c-9356-d34c45958ae8.png)

After
![After](https://user-images.githubusercontent.com/24505855/191026616-694bed2f-7155-4e49-8e35-29a7a9e35682.png)

### Motivation and Context

I want displayed correctly.

### How Has This Been Tested?

I changed the qss file and tested it.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-09-19 20:56 UTC, Warchamp7 requested changes
Please use the palette values where it makes sense, or when it aligns with the existing theme definitions.

In this case, the `text` palette color should be used for both of these as the labels are normal text, and the existing slider handles also use it

https://github.com/obsproject/obs-studio/blob/a90dc8ef2596e8f425841dcb2bb6fabf7b1423b1/UI/data/themes/Light.qss#L831-L832

2022-09-21 16:33 UTC, RytoEX approved these changes
Confirmed that the current changes fix the Light theme as described.

2022-09-21 16:40 UTC, RytoEX commented
Though, ideally I would like the commit message to be a bit more descriptive about what is being fixed.

2022-09-21 17:17 UTC, Warchamp7 approved these changes

2022-09-21 17:49 UTC, merged