obs-filters: Warn when NVIDIA FX needs update & Update to v0.7.1 Video SDK
obsproject/obs-studio pull request #7466
Opened 2022-09-25 19:23 UTC by pkviet

### Description
This PR consists in two things:

1. Trying to mitigate an issue with NVIDIA Video & Audio FX sdks (which arises when updating one sdk and not the other).
2. Support v0.7.1.0+ Video FX sdk which improves Background Removal Filter by adding temporal processing.

### Motivation and Context

1. Context of the bug we are trying to mitigate: the NVIDIA Audio & Video Effects redistributable have been very recently updated (end of September 2022).
This can occasion bugs with obs-studio because the two redistributable rely on the same set of dependencies.
When one redistributable is more recent than the other, there can be a 'dll hell' with one of the two FX dll
being prevented from loading because the dependencies load but are the wrong ones for the other FX.
This is something which can not be solved on obs side but must be fixed by NVIDIA or the user.

- On the user side, the solution is to always upgrade both Video and Audio Effects redistributable at the same time. This is rendered a bit difficult because the versions of both SDKs have different numbers.
- On NVIDA side, an installer combining both Video & Audio FX would be one solution. Another would be to bundle the FX dlls with the GPU drivers.
On obs-studio side, we have implemented a detection of the dll versions and if they don't match a warning is issued in the Properties window of the filter.
Additionally the warning is logged.

2. Since Video Effects sdk v 0.7.0+, a major improvement is 'temporal processing' instead of a mere intraframe AI processing. This can improve the quality of the Background Removal filter. There is less flickering for instance.
We have added the capability to do temporal processing. But this will require the user to update to the latest sdk (as of Sept. 25). 

### How Has This Been Tested?
This was tested with an RTX 3070 FE with both last SDK and previous one.
All the Audio and Video FXs work fine.
This was also tested with another GPU, which can't be disclosed at this time.
The redistributables can be found [here](https://www.nvidia.com/en-us/geforce/broadcasting/broadcast-sdk/resources/).
The audio files are provided by NVIDIA in their sdks.
To demo the dereverb FX, I have dramatized the effect by inserting a reverb vst in obs.

1. Audio FX:
   a. Denoiser (NVIDIA demo file played in obs + noise reduction filter with NVIDIA FX set to noise reduction): 

https://user-images.githubusercontent.com/9283407/192160933-8c1602dd-d308-4590-8318-4b24ae9efb5c.mp4

   b. Dereverb (NVIDIA demo file played in obs + reverb vst + noise reduction filter with NVIDIA FX set to dereverb): 

https://user-images.githubusercontent.com/9283407/192160936-52951685-e1b3-48a9-ba94-583ccc7a80b6.mp4

   c. Dereverb + Denoiser (NVIDIA demo file played in obs + reverb vst + noise reduction filter with NVIDIA FX set to dereverb+denoiser): 

https://user-images.githubusercontent.com/9283407/192160920-29d6e4a0-77af-402c-af9d-9d0203ae44a4.mp4

2. Video FX (Background Removal filter):

We checked that the filter still works after the changes in this PR with various types of sources.

- Browser-source:
![obs64_2022-09-25_20-35-26](https://user-images.githubusercontent.com/9283407/192161026-3eca3c43-d0ad-4999-a9ba-de5a263e194e.png)

- Video source:
![obs64_2022-09-25_20-40-52](https://user-images.githubusercontent.com/9283407/192161032-48b08abc-46ae-41df-82a2-75ff411bcd68.png)

- Still image:
![obs64_2022-09-25_20-35-40](https://user-images.githubusercontent.com/9283407/192161037-fd7e9b3b-cc19-44d0-b102-65b6ad530e7a.png)

- webcam (not shown).

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-11-02 19:37 UTC, pkviet commented
Fixes issue #7369

2022-11-02 22:45 UTC, RytoEX requested changes
Just a nit.

2022-11-02 22:45 UTC, RytoEX commented on plugins/obs-filters/nvidia-greenscreen-filter.c
> +     */
Nit: Fix indentation.

2022-11-03 13:45 UTC, pkviet commented on plugins/obs-filters/nvidia-greenscreen-filter.c
> +     */
fixed

2022-11-11 21:46 UTC, Fenrirthviti approved these changes

2022-11-11 22:47 UTC, RytoEX approved these changes

2022-11-11 22:47 UTC, merged

2023-01-12 06:26 UTC, sandr1x commented
Do I understand correctly that Nvidia Audio SDK is not necessary unless new features are needed?

2023-01-12 23:47 UTC, khaosmaou commented
This warning message shows up on 10XX series cards and older. There are no Audio SDK updates from Nvidia for cards of these generations. The warning message indicates something is wrong, but as RNNoise still works on my GTX 1080 with the latest drivers with no issue this message can be misleading. Installing the new SDK adds new options and makes the warning message disappear, but none of these new "features" are even supported on non-RTX cards and show as greyed out inside of OBS.

Seems like this warning should only show on 20XX series or newer cards, and only if there is an update available to the SDK to prevent users with older cards installing extra software that literally does nothing.

2023-01-23 10:30 UTC, max-programming commented
I have a GTX 1650 but this warning shows up and also the Noise Suppression filter simply just **doesn't work** It doesn't remove noise from my background as it did before