cmake: Fix FindGio.cmake
obsproject/obs-studio pull request #7531
Opened 2022-10-05 11:46 UTC by tgurr

Find actual `libgio-2.0.so` instead of `libgobject-2.0.so`.

### Description
Without this change CMake detects `libgobject-2.0.so` instead of the actual `libgio-2.0.so`
```
-- Checking for modules 'gio-2.0;gio-unix-2.0'
--   Found gio-2.0, version 2.74.0
--   Found gio-unix-2.0, version 2.74.0
-- Found Gio: /usr/x86_64-pc-linux-gnu/lib/libgobject-2.0.so
```

and later on fails the build ([obs-studio-28.0.3.log](https://github.com/obsproject/obs-studio/files/9715172/obs-studio-28.0.3.log)) with:

```
[ 48%] Linking C executable obs-x264-test
cd /var/tmp/paludis/build/media-video-obs-studio-28.0.3/work/build/plugins/obs-x264 && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/obs-x264-test.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-cc -march=native -O2 -pipe -Wl,-O1 -Wl,--as-needed "CMakeFiles/obs-x264-test.dir/obs-x264-test.c.o" "CMakeFiles/obs-x264-test.dir/__/__/deps/opts-parser/opts-parser.c.o" -o obs-x264-test  -Wl,-rpath,/var/tmp/paludis/build/media-video-obs-studio-28.0.3/work/build/libobs ../../libobs/libobs.so.28 
make[2]: Leaving directory '/var/tmp/paludis/build/media-video-obs-studio-28.0.3/work/build'
make[1]: Leaving directory '/var/tmp/paludis/build/media-video-obs-studio-28.0.3/work/build'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_bus_get_sync'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_get_unique_name'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_call'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_call_finish'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_cancellable_new'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_signal_subscribe'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_io_error_quark'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_cancellable_cancel'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_call_sync'
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: ../../libobs/libobs.so.28: undefined reference to `g_dbus_connection_signal_unsubscribe'
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/obs-x264/CMakeFiles/obs-x264-test.dir/build.make:117: plugins/obs-x264/obs-x264-test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1205: plugins/obs-x264/CMakeFiles/obs-x264-test.dir/all] Error 2
make: *** [Makefile:159: all] Error 2
```

With the change CMake instead detects the actual `libgio-2.0.so`

```
-- Checking for modules 'gio-2.0;gio-unix-2.0'
--   Found gio-2.0, version 2.74.0
--   Found gio-unix-2.0, version 2.74.0
-- Found Gio: /usr/x86_64-pc-linux-gnu/lib/libgio-2.0.so
```

and build succeeds.

```
# lddtree /usr/x86_64-pc-linux-gnu/lib/libobs.so.28
libobs.so.28 => /usr/x86_64-pc-linux-gnu/lib/libobs.so.28 (interpreter => none)
[...]
    libgio-2.0.so.0 => /usr/x86_64-pc-linux-gnu/lib/libgio-2.0.so.0
        libglib-2.0.so.0 => /usr/host/lib/libglib-2.0.so.0
            libpcre2-8.so.0 => /usr/host/lib/libpcre2-8.so.0
        libgobject-2.0.so.0 => /usr/host/lib/libgobject-2.0.so.0
            libffi.so.8 => /usr/host/lib/libffi.so.8
        libgmodule-2.0.so.0 => /usr/host/lib/libgmodule-2.0.so.0
        libmount.so.1 => /usr/host/lib/libmount.so.1
            libcryptsetup.so.12 => /usr/x86_64-pc-linux-gnu/lib/libcryptsetup.so.12
            libuuid.so.1 => /usr/x86_64-pc-linux-gnu/lib/libuuid.so.1
            libdevmapper.so.1.02 => /usr/x86_64-pc-linux-gnu/lib/libdevmapper.so.1.02
                libudev.so.1 => /usr/host/lib/libudev.so.1
            libargon2.so.1 => /usr/x86_64-pc-linux-gnu/lib/libargon2.so.1
            libjson-c.so.5 => /usr/x86_64-pc-linux-gnu/lib/libjson-c.so.5
            libblkid.so.1 => /usr/x86_64-pc-linux-gnu/lib/libblkid.so.1
[...]
```

### Motivation and Context
* Discussion at https://gitlab.exherbo.org/exherbo/media/-/merge_requests/1004#note_34384
* Fix build failure, explanation above.

### How Has This Been Tested?
Locally, Exherbo Linux, x86_64 as well as on our CI which failed before with the same error:
https://gitlab.exherbo.org/tgurr/media/-/jobs/50164 and built fine with the fix https://gitlab.exherbo.org/tgurr/media/-/jobs/50207.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2022-10-05 12:34 UTC, PatTheMav requested changes
This change is incomplete - the finder relies on `pkg-config` to find the libraries as present in the system and uses the result of that as library names and naming hints.

With this change the result of `pkg-config` is ignored, so if `pkg-config` yields "wrong" results, I'd like to know why that is and remove the entire codepath involving `pkg-config`.

2022-10-05 13:56 UTC, tgurr commented
> This change is incomplete - the finder relies on `pkg-config` to find the libraries as present in the system and uses the result of that as library names and naming hints.
> 
> With this change the result of `pkg-config` is ignored, so if `pkg-config` yields "wrong" results, I'd like to know why that is and remove the entire codepath involving `pkg-config`.

I'm by far no CMake expert and I have no idea what "the finder" is but this change fixes an actual build issue for us, afaik the code e.g. darktable uses looks pretty much the same in this regard: https://github.com/darktable-org/darktable/blob/master/cmake/modules/FindGIO.cmake#L18. Feel free to fix this "properly" and close this PR. If you need further details and/or if you want me to report a plain bugreport instead please advice.

2022-10-05 14:09 UTC, PatTheMav commented
I actually spoke to soon - by the look of the comments the results of the lookup via `pkg-config` is supposed to only yield directory hints, but not actual library names. I cannot comment on why that should be necessary, but from that POV this change is the correct one.

The "finder" is the CMake script that you modified.

2022-10-05 14:10 UTC, PatTheMav approved these changes
Fine from my POV - @tytan652 any objections re. other distros?

2022-10-05 14:40 UTC, tytan652 commented
The main issue here is that Exherbo seems to do things differently from other distros.

The architecture folder shoudl be inside the lib folder. Ubuntu has `lib/x86_64-linux-gnu`, Exherbo has something different.

2022-10-05 14:59 UTC, tytan652 reviewed
Exherbo doesn't seems to follow the FHS (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) when it comes to the `lib` folder.

Is the issue reproduce-able on other distro that follow FHS like Ubuntu, Fedora… ?

Because if the issue exist only on your distro, I don't think OBS CMake is where the issue relies.

And also the commit should indicate what it fixes at the first glance.

2022-10-05 16:30 UTC, tgurr commented
> Edit: So from my POV the distro has an issue not the CMake.

I really fail to see the need for throwing around false accusations and the actual connection to this problem at all. We're not doing anything that is not supported officially by the various build systems and its tools, we're not doing anything new and what doesn't work for other packages. It's not like our CMake and/or pkg-config doesn't work, please elaborate why you think there's an actual issue regarding our directory structure and give further details.

> And also the commit should indicate what it fixes at the first glance.

Updated hopefully to your liking.

2022-10-05 17:15 UTC, marv commented
> Because if the issue exist only on your distro, I don't think OBS CMake is where the issue relies.

Please have a look at some official `Find*` modules in the cmake repository for comparison, e.g.
https://github.com/Kitware/CMake/blob/master/Modules/FindEXPAT.cmake#L43
https://github.com/Kitware/CMake/blob/master/Modules/FindLibinput.cmake#L56
https://github.com/Kitware/CMake/blob/master/Modules/FindLibXslt.cmake#L67

The `<PKG>_LIBRARIES` variable that is set by the `pkg_check_modules` invocation is never used as potential `NAMES` in the `find_library` call, only `<PKG>_INCLUDE_DIRS`/`<PKG>_LIBRARY_DIRS` are used to give the subsequent `find_path`/`find_library` invocations hints where the headers and the library are located.
`<PKG>_LIBRARIES` contains all libraries that are listed in the `Libs:` and `Requires:` fields of the pkg-config file, for `gio-2.0.pc` this results in `gio-2.0;glib-2.0;gobject-2.0` (on any distribution) - using that information in `find_library(NAMES ...)` is semantically wrong since it suggests that `libgio-2.0` could also be named like any of the libraries it depends on

2022-10-05 17:55 UTC, tytan652 commented
Thanks for the explaination @marv.

So the finder CMake needs to be fixed.

2022-10-15 11:08 UTC, TimB87 commented
I pulled this patch for CRUX which fixes the build issue just fine, thanks @tgurr !

2022-12-05 19:22 UTC, merged