mac-capture: sort apps and windows
obsproject/obs-studio pull request #7690
Opened 2022-10-31 11:18 UTC by Colerar

### Description

Order application and window list in mac screen capture panel.

<img width="50%" alt="image" src="https://user-images.githubusercontent.com/62297254/198995177-ca6e2a79-2a35-43cd-8f7b-24efdf2bfc8d.png">

<img width="50%" alt="image" src="https://user-images.githubusercontent.com/62297254/198995298-a23db3d7-feeb-4b95-b3c7-ba0b3c98abc5.png">

### Motivation and Context

The list is now unordered, making it difficult to find the app or window you want to capture.

### How Has This Been Tested?

It is a small tweak, so I just run and see if it works.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

2022-10-31 15:27 UTC, PatTheMav reviewed
It's unfortunate this requires two loop iterations, especially as we throw away lots of entries in the default case. Usually you want the filtering happen before the sorting to minimise the amount of comparisons required to achieve the output.

2022-10-31 15:34 UTC, Colerar commented
Thanks for your advice! But I'm a newbie for objective-c. Actually, it's my first commit with obj-c. I'll try to do this, although maybe not as clear or idiomatic.

2022-11-05 22:54 UTC, PatTheMav approved these changes
Conceptually this seems fine given that the sorted arrays contain only pointers (so no unnecessary copies of data take place). Will check functionality tomorrow.

2022-11-05 23:11 UTC, jp9000 commented
Seems to be a case-sensitive sort. Should probably be case-insensitive.

2023-02-15 16:08 UTC, PatTheMav commented on plugins/mac-capture/mac-screen-capture.m
> +				[window.owningApplication.applicationName
Per Jim's comment, please add `options: NSCaseInsensitiveSearch` to the `compare` message.

2023-04-08 00:09 UTC, gxalpha requested changes
In addition to the comment above regarding case sensitivity, please fix the merge conflicts and squash the commits into one. Ideally, capitalize the first letter in the commit title after the prefix (`mac-capture: Sort apps and windows alphabetically`).

2023-06-04 11:11 UTC, merged