UI: Use main video on the virtual camera if program
obsproject/obs-studio pull request #7781
Opened 2022-11-15 09:09 UTC by tytan652

### Description

Fixes #7780

Depends on #7169

This change allows the virtual camera to really output what is in the program view, some plugin interract with this view but their changes does not appear on the virtual camera.

But now if the virtual camera is started with program the config dialog is disabled because we use the main view.
And so if another type (preview, source, scene) is set, the dialog prevents you to set program if the virtual camera is active.

![2022-11-15_10-07](https://user-images.githubusercontent.com/17492366/201877784-1f83b86c-2da3-47ff-8bdb-c3afbff0c525.png)

### Motivation and Context

The virtual camera shall show the program view and this is not case.

### How Has This Been Tested?

1. Install downstream keyer plugin
2. Add and enable a downstream keyer
3. Start virtual camera with program as type
4. Check output of virtual camera is the same as the main output of obs

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-11-15 09:15 UTC, tytan652 commented
I'm concerned on how some program would react if the virtual camera disappear and reappear on each virtualcam implementation.

2022-11-15 11:05 UTC, tt2468 commented
Perhaps instead we can instead show a warning in the dialog itself whenever a restart is required? `Pressing OK will restart virtual cam.`

2023-03-06 22:18 UTC, Warchamp7 commented
Let's leave this dialog always available and keep the dropdown options enabled. If the user swaps to/from Program and it requires a Virtual Cam restart, display an inline warning stating as such and apply the changes + perform the restart when they click Ok

2023-03-07 14:51 UTC, tytan652 commented
Made UI/UX changes, PR description updated.

2023-03-27 22:35 UTC, GeorgesStavracas commented
UI side approved :+1:

2023-05-06 23:55 UTC, WizardCM commented
Note to self: test on Windows and macOS to verify that the virtual cameras successfully restart in the allotted time, and don't cause third party apps to get confused.

2023-05-14 07:42 UTC, tytan652 commented
Rebased against #8900

2023-05-30 10:05 UTC, Lain-B requested changes
Looks good, just have one requested change and one "wish there was a better way" sort of comment. Feel free to ignore the latter if you wish.

Otherwise looks good!

2023-05-30 11:03 UTC, tytan652 commented on UI/window-basic-main.cpp
> +	QTimer::singleShot(1, this, &OBSBasic::RestartingVirtualCam);
> I'm guessing if you did this then there's not any other way that you were able to think of. Kind of wish there was another way though.

You can check [here](https://discord.com/channels/348973006581923840/940868766345084928/1082661897628815430) but I tried `QMetaObject::invokeMethod` but only `QTimer::singleShot` gave a result.

2023-05-30 12:32 UTC, tytan652 commented on UI/window-basic-main.cpp
> +		if (vcamConfig.type == 0) {
Added `VCamOutputType::Invalid`.

2023-05-30 23:16 UTC, merged