QSV Cleanups
obsproject/obs-studio pull request #8014
Opened 2023-01-07 02:48 UTC by kkartaltepe

### Description

Minor changes to remove the majority of the windows dependencies and windows specific references in common code.

### Motivation and Context

Removing unused headers and dead code is always a win, using common obs locks/more accurate names for variables is also nice. This also restores the presumed purpose of the "common_utils" collection of folders to provide common utilities to the other QSV supported platform. Finally it makes the work of implementing a linux/VAAPI build easier to review later.

### How Has This Been Tested?

Prayers to the github build bot.

### Types of changes

- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-01-31 03:32 UTC, kkartaltepe commented
Rebased on top of the warnings to errors changes.

2023-02-08 03:13 UTC, RytoEX requested changes
When referring to "Windows" the operating system, capitalize it as such.

Third commit message:
* replaces them platform -> replaces them with platform
* indpendent -> independent
* officially so its -> officially, so it's

Weirdly, with `m_bD3D9HACK` and `m_bUseTexAlloc` always being `true`, there are a lot of seemingly dead branches. Are those going to be utilized for later work?

In its commits, it was specifically stated that the "D3D9 hack" only applied to Windows 7. However, there appears to be a path where D3D11 _could have failed_ and QSV is attempts to init as D3D9 (the block after "D3D11 failed at this point."). Strangely, this logs that the surface is on SysMem, but there is a later code branch in InitParams:
```
	if (m_bUseD3D11 || m_bD3D9HACK)
		m_mfxEncParams.IOPattern = MFX_IOPATTERN_IN_VIDEO_MEMORY;
	else
		m_mfxEncParams.IOPattern = MFX_IOPATTERN_IN_SYSTEM_MEMORY;
```
This will seemingly always end up in the first branch, because `m_bD3D9HACK` is always `true` and never set to `false`. That's been that way since the commit that added the D3D9 allocator hack, so it's not new here, but if we can possibly get to the D3D09+SysMem init (I don't know what would cause this), then we may want to fix this at some point.

If we're removing the Win7 path, then perhaps we should just remove the entire D3D9 hack code path (manually revert the whole commit)? The separate D3D9 on Win8+ path from before the D3D9 hack commit _should_ be fine for systems that somehow have a D3D11 failure. If we want to put that off for a separate cleanup, that's fine with me.

Other than that and the individual review comments, this looks pretty straightforward.

2023-02-08 04:49 UTC, kkartaltepe commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +	m_bUseTexAlloc = (m_bUseD3D11 || m_bD3D9HACK);
It will be false on linux, and it makes the branches in platform agnostic code clearly platform agnostic.

2023-02-08 04:51 UTC, kkartaltepe commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +		//	(version.Major == 1 && version.Minor >= 8));
This and the following comment are for pre-existing code, I only removed the indentation after we removed the win8 branch. If you want I can clean up this up in the PR.

2023-02-08 04:59 UTC, kkartaltepe commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +		//	(version.Major == 1 && version.Minor >= 8));
There is kind of weird situation with useTexAlloc so I went ahead and cleaned these up too just to make it simpler.

2023-02-08 05:04 UTC, RytoEX commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +		//	(version.Major == 1 && version.Minor >= 8));
To clarify, the commented out code is what I was suggesting to remove. The actual descriptive comment can stay.

2023-02-08 05:05 UTC, RytoEX commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +	m_bUseTexAlloc = (m_bUseD3D11 || m_bD3D9HACK);
How would it be false on Linux right now in this file in this function? The two bools used to define it are defined right above it.

2023-02-08 05:08 UTC, kkartaltepe commented
> Weirdly, with m_bD3D9HACK and m_bUseTexAlloc always being true, there are a lot of seemingly dead branches. Are those going to be utilized for later work?

Yea we will use the existing non-texalloc paths on linux.

> If we're removing the Win7 path, then perhaps we should just remove the entire D3D9 hack code path (manually revert the whole commit)? The separate D3D9 on Win8+ path from before the D3D9 hack commit should be fine for systems that somehow have a D3D11 failure. If we want to put that off for a separate cleanup, that's fine with me.

Yea I think just removing all of the d3d9 code should probably be done since we dropped win8 support. This is fairly straightforward as its mostly deleting `common_directx9.cpp/h` and some branches. But I also wanted to try and keep this PR as small as possible for any reviewer's sake.

> Strangely, this logs that the surface is on SysMem, but there is a later code branch in InitParams:

I didnt try to understand the directx9 implementation, so whether it makes sense to label it sysmem is unclear to me.

2023-02-08 05:10 UTC, kkartaltepe commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +		//	(version.Major == 1 && version.Minor >= 8));
The descriptive comment is no longer applicable.

2023-02-08 05:11 UTC, RytoEX commented
> > Weirdly, with m_bD3D9HACK and m_bUseTexAlloc always being true, there are a lot of seemingly dead branches. Are those going to be utilized for later work?
> 
> Yea we will use the existing non-texalloc paths on linux.

Got it.

> > If we're removing the Win7 path, then perhaps we should just remove the entire D3D9 hack code path (manually revert the whole commit)? The separate D3D9 on Win8+ path from before the D3D9 hack commit should be fine for systems that somehow have a D3D11 failure. If we want to put that off for a separate cleanup, that's fine with me.
> 
> Yea I think just removing all of the d3d9 code should probably be done since we dropped win8 support. This is fairly straightforward as its mostly deleting `common_directx9.cpp/h` and some branches. But I also wanted to try and keep this PR as small as possible for any reviewer's sake.

Fair enough.

> > Strangely, this logs that the surface is on SysMem, but there is a later code branch in InitParams:
> 
> I didnt try to understand the directx9 implementation, so whether it makes sense to label it sysmem is unclear to me.

I'll file that away under "research later".

2023-02-08 05:11 UTC, RytoEX commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +		//	(version.Major == 1 && version.Minor >= 8));
Fair enough. I hadn't checked the latest push before replying to this thread.

2023-02-08 05:28 UTC, kkartaltepe commented
For the usage on linux of the non-texture alloc path you can see https://github.com/kkartaltepe/obs-studio/tree/qsv-linux-pt2

2023-03-09 20:06 UTC, RytoEX commented
Revisiting this, I get an encoder start failure on Windows 11.
```
[qsv encoder: 'msdk_impl'] Invalid session or MemId handle (MFX_ERR_INVALID_HANDLE)
```

2023-03-10 00:28 UTC, kkartaltepe commented
> Revisiting this, I get an encoder start failure on Windows 11.
> 
> ```
> [qsv encoder: 'msdk_impl'] Invalid session or MemId handle (MFX_ERR_INVALID_HANDLE)
> ```

It looks like i missed setting `m_bUseD3D11 = true`, you can change that yourside to test or ill update the commits later today.

2023-03-11 23:14 UTC, kkartaltepe commented
Fixed that up now.

2023-03-20 21:18 UTC, RytoEX requested changes
One nit, but otherwise looks okay to me. My recording tests worked this time.

2023-03-20 21:18 UTC, RytoEX commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +	// We don't check what was valid or invalid here, just try changing lower power.
nit: lower power -> LowPower

2023-03-21 04:04 UTC, kkartaltepe commented on plugins/obs-qsv11/QSV_Encoder_Internal.cpp
> +	// We don't check what was valid or invalid here, just try changing lower power.
done

2023-03-22 22:45 UTC, RytoEX approved these changes
Looks good to me.

2023-07-05 23:52 UTC, merged