win-capture: Add compatibility notices
obsproject/obs-studio pull request #8080
Opened 2023-01-18 01:42 UTC by derrod

### Description

Adds text warnings with optional URLs to window and game capture to notify users about incompatibilities using the new text labels introduced in #5160

ToDo:
- [ ] Write JSON Schema and validate it on CI
- [ ] Set up server side stuff
- [ ] Add actual useful entries

Screenshot:
![2023-01-18_01-43-09_jlHKvV](https://user-images.githubusercontent.com/3123295/213059983-6678ab0b-1f1b-41d8-a30f-483cba505d70.png)

### Motivation and Context

Provide in-app guidance for users when things don't work in case of known compatibility issues.

### How Has This Been Tested?

Mucked about locally.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-01-19 07:47 UTC, derrod commented
Based on off-chain feedback translation is a potential issue.

My idea would be:
- Add `translation_key` and `title` properties to JSON
- Provide translatable generic messages, like `%title% may require OBS to be run as admin to use Game Capture`
- Provide translatable specified message, e.g. for CSGO and Minecraft
- If the translation string exists, attempt to replace variables, i.e. `%title%` in string => `title` from JSON
- If no translation key exists, e.g. outdated OBS version or new entry where generic messages couldn't be used, use message from JSON instead

2023-02-05 14:46 UTC, derrod commented
Rebased on master with the following changes:

- Remove labels (as discussed off-chain yesterday)
- Added explanation of severity labels to schema
- Squashed commits

2023-02-05 15:24 UTC, Gol-D-Ace commented
Gave this a try and it looks like if no application is selected it defaults to the CSGO message for me.
![Screenshot_20230205-162221-489](https://user-images.githubusercontent.com/5058319/216828309-f12f8941-e2b9-4b6e-a20f-cd18ae985e84.png)

2023-02-05 15:49 UTC, derrod commented
Yeah I didn't consider the "any" case. I fixed that now (Also added GTA:SA and SAMP entries based on Discord discussion).

2023-02-20 23:11 UTC, Warchamp7 approved these changes

2023-02-26 01:07 UTC, RytoEX requested changes

2023-02-26 01:07 UTC, RytoEX commented on plugins/win-capture/data/locale/en-US.ini
> +Compatibility.Application.CSGO="CSGO may require the <code>--allow_third_party_software</code> launch option to use Game Capture"
```suggestion
Compatibility.Application.CSGO="CS:GO may require the <code>--allow_third_party_software</code> launch option to use Game Capture"
```

2023-02-26 01:07 UTC, RytoEX commented on plugins/win-capture/data/locale/en-US.ini
> +Compatibility.Application.Minecraft="If you're having issues capturing Minecraft: Java Edition check our troubleshooting guide"
Sentence ending punctuation?

2023-02-26 01:07 UTC, RytoEX commented on plugins/win-capture/data/schema/compatibility-schema-v1.json
> +}
End with newline.

2023-02-26 01:07 UTC, RytoEX commented on plugins/win-capture/game-capture.c
> +	char *class, *exe, *title;
Declare these on separate lines.

2023-02-26 01:07 UTC, RytoEX commented on plugins/win-capture/plugin-main.c
> +	bfree(config_dir);
Free in reverse order of declaration.

2023-02-26 01:24 UTC, derrod commented on .github/workflows/compat-json.yml
> +    runs-on: [ubuntu-20.04]
No specific reason, this was just copied 1:1 from the rtmp-service schema checker.

2023-02-26 01:26 UTC, derrod commented on plugins/win-capture/data/compatibility.json
> +            "message": "Valorant may require OBS to be run as admin to use Game Capture.",
I do not have that game installed, I just added entries from https://obsproject.com/kb/game-capture-troubleshooting

2023-02-27 19:49 UTC, derrod commented on plugins/win-capture/plugin-main.c
> +#define WIN_CAPTURE_LOG_STRING "[win-capture plugin] "
This is just a straight copy from `rtmp-services`:

https://github.com/obsproject/obs-studio/blob/master/plugins/rtmp-services/rtmp-services-main.c#L21-L22

An example line would be
`20:47:45.242: [win-capture plugin] Remote update of URL "https://obsproject.com/obs2_update/win-capture/v1/package.json" failed: The requested URL returned error: 404`

2023-02-27 20:06 UTC, RytoEX commented on plugins/win-capture/plugin-main.c
> +#define WIN_CAPTURE_LOG_STRING "[win-capture plugin] "
Weird. If it's only used in that one place and is based on an existing pattern, then I'm not as concerned.

2023-03-02 13:24 UTC, derrod commented
Based on Flaeri's feedback:
- Removed Valorant (seems to be no longer reuqired, possibly never was)
- Added generic Electron entries to BitBlt Window Capture and Game Capture
  + Window Capture will default to WGC for Electron apps, so only a "notice" severity
  + For Game Capture this affects titles such as Vampire Survivors that are built using Electron. See https://steamdb.info/tech/SDK/Greenworks/ for a list of many affected titles

2023-03-02 21:19 UTC, RytoEX approved these changes
Looks okay to me. I think this is a good first attempt at trying to give users some assistance to resolve issues on their own without having to come to our support channels.

2023-03-07 21:03 UTC, merged