Update CONTRIBUTING.rst
obsproject/obs-studio pull request #8108
Opened 2023-01-21 11:44 UTC by Ishaan2053

### Description
- I have Improved the ['Contribution  Guidelines'](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst) page by adding alternate texts to all the links, rephrasing some text and polishing the document.

### Motivation and Context
 - I have updated the document for improved appearance and readability. Also, a cleaner appearance makes it easier for people to understand the guidelines. 
 -  Good documentation always helps 🙂

### How Has This Been Tested?
- NA

### Types of changes:
- Documentation

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-01-22 01:42 UTC, RytoEX requested changes

2023-01-22 16:53 UTC, Ishaan2053 commented on CONTRIBUTING.rst
> +  So for example, if you are modifying the obs-ffmpeg plugin, write in this format::
Fixed👍🏼

2023-01-22 16:54 UTC, Ishaan2053 commented on CONTRIBUTING.rst
> +- `Developer/API Documentation <https://obsproject.com/docs>`_.
Updated that as well👍🏼

2023-02-15 18:01 UTC, Fenrirthviti commented
While I think our contributing guidelines are indeed due for an update, this PR contains nothing of substance and is only formatting. Thank you for the submission, but we will decline this in favor of something more substantial.

2023-02-15 18:01 UTC, closed without merging