obs-filters: Improve upward compressor & expander fix
obsproject/obs-studio pull request #8121
Opened 2023-01-22 19:48 UTC by pkviet

### Description
This is a series of improvements for the upward compressor co-authored by @norihiro and @pkviet :
- the hard knee is replaced by a soft knee (pkv);
- gain is made to be continuous even at -60 dB (kamae);
- attack and release were swapped for compressor instead of following the expander (kamae).
This should solve:
#8052 

Furthermore, the hard setting of gain to 0 dB above threshold for the expander was removed.
This should solve:
#8030 

### Motivation and Context
Fix bugs for expander and upward compressor.
Enhance the upward compressor.

### How Has This Been Tested?
Tested to work by @norihiro : details [here](https://github.com/pkviet/obs-studio/pull/84) and @pkviet 

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-01-22 19:55 UTC, RytoEX commented
If this fixes a GitHub Issue, please use [closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in the PR description.

2023-01-23 01:49 UTC, norihiro commented
The knee is a new feature. I want to suggest to separate it at the end of the commit so that other fix commits can be cherry-picked to 29.0.1.

2023-01-23 13:37 UTC, norihiro commented
I tested the knee feature. The kee looks working ok.

Input is a 440 Hz sine wave and sweeps the level using the `Gain` filter and changes the knee settings for 0, 10, and 20. Figure below shows the input level vs. the output level reading the level meter by eyes.
![upwcomp-inout-level-knee](https://user-images.githubusercontent.com/780600/214052713-c1f356b7-76f3-454c-9736-33e818c299b2.png)

2023-01-25 01:32 UTC, RytoEX commented
It seems like the first three commits here are bug fixes, while the fourth commit is a new feature. Is that correct? We may not make this in for 29.0.1, but we can reevaluate the bug fix commits for a potential 29.0.2, if needed.

2023-01-25 06:59 UTC, FelikZ commented
can confirm that this PR fixes #8030 (for my usecase)

2023-01-26 18:22 UTC, RytoEX requested changes

2023-01-26 18:22 UTC, RytoEX commented on plugins/obs-filters/data/locale/en-US.ini
> +expander.Knee.Width="Knee Width"
Nit: Expander

2023-01-26 18:38 UTC, pkviet commented on plugins/obs-filters/data/locale/en-US.ini
> +expander.Knee.Width="Knee Width"
fixed

2023-01-27 07:23 UTC, merged