Dimidium Totius (in preparation for PipeWire camera and audio, part 1)
obsproject/obs-studio pull request #8153
Opened 2023-01-26 12:07 UTC by GeorgesStavracas

### Description

Various cleanups in preparation for making `linux-pipewire` handle cameras and audio. This pull request contains the "easy" half of https://github.com/obsproject/obs-studio/pull/5614 and should not be controversial.

What is done here is: 

 * Clean up a leftover object when the plugin is unloaded
 * Massage some functions to receive more parameters...
 * ... which then allow cleaning up the internal struct
 * Rename a struct to better represent its scope
 * Shuffle code around

### Motivation and Context

Prepare the `linux-pipewire` plugin to receive support for cameras and audio. This is also an effort to get https://github.com/obsproject/obs-studio/pull/5614 unstuck.

### How Has This Been Tested?

 - Run OBS Studio on Linux + Wayland, and notice it continues to work

### Types of changes

 - Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-01-29 00:22 UTC, kkartaltepe approved these changes
looks fine and works on my machine.

2023-02-10 04:07 UTC, RytoEX requested changes

2023-02-10 16:59 UTC, RytoEX requested changes
Commit message nits:

https://github.com/obsproject/obs-studio/pull/8153/commits/22b641c43f319cc8fe95f40b792b703a686efeae
> Remove the pipewire_node field, and just create the stream directly
from the passed now.

Perhaps missing a word? I feel like something is amiss.

https://github.com/obsproject/obs-studio/pull/8153/commits/334927ecf6f12fd78f30708e39ca134ee738b7a1
* existance -> existence
* prespective -> perspective
* screencast -?> ScreenCast

https://github.com/obsproject/obs-studio/pull/8153/commits/3a761482de6ac6128f43dabe4ae54d7a9948db71
* ying -> yin

Other than nits, and the previous review, I really don't have any items I'm worried about.

2023-02-12 20:04 UTC, GeorgesStavracas commented on plugins/linux-pipewire/pipewire.c
> +	UNUSED_PARAMETER(seq);
Good catch. Fixed.

2023-02-12 20:04 UTC, GeorgesStavracas commented
Thanks for the review. The commit messages were adjusted.

2023-02-13 15:28 UTC, merged