UI: Add frontend copy paste functions
obsproject/obs-studio pull request #8286
Opened 2023-02-17 14:14 UTC by exeldro

### Description
Add frontend copy paste functions
```
void obs_frontend_copy_sceneitem(obs_sceneitem_t *item);
bool obs_frontend_can_paste_sceneitem(bool duplicate);
void obs_frontend_paste_sceneitem(obs_scene_t *scene, bool duplicate);
```

### Motivation and Context
Allow users from the vertical plugin to copy and paste sources from and to the main canvas

### How Has This Been Tested?
On windows with changes to the vertical plugin

### Types of changes
 - New feature (non-breaking change which adds functionality) 
 
### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-06-20 16:15 UTC, CodeYan01 commented on UI/obs-frontend-api/obs-frontend-api.h
> +EXPORT void obs_frontend_paste_sceneitem(obs_scene_t *scene, bool duplicate);
Please add these to the docs, preferably with `:versionadded:` with a placeholder version number (that can be updated once the PR is added to a project milestone)

2025-08-08 20:26 UTC, PatTheMav requested changes
I'll have to give this a test locally but at first glance this seems fine and I also agree that it's preferable for 3rd party code to use these built-in functions to duplicate or alias existing sources.

2025-08-08 20:26 UTC, PatTheMav commented on frontend/widgets/OBSBasic.hpp
> +	void PasteSceneItem(OBSScene scene, bool duplicate);
```suggestion
	void copySceneItem(OBSSceneItem item);
	bool canPasteSceneItem(bool duplicate);
	void pasteSceneItem(OBSScene scene, bool duplicate);
```
For any additions to code after the frontend reorganisation we prefer to use common "camelCase" for C++ methods and leave "CapitalCase" to class names (`enum class` names would probably also be fine).

2025-08-09 17:31 UTC, PatTheMav commented
Tested this locally and seemed to work just fine.

2025-08-16 18:44 UTC, exeldro commented
Switched methods to camelCase as requested

2025-09-25 12:54 UTC, PatTheMav commented on frontend/widgets/OBSBasic.cpp
> +	ui->actionPasteDup->setEnabled(canPasteSceneItem(true));
I'd probably prefer if this method does not return a contextless `true` or `false` but instead would be called like `getItemPasteType` that returns a `class enum` value:

* `OBS::ItemPasteType::Invalid`
* `OBS::ItemPasteType::Reference`
* `OBS::ItemPasteType::Duplicate`
* `OBS::ItemPasteType::Both`

You can `switch` over that return value and enable the controls accordingly.

IMO that would communicate the meaning of the return value explicitly and make the code path choices made based on that value more clear.

2025-12-18 02:19 UTC, RytoEX commented on frontend/widgets/OBSBasic.cpp
> +	ui->actionPasteDup->setEnabled(canPasteSceneItem(true));
@exeldro This feedback is unresolved.

2025-12-19 14:44 UTC, PatTheMav approved these changes

2026-02-26 18:25 UTC, exeldro commented
Rebased and fixed conflicts

2026-05-03 18:39 UTC, Warchamp7 commented
This is probably fine in the interim but we should really be making proper use of QMimeData in the UI.

2026-05-07 17:05 UTC, RytoEX requested changes

2026-05-07 17:05 UTC, RytoEX commented on docs/sphinx/reference-frontend-api.rst
> +   .. versionadded:: 32.0
Version added will need to be updated to 32.2. I can change this before merging if needed.

2026-05-07 17:05 UTC, RytoEX commented on frontend/widgets/OBSBasic_Clipboard.cpp
> +	OBSSource scene_source = obs_scene_get_source(scene);
```suggestion
	if (!scene || !clipboard.size()) {
		return;
	}
	OBSSource scene_source = obs_scene_get_source(scene);
```

2026-05-07 17:05 UTC, RytoEX commented on frontend/widgets/OBSBasic_Clipboard.cpp
> +		return OBS::ItemPasteType::Invalid;
```suggestion
	if (clipboard.empty()) {
		return OBS::ItemPasteType::Invalid;
	}
```

2026-05-07 17:05 UTC, RytoEX commented on frontend/widgets/OBSBasic_Clipboard.cpp
> +	}
```suggestion
		if (allowPastingDuplicate && obs_source_get_output_flags(strong) & OBS_SOURCE_DO_NOT_DUPLICATE) {
			allowPastingDuplicate = false;
		}
	}
```

2026-05-07 21:14 UTC, RytoEX requested changes

2026-05-07 21:14 UTC, RytoEX commented on frontend/widgets/OBSBasic_Clipboard.cpp
> +		return;
I either forgot to submit this, or GitHub had an issue earlier.

```suggestion
	if (!item) {
		return;
	}
```

2026-05-22 19:54 UTC, RytoEX approved these changes

2026-05-22 21:25 UTC, merged