UI: Add ability to re-color icons
obsproject/obs-studio pull request #8351
Opened 2023-02-26 07:39 UTC by cg2121

### Description
This adds the ability to change icon colors by qss.

### Motivation and Context
@Warchamp7 really wants this feature because it prevents having to maintain several different sets of icons. It currently doesn't work with combobox or spinbox up/down icons.

### How Has This Been Tested?
Changed icon color in qss and made sure they were the correct color.

### Types of changes
- New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-03-04 23:18 UTC, tytan652 requested changes

2023-03-04 23:18 UTC, tytan652 commented on UI/obs-frontend-api/obs-frontend-api.h
> +
Needs documentation.

It also feels out of scope without context.

2023-03-04 23:24 UTC, WizardCM commented
The more I read through this, the less maintainable it looks. While the implementation seems alright enough, it's a lot of code for something that _should_ be relatively simple, and requires extra consideration whenever a new icon is added & styled. Additionally, if Qt ever does add proper SVG support, this would have to be cleaned up in reverse.

While I like the idea of this feature, I don't think it's a good idea for us to implement it on our side. Ideally, we push for Qt to implement proper `currentColor` support on their end.

2023-03-05 01:04 UTC, cg2121 commented
After thinking about it, this shouldn't be something we should be doing, as Qt should be doing it. Just too much code. This is an old branch that I had laying around, as mostly experimental, so I don't really care much about it anyway.

2023-03-05 01:04 UTC, closed without merging