UI, libobs: Fix not handled in switch warnings
obsproject/obs-studio pull request #8357
Opened 2023-02-27 05:47 UTC by cg2121

### Description
These warnings were being spit out by GCC on Linux.

### Motivation and Context
Less spammy compiling

### How Has This Been Tested?
Compiled OBS

### Types of changes
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-02-27 06:57 UTC, tytan652 requested changes

2023-02-27 06:57 UTC, tytan652 commented on UI/qt-wrappers.cpp
> +		break;
```suggestion
	default:
		success = false;
		break;
```

2023-02-27 06:57 UTC, tytan652 commented on UI/qt-wrappers.cpp
> +		native = QGuiApplication::platformNativeInterface();
Adding `{}` normally avoids having to create the pointer outside of the switch.

```c++
#ifdef ENABLE_WAYLAND
	case OBS_NIX_PLATFORM_WAYLAND:
	{
		QPlatformNativeInterface *native =
			QGuiApplication::platformNativeInterface();
		gswindow.display =
			native->nativeResourceForWindow("surface", window);
		success = gswindow.display != nullptr;
		break;
	}
#endif
```

2023-02-27 09:50 UTC, cg2121 commented on UI/qt-wrappers.cpp
> +		break;
Fixed

2023-02-28 08:42 UTC, tytan652 requested changes

2023-02-28 08:42 UTC, tytan652 commented on UI/qt-wrappers.cpp
> +	} break;
Why the `break` is outside ?

2023-03-21 18:22 UTC, cg2121 commented on UI/qt-wrappers.cpp
> +	} break;
Fixed

2023-03-25 23:47 UTC, merged