Support MSVC standard conforming mode
obsproject/obs-studio pull request #8377
Opened 2023-02-28 18:13 UTC by derrod

### Description

Enable compiling OBS with `/permissive- /Zc:__cplusplus /Zc:preprocessor /std:c17`.

This is the bare-minimum to get OBS (minus `enc-amf`) to compile and run with these options.

See: https://learn.microsoft.com/en-us/cpp/preprocessor/preprocessor-experimental-overview

Draft because I'm not 100% happy/sure about some of these. 

### Motivation and Context

Want to not use `/permissive-` anymore and use more consistent build options with *nix.

### How Has This Been Tested?

Build and ran OBS.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)
- Code cleanup (non-breaking change which makes code smaller or more readable)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-03-01 15:16 UTC, RytoEX requested changes
The changes overall looked fine to me. We are still shipping minor fixes for enc-amf for now, particularly for build fixes (such as `/utf-8`), so feel free to PR those changes on that repo. Please move the `cmake: Enable stricter MSVC compiler options` commit to be last so that each commit can compile (assuming the changes work with both compiler configurations).

2023-03-01 16:32 UTC, derrod commented
In that case would you mind merging https://github.com/obsproject/obs-amd-encoder/pull/435 so that I can rebase make this PR update the submodule to keep a working build?

2023-03-01 18:45 UTC, notr1ch approved these changes
LGTM.

2023-03-01 18:58 UTC, RytoEX approved these changes

2023-03-01 18:59 UTC, derrod commented
Ignore that force push, the changes are exactly the same, I just found a typo in the first commit message that I *needed* to fix.

2023-03-01 19:39 UTC, merged

2023-04-06 19:04 UTC, SetoKaiba commented
https://youtrack.jetbrains.com/issue/CPP-32997/Reload-CMake-Project-problem-in-CLion
Hi, when I use CLion to open the project. It won't reload the project. 
I can reload the project with /std:c17 removed from CompilerConfig.cmake.

```
Command line error D8016 : '/std:c17' and '/std:c++17' command-line options are incompatible
```

2023-04-07 02:21 UTC, SetoKaiba commented
@derrod Any idea on this? Is it a bug of CLion? Or the param shouldn't be here?

2023-04-07 13:26 UTC, derrod commented
I have no idea. I haven't used CLion on Windows for OBS.

2023-04-07 13:29 UTC, SetoKaiba commented
In windows, /std:c17 and /std:c++17 is incompatible. Maybe the /std:c17 should be only applied to the project that need /std:c17. Previously, there's no /std:c17 in the CompilerConfig.cmake.

2023-04-07 15:39 UTC, RytoEX commented
> In windows, /std:c17 and /std:c++17 is incompatible. Maybe the /std:c17 should be only applied to the project that need /std:c17. Previously, there's no /std:c17 in the CompilerConfig.cmake. And it works for CLion.

It works fine for MSVC, which is the compiler that we support on Windows. That said, we have made an adjustment in #8694 to use CMake flags to set the C standard instead of using a compiler flag directly.

2023-04-07 19:51 UTC, SetoKaiba commented
I tried #8684. It fixes the issue. Thank you.