rtmp-services: Add Mavenx.gg
obsproject/obs-studio pull request #8385
Opened 2023-03-01 17:03 UTC by MuhammadAyazRao

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2023-03-01 17:08 UTC, gxalpha requested changes
Please fill out the Pull Request template instead of deleting it.
Please use 4 spaces instead of a tab.

2023-03-01 17:09 UTC, RytoEX requested changes
Please fill out the PR template.

2023-03-01 17:09 UTC, RytoEX commented on plugins/rtmp-services/data/services.json
> +	},
Do not change whitespace from spaces to tabs.

2023-03-01 17:09 UTC, RytoEX commented on plugins/rtmp-services/data/services.json
> +		"more_info_link": "https://mavenx.gg",
Per our Services Submission Guidelines, `more_info_link` is meant to be a:
> Link that provides additional info about the service, presented in the UI as a button next to the services dropdown.

Linking to the homepage seems too vague/broad.

2023-03-02 09:38 UTC, MuhammadAyazRao commented
> ### Description
Our website offers a unique platform for gamers to showcase their skills and interact with their fans. With a vast library of games and a passionate community, we provide an immersive gaming experience for everyone. Whether you are a casual gamer, a professional player, or a streamer, our website has something for everyone. From the latest AAA titles to indie games, you can find a wide variety of games to enjoy. Our website is designed to make streaming easy and accessible. With our user-friendly interface and powerful streaming tools, you can easily stream your gameplay to thousands of viewers worldwide. So come join our community of gamers and start streaming today. Whether you are a seasoned veteran or a newbie, there is always something new to discover on our game streaming website.

> ### Motivation and Context
Our website offers a unique platform for gamers to showcase their skills and interact with their fans. With a vast library of games and a passionate community, we provide an immersive gaming experience for everyone. Whether you are a casual gamer, a professional player, or a streamer, our website has something for everyone. From the latest AAA titles to indie games, you can find a wide variety of games to enjoy. Our website is designed to make streaming easy and accessible. With our user-friendly interface and powerful streaming tools, you can easily stream your gameplay to thousands of viewers worldwide. So come join our community of gamers and start streaming today. Whether you are a seasoned veteran or a newbie, there is always something new to discover on our game streaming website.
> ### How Has This Been Tested?
We update the services.json file on our local system with OBS Services.json file and it is working perfectly fine on our local system.
> ### Types of changes
> ### Checklist:
> * [ ]  My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
> * [x]  I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
> * [x]  My code is not on the master branch.
> * [x]  The code has been tested.
> * [x]  All commit messages are properly formatted and commits squashed where appropriate.
> * [ ]  I have included updates to all appropriate documentation.

2023-03-02 09:39 UTC, MuhammadAyazRao commented
> Please fill out the PR template.

Where to add PR template ?

2023-03-02 17:50 UTC, Fenrirthviti commented
Thank you for the submission, but after review we have found that your service does not meet the minimum requirements per our [service submission guidelines](https://obsproject.com/wiki/Service-Submission-Guidelines). We found many site errors, as well as lacking adoption of the service.

Once the service has matured and more users have adopted it, feel free to resubmit.

2023-03-02 17:50 UTC, closed without merging