rtmp-services: Add Joystick.TV
obsproject/obs-studio pull request #8414
Opened 2023-03-06 19:47 UTC by russ

### Description
[JoystickTV](https://joystick.tv/) (NSFW) is an adult live streaming service with a focus on gaming. This PR adds JoystickTV as an official service. The site has been live since January 2022.

### Motivation and Context
Currently our users are just streaming to our site using a custom RTMP setup. We often have to help support with the OBS setup to fine-tune their connection. This PR will allow new users that are less savvy in custom setups to start streaming right away.

### How Has This Been Tested?
These settings are what we have our users go by as a default recommendation. They have been using these settings successfully since we have been live.

### Types of changes
New feature (non-breaking change which adds functionality) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-03-06 21:53 UTC, derrod requested changes
Please ensure the commit title conforms to the contribution guidelines (in this case just make it the same as the PR title).

2023-03-06 22:15 UTC, russ commented
@derrod Commit title updated

2023-03-06 22:21 UTC, derrod approved these changes

2023-03-26 21:41 UTC, closed without merging

2023-03-26 21:41 UTC, jp9000 commented
Manually merged.