Use more actionable error messages for hardware encoders
obsproject/obs-studio pull request #8474
Opened 2023-03-15 20:22 UTC by notr1ch

### Description
Updates error messages when hardware encoders fail to be more actionable. Also some minor tone / grammar fixes.

### Motivation and Context
Telling a user to "Check your driver is up to date" is too open to interpretation, many users will use Windows Update or Device Manager to check for updates which doesn't help. Instead, let's explicitly tell them what is most likely to fix the problem.

### How Has This Been Tested?
Simulated an error and verified the links show as expected.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-03-18 22:25 UTC, WizardCM commented
We do expose NVENC on Linux these days, and so the driver link is irrelevant to them. This might require a separate translation key.

2023-03-19 18:13 UTC, notr1ch commented
Linux drivers are also available at that link.

2023-03-19 19:32 UTC, derrod commented
They are but Nvidia drivers on Linux are often handled by the distribution itself and using Nvidia's Linux installer can be a bit weird. So our Linux people suggested that it should not be shown for Linux users so they instead check their OS's respective repositories for updates.

2023-03-19 23:54 UTC, notr1ch commented
Do we have an appropriate page to send them to?

2023-03-21 06:38 UTC, norihiro commented
Would you please start the commit title from a verb?

2023-03-26 00:31 UTC, RytoEX requested changes
Wording nit, but otherwise I think this is fine.

2023-03-26 00:31 UTC, RytoEX commented on plugins/obs-ffmpeg/data/locale/en-US.ini
> +NVENC.UnsupportedDevice="NVENC Error: Unsupported device. Check your video card <a href=\"https://obsproject.com/go/nvenc-matrix\">supports NVENC</a> and try <a href=\"https://obsproject.com/go/nvidi
```suggestion
NVENC.UnsupportedDevice="NVENC Error: Unsupported device. Check that your video card <a href=\"https://obsproject.com/go/nvenc-matrix\">supports NVENC</a> and try <a href=\"https://obsproject.com/go/nvidia-drivers\">updating the driver</a>."
```

2023-03-26 02:30 UTC, RytoEX approved these changes
Force pushed changes. Looks good to me.

2023-03-26 02:48 UTC, merged