UI: Fix crash with custom service and empty server
obsproject/obs-studio pull request #8500
Opened 2023-03-20 15:39 UTC by tytan652

### Description

The else branch should not be taken in custom server scenarios.

### Motivation and Context

Fix a crash

### How Has This Been Tested?

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-03-20 15:46 UTC, notr1ch commented
I'm generally not a fan of branches that use the same variable in different conditions like this. Personally I think an early return in the first branch or letting it fall through would be better.

2023-03-21 17:46 UTC, notr1ch approved these changes

2023-03-21 17:52 UTC, RytoEX requested changes

2023-03-21 17:52 UTC, RytoEX commented on UI/window-basic-settings-stream.cpp
> +		if (ui->customServer->text().isEmpty())
Nit: remove the blank line here.

2023-03-21 18:16 UTC, tytan652 commented on UI/window-basic-settings-stream.cpp
> +		if (ui->customServer->text().isEmpty())
Done

2023-03-21 19:16 UTC, RytoEX approved these changes
Typically, no need to end list items with periods, but not going to block on this.

Looks good to me.

2023-03-21 19:17 UTC, merged