obs-outputs: Log encoder incompatibility with dbr
obsproject/obs-studio pull request #8741
Opened 2023-04-14 11:01 UTC by pkviet

### Description
This logs that dynamic bitrate is disabled when a codec which does not support bitrate reconfiguration is used, such as aom, svt-av1 ...

### Motivation and Context
User reported that dynamic bitrate did not work with aom + rtmp to YouTube.
See #8740 

### How Has This Been Tested?
Tested that it logs that dbr is disabled.

### Types of changes
 - Tweak (non-breaking change to improve existing functionality)
### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-04-14 21:19 UTC, RytoEX requested changes
Prefer spelling out "dynamic bitrate" when possible, such as the commit message:
```
obs-outputs: Log encoder incompatibility with dynamic bitrate
```

2023-04-14 21:19 UTC, RytoEX commented on plugins/obs-outputs/rtmp-stream.c
> +		info("Dynamic bitrate disabled.  The encoder does not support on the fly bitrate reconfiguration.");
```suggestion
		info("Dynamic bitrate disabled. The encoder does not support on-the-fly bitrate reconfiguration.");
```

2023-04-15 20:21 UTC, pkviet commented on plugins/obs-outputs/rtmp-stream.c
> +		info("Dynamic bitrate disabled.  The encoder does not support on the fly bitrate reconfiguration.");
done

2023-04-15 20:22 UTC, pkviet commented
> Prefer spelling out "dynamic bitrate" when possible, such as the commit message:
> 
> ```
> obs-outputs: Log encoder incompatibility with dynamic bitrate
> ```

fixed

2023-04-15 23:33 UTC, merged