libobs: Finalise source creation before firing signal
obsproject/obs-studio pull request #8769
Opened 2023-04-18 19:30 UTC by derrod

### Description

Fixes a possible crash when renaming a source during the source_create signal callback as it has not been added to the hash table yet.

### Motivation and Context

Fix crash reported on Discord.

### How Has This Been Tested?

Has not been tested.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-04-19 05:43 UTC, CodeYan01 commented
I have tested this both with my plugin and a minimal script, and it works, thank you!

If someone wants a minimal script to test this issue (just change extension to .py): 
[source_rename_test.txt](https://github.com/obsproject/obs-studio/files/11269061/source_rename_test.txt)

This script crashes OBS 29.1-beta4, but works properly on this build

2023-04-19 22:58 UTC, notr1ch approved these changes

2023-04-21 15:26 UTC, RytoEX requested changes
Nit:
* finalise -> finalize

2023-04-21 22:15 UTC, derrod commented
> * finalise -> finalize

Both are valid spellings.

2023-04-22 23:13 UTC, merged