UI: Disallow exiting settings with no audio tracks selected
obsproject/obs-studio pull request #8897
Opened 2023-05-12 16:34 UTC by gxalpha

### Description

Disallows the user from exiting the audio settings without having selected an audio track.

<img width="300" alt="image" src="https://github.com/obsproject/obs-studio/assets/59806498/b859d87d-f685-48bf-9118-45e145cb7ad7">

Split into two commits so that the first commit (for simple mode) can be cherry-picked to the 29.1 branch, while the second commit can wait until the next version.

### Motivation and Context

Fixes #8887

### How Has This Been Tested?

macOS 13.3.1
Unselected all audio tracks in both simple and advanced mode, and saw the popup appear, preventing me from exiting settings. Selected an audio track and exited successfully.
Selected FLV (and "Same as Stream" quality in simple mode) with none of the checkboxes checked beforehand and exited the settings successfully (since the checkboxes don't have an effect with FLV or with Same as stream quality in simple mode).

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-05-12 16:48 UTC, RytoEX requested changes

2023-05-12 16:48 UTC, RytoEX commented on UI/data/locale/en-US.ini
> +OutputWarnings.NoTracksSelected.Title="No audio track selected"
```suggestion
OutputWarnings.NoTracksSelected.Title="No Audio Track Selected"
```

2023-05-12 16:48 UTC, RytoEX commented on UI/window-basic-main-outputs.cpp
> +	 * just break them. */
How long has this been possible? Wondering if there's a way for us to force the user to select a track by preventing an output from starting in this configuration, as a future approach.

2023-05-12 17:02 UTC, gxalpha commented on UI/data/locale/en-US.ini
> +OutputWarnings.NoTracksSelected.Title="No audio track selected"
Fixed

2023-05-14 02:05 UTC, Warchamp7 commented
![image](https://github.com/obsproject/obs-studio/assets/1554753/e7e26032-3b3a-4394-a9cf-50ca0508badc)

Title -> `Output Settings Error`
Text -> `All outputs must have at least one audio track selected`

2023-05-14 12:30 UTC, gxalpha commented
Adjusted the wording per the above comment.
<img width="302" alt="image" src="https://github.com/obsproject/obs-studio/assets/59806498/7f3e7d05-8659-421e-8125-66f5212ca0e1">

2023-05-17 07:24 UTC, Warchamp7 approved these changes

2023-05-24 16:30 UTC, RytoEX approved these changes
After some off-thread discussion, this is better than the current situation. It might be ideal if the user selects zero audio tracks, that OBS outputs zero audio tracks if OBS can handle that, but for the interim, this is better than causing outputs to fail.

2023-05-24 16:30 UTC, merged

2023-08-19 01:37 UTC, jgusta commented
## Paradox 
In the event that you have all audio tracks unselected and all audio devices turned off, you enter a Catch-22 situation where you can't turn the audio device on because you can't hit 'Apply' without selecting audio tracks. You can't select audio tracks unless you have an audio device selected.

### Device disabled:
<img width="957" alt="CleanShot 2023-08-18 at 18 27 03@2x" src="https://github.com/obsproject/obs-studio/assets/2585228/1ee41aaf-a923-42ee-8052-f8de8782b8b8">

### Enabled, hitting apply:
<img width="755" alt="CleanShot 2023-08-18 at 18 27 16@2x"  src="https://github.com/obsproject/obs-studio/assets/2585228/27091f97-7a3b-4a12-aabb-78e814d17c2b">

### Can't select audio track
<img width="977" alt="CleanShot 2023-08-18 at 18 36 26@2x" src="https://github.com/obsproject/obs-studio/assets/2585228/0ff59e72-6782-418b-8dcd-b3d4c1eec9fa">

### Can't select audio track in recording settings
<img width="960" alt="CleanShot 2023-08-18 at 18 22 55@2x" src="https://github.com/obsproject/obs-studio/assets/2585228/b376bab7-d257-4dce-9c7a-7a875047709b">

### Can't select bitrate for audio tracks
<img width="955" alt="CleanShot 2023-08-18 at 18 24 06@2x" src="https://github.com/obsproject/obs-studio/assets/2585228/7d0907d2-5f96-437b-9c03-caf667385335">

2023-08-19 06:01 UTC, gxalpha commented
@jgusta on first glance it looks like the track selection is disabled because there’s an output running. Try stopping any recording/stream/virtualcam/NDI/etc, and then try to select a recording track. It should have nothing to do with whether there are any input devices selected.
If that doesn’t fix it, please file a new issue, reports under merged PRs can get lost easily. I’m currently on vacation but would assign it to me and look at it in detail once I’m back.

2023-08-23 10:05 UTC, jgusta commented
I've got it fixed. Apologies for posting on this PR. But to wrap up, it was a scene with the NDI plugin turned on that triggered the output error. Thank you.

2023-11-15 13:03 UTC, iG8R commented
Seams the issue still exists.
 - Microsoft Windows [Version 10.0.19045.2673] 64bit
 - OBS ver 30.0
 
![image](https://github.com/obsproject/obs-studio/assets/11407417/2e8043b6-9d2c-448b-bbc1-19e7d227468e)
![image](https://github.com/obsproject/obs-studio/assets/11407417/80bafd04-5ad4-4b42-9367-8a3e0c89f1b6)