build-aux: Update libdatachannel
obsproject/obs-studio pull request #9130
Opened 2023-06-22 19:59 UTC by pkviet

### Description
This updates libdatachannel to commit supporting simulcast.
This syncs the lib to obs-deps concurrent PR updating libdatachannel for windows & macOS [1].

[1] https://github.com/obsproject/obs-deps/pull/194/

### Motivation and Context
Keep libdatachannel updated on flatpak and synced with obs-deps.

### How Has This Been Tested?
Untested. I don't have any linux box except WSL.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-06-22 20:01 UTC, tytan652 commented
Please specify that it's for the Flatpak in the commit name.

2023-06-22 20:03 UTC, pkviet commented
> Please specify that it's for the Flatpak in the commit name.

yeah done

2023-06-22 21:09 UTC, pkviet commented
I'll update the PR when there's a tag for Sean simulcast commit, which should not take long.
I didn't know it was only possible to checkout tags for flatpak.
So it's on hold for now.

2023-06-23 04:32 UTC, tytan652 commented
Flatpak is with a `F` not a `f`.

> I didn't know it was only possible to checkout tags for flatpak.

If you want to checkout a specific commit you that have no tag, you have to remove the `tag` object.

2023-07-19 23:16 UTC, pkviet commented
**Update**
Added a commit to copy the new libdatachannel dll for old cmake.

2023-07-19 23:56 UTC, pkviet commented
I checked that the new dll is indeed copied with both old and new cmake.

2023-07-20 00:10 UTC, RytoEX requested changes
For the second commit, use this message:
```
cmake: Copy libdatachannel DLL

Copy libdatachannel DLL whether it's compiled on MSVC (and named
datachannel.dll) or cross-compiled on MinGW (and named
libdatachannel.dll).
```

The PR title probably needs simplified. Seems good otherwise.

2023-07-20 00:23 UTC, pkviet commented
> For the second commit, use this message:
> 
> ```
> cmake: Copy libdatachannel DLL
> 
> Copy libdatachannel DLL whether it's compiled on MSVC (and named
> datachannel.dll) or cross-compiled on MinGW (and named
> libdatachannel.dll).
> ```
> 
> The PR title probably needs simplified. Seems good otherwise.

done

2023-07-20 00:26 UTC, RytoEX commented
> > For the second commit, use this message:
> > ```
> > cmake: Copy libdatachannel DLL
> > 
> > Copy libdatachannel DLL whether it's compiled on MSVC (and named
> > datachannel.dll) or cross-compiled on MinGW (and named
> > libdatachannel.dll).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The PR title probably needs simplified. Seems good otherwise.
> 
> done

Nit: the second commit still uses two "sentences" instead of one.

2023-07-20 00:29 UTC, pkviet commented
> 
> Nit: the second commit still uses two "sentences" instead of one.

ha , should have copy-paste instead of fixing manually

2023-07-20 00:31 UTC, RytoEX approved these changes
Seems fine. Will wait for CI.

2023-07-20 14:28 UTC, merged