cmake: Add flags for reproducible builds on Windows
obsproject/obs-studio pull request #9177
Opened 2023-06-29 22:55 UTC by PatTheMav

### Description
Compiler and linker flags for reproducible builds on Windows were omitted from the recent CMake rework in error. This commit adds those flags back.

### Motivation and Context
Restores desired ability to create reproducible builds on Windows.

### How Has This Been Tested?
Will be tested by CI run on Windows.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-06-29 23:19 UTC, derrod requested changes
Reproducible build options work as expected and the files are identical between runs (build -> clean -> build), but the `PDBALTPATH` option does not seem to work, it still gets set to the absolute path.

Not sure to what extent we care about clang, but it supports `/Brepro` as well: https://clang.llvm.org/docs/UsersManual.html#id12

2023-06-29 23:23 UTC, PatTheMav commented
> Reproducible build options work as expected and the files are identical between runs (build -> clean -> build), but the `PDBALTPATH` option does not seem to work, it still gets set to the absolute path.
> 
> Not sure to what extent we care about clang, but it supports `/Brepro` as well: https://clang.llvm.org/docs/UsersManual.html#id12

Yeah my current experience is that as long as we use `clang-cl`, the same flags work.

2023-06-29 23:41 UTC, derrod approved these changes

2023-06-30 20:16 UTC, RytoEX approved these changes
Looks good to me.

2023-06-30 20:16 UTC, merged