Update services.json
obsproject/obs-studio pull request #9180
Opened 2023-06-30 10:45 UTC by mariocoellocastro

Wavezoo.com streaming server settings for DJ's

### Description
Adding 4 new types of server settings for with 10 servers each type

### Motivation and Context
Our DJ's need a simple way for configuring OBS properly

### How Has This Been Tested?
This was tested with the last release of OBS in a Linux environment (Ubuntu)

### Types of changes

New feature (non-breaking change which adds functionality): New Wavezoo specific stream settings and servers

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2023-06-30 10:48 UTC, derrod requested changes
Please read the [Service Submission Guidelines](https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines).

You're also adding the service multiple times which is not necessary. On top of that, you have marked the service as common and not provided any valid ingest servers and the website listed does not appear to be available.

2023-07-04 14:26 UTC, mariocoellocastro commented
You're right. I missed the guidelines.

I'll do the proper changes and try again when is ready.

Thanks and sorry for the inconvenience.

Mario

El vie, 30 jun 2023 a las 12:48, Rodney ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Please read the Service Submission Guidelines
> <https://github.com/obsproject/obs-studio/wiki/Service-Submission-Guidelines>
> .
>
> You're also adding the service multiple times which is not necessary. On
> top of that, you have marked the service as common and not provided any
> valid ingest servers and the website listed does not appear to be available.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/obsproject/obs-studio/pull/9180#pullrequestreview-1506970567>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4N45AOTIQL3GM36P2M6YRLXN2VHLANCNFSM6AAAAAAZZVYRZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-04 18:37 UTC, Fenrirthviti commented
You can update your branch and force push the changes, which is preferred rather than opening a new PR.

2023-07-08 12:15 UTC, norihiro commented on plugins/rtmp-services/data/services.json
> +                    "url": "rtmp://live-stream-server-01:1935/LiveApp"
Is this hostname (`live-stream-server-01`) correct? You might need to add your domain name, which is automatically added when you attempt to resolve the hostname.

2023-07-10 14:13 UTC, mariocoellocastro commented
No, I'm really ashamed for that. I did nothing well. The next commit will
be fine.

El sáb, 8 jul 2023 a las 14:15, Norihiro Kamae ***@***.***>)
escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In plugins/rtmp-services/data/services.json
> <https://github.com/obsproject/obs-studio/pull/9180#discussion_r1257251572>
> :
>
> > @@ -2846,6 +2846,262 @@
>              "supported video codecs": [
>                  "h264"
>              ]
> +        },
> +        {
> +            "name": "Wavezoo SD",
> +            "common": true,
> +            "stream_key_link": "https://wavezoo.com",
> +            "supported video codecs": [
> +                "h264"
> +            ],
> +            "supported audio codecs": [
> +                "aac"
> +            ],
> +            "servers": [
> +                {
> +                    "name": "Server #01 (RTMP)",
> +                    "url": "rtmp://live-stream-server-01:1935/LiveApp"
>
> Is this hostname (live-stream-server-01) correct? You might need to add
> your domain name, which is automatically added when you attempt to resolve
> the hostname.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/obsproject/obs-studio/pull/9180#pullrequestreview-1520698964>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4N45AJOGZAT54QWBUUNE2DXPFFNDANCNFSM6AAAAAAZZVYRZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-10 14:34 UTC, derrod requested changes

2023-07-10 14:34 UTC, derrod commented on plugins/rtmp-services/data/services.json
> +                "opus"
Unless your servers support [enhanced RTMP](https://github.com/veovera/enhanced-rtmp) do not specify "hevc" and "opus" here (or omit those properties entirely).

2023-07-10 14:34 UTC, derrod commented on plugins/rtmp-services/data/services.json
> +                "x264opts": "tune=zerolatency scenecut=0"
`tune=zerolatency` negatively impacts the quality more than it saves latency, especially if you're allowing b-frames you're better off not having it.

2023-07-10 14:34 UTC, derrod commented on plugins/rtmp-services/data/services.json
> +                    "url": "rtmps://live-stream-server-01.wavezoo.com:8443/LiveApp"
None of the RTMP URLs resolve.

2023-07-11 15:08 UTC, derrod commented
The RTMP URLs you specified still don't resolve to any IPs.

2023-07-11 15:13 UTC, mariocoellocastro commented
Sure. It’s a pool of server names, the server is created on demand for an
specific event. Right now, there’s no server instance behind the URLs.

El El mar, 11 jul 2023 a las 17:08, Rodney ***@***.***>
escribió:

> The RTMP URLs you specified still don't resolve to any IPs.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/obsproject/obs-studio/pull/9180#issuecomment-1631005508>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4N45AM6ZTSWQOR5OCU25P3XPVT57ANCNFSM6AAAAAAZZVYRZ4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-14 16:42 UTC, norihiro commented
If the server is not running, it's eligible to be removed like the PR 9387.

2023-08-17 13:42 UTC, mariocoellocastro commented
Hi Nirihiro,

   As I explained before, we run the servers on demand, but the URLs are
fixed. If you want to try wavezoo.com I can give you a demo. When an event
(a party in our case) is about to start, we assign a server of the pool to
the party, and the server (a big and expensive one) starts. Then, the
streamer (DJ) connects to the assigned server using the provided stream ID
in order to authenticate the user.

As you can see, we cannot have on line 20 big and expensive servers 24/7.

I appreciate your understanding.

Kind regards,

    Mario

2023-08-20 02:05 UTC, Fenrirthviti commented
After some discussion, I am making the call to decline this PR for now.

Wavezoo operates on a non-standard way and, frankly, is a bit of an anti-pattern to how every other streaming service operates with servers that are not expected to be available unless explicitly requested.

It conflicts with the user expectations, and would require custom handling to avoid our service validation checks from failing (as these servers would be offline more often than not). No other services in OBS really operate this way, so this is very much a non-standard way of operating and we'd be carving out a lot of exceptions I would rather not set a precedent for.

If there is an update towards a more standard service setup, we will happily re-review at that time. Thank you for your understanding.

2023-08-20 02:05 UTC, closed without merging