obs-webrtc: Add AV1 Support
obsproject/obs-studio pull request #9331
Opened 2023-07-28 19:02 UTC by Sean-Der

### Description
This adds AV1 support to obs-webrtc

### Motivation and Context
Users wish to use AV1

### How Has This Been Tested?
Tested against Broadcast Box

### Types of changes
 - New feature (non-breaking change which adds functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-07-28 19:03 UTC, Sean-Der commented
Adding AV1 is done in this commit https://github.com/obsproject/obs-studio/pull/9331/commits/d639dda1369c49983dcfff6acacbf616fca5890a

Migrating the libdatachannel usage to C -> C++ is done in this commit https://github.com/obsproject/obs-studio/pull/9331/commits/11a6348250c9d2e879c9d7db8000de57e5b17d17

Migration to C++ is a prerequisite for AV1 support.

2023-08-03 17:08 UTC, tytan652 requested changes
Those changes must be guarded behind #if version, some distro will not use an alpha version to build OBS Studio.

2023-08-03 18:01 UTC, Sean-Der commented
@tytan652 We use an alpha version of libdatachannel today. No stable release of libdatachannel exists that can be used with OBS.

I can ask for a stable release if packagers/distros want. Since libdatachannel isn't packaged anywhere I anticipate WebRTC will be disabled in most places :(

2023-08-03 20:54 UTC, tytan652 commented
> Since libdatachannel isn't packaged anywhere I anticipate WebRTC will be disabled in most places :(

So I am off-topic: It was already available on the AUR (ArchLinux User Repo) by the author of libdatachannel since a while. So people that build obs-studio-git have bad build of the webrtc plugin and my dev machine too.
A PR to make CMake fail if the version is too low will be needed as a fix.

2023-08-17 12:51 UTC, Conan-Kudo commented
> I can ask for a stable release if packagers/distros want. Since libdatachannel isn't packaged anywhere I anticipate WebRTC will be disabled in most places :(

Please get a released version in place for OBS (and packagers) to depend on.

2023-08-17 13:21 UTC, tytan652 commented
@Conan-Kudo, this is off-topic of the PR.
But maybe to try to discuss [libdatachannel](https://github.com/paullouisageneau/libdatachannel) maintainer directly about libdatachannel stabilization.

2023-08-17 13:35 UTC, Lain-B commented
I'll just throw in one very final thing on that off-topic discussion here: there's no need to rush things. I'd agree with @Conan-Kudo and @tytan652. I'd also like to say that there's no need to rush things, don't push public packages to release alpha as stable, make sure it's fully stabilized. Let's just all have patience. :slightly_smiling_face: 

(Also it would be nice if there were version macros)

Glad to see more AV1 PRs.

2023-11-01 20:03 UTC, Sean-Der commented
@Lain-B Good news! AV1 is now available in stable `v0.19.0`

Post v30.0 would it be ok to update the deps and enable AV1 for OBS?

2024-01-28 03:12 UTC, Sean-Der commented
AV1 is now available in the libdatachannel that OBS uses. This PR is ready for review/merge.

2024-01-28 08:11 UTC, Lain-B approved these changes

2024-01-28 08:11 UTC, merged

2024-03-11 07:05 UTC, kimilpyoung commented
Hi guys
When using the AV1 codec, frequent video freezing issues seem to occur due to keyframe problems.
After a keyframe arrives and the video playback resumes, the video plays normally for a while.
However, after a certain amount of time, the video stops and Browser can no longer receive keyframes from OBS.

When setting the keyframe interval to 1 second, the video experiences frequent interruptions. The testing environment is 1920x1080 at 60fps with a bitrate of 6000 Kbps.