obs-webrtc: Add AAC Support
obsproject/obs-studio pull request #9567
Opened 2023-09-06 08:37 UTC by troman123

### Description

### Motivation and Context

### How Has This Been Tested?

### Types of changes

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [ ] The code has been tested.
- [ ] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2023-09-06 08:50 UTC, pkviet commented
Thanks for your contribution. There are some formal issues.

- Please fill the template, especially motivation and tests.
- Also run clang-format on your code.
- your commit has no message. A description is mandatory.

In particular, tests with our various aac encoders would be useful:
- FFmpeg aac 
- coreaudio
- fdk-aac

You'll also have to fix the CI issues. Check the CI logs ; seems flatpak and macos do not build.

2023-09-06 08:56 UTC, pkviet commented
windows CI doesn't pass either:
`D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(142,17): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]
  D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(142,17): error C2220: the following warning is treated as an error [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]
  D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(264,4): error C2065: 'RTC_CODEC_AAC': undeclared identifier [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]
  D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(271,17): error C2078: too many initializers [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]
  D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(275,3): error C3861: 'rtcSetAACPacketizationHandler': identifier not found [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]`

2023-09-06 09:07 UTC, tytan652 commented
*Requires libdatachannel 0.19.0 stable release*

2023-09-06 09:25 UTC, pkviet commented
> **Requires libdatachannel 0.19.0 stable release**

ah, aac was added to libdatachannel on august 23 indeed by the same author.
@troman123 if you want to pass CI, you'll have to point build-spec.json to your fork of obs-deps which incorporate the update of libdatachannel to 0.19 stable release (in a separate commit which will be dropped upon eventual merge)
I'd suggest you also PR the libdatachannel update to obs-deps.
Also, for flatpak, you'll have to have a commit to point to 0.19 stable.

2023-09-06 09:44 UTC, troman123 commented
@pkviet ,  thanks for your suggestion, i will follow those steps to fix

2023-09-06 09:46 UTC, pkviet commented
> @pkviet , thanks for your suggestion, i will follow those steps to fix

Also fill the template and fix the commit message, as I pointed earlier.
It's not in mergeable state otherwise.

2023-09-06 13:21 UTC, troman123 commented
> Thanks for your contribution. There are some formal issues.
> 
> * Please fill the template, especially motivation and tests.
> * Also run clang-format on your code.
> * your commit has no message. A description is mandatory.
> 
> In particular, tests with our various aac encoders would be useful:
> 
> * FFmpeg aac
> * coreaudio
> * fdk-aac
> 
> You'll also have to fix the CI issues. Check the CI logs ; seems flatpak and macos do not build.

2023-09-06 13:22 UTC, troman123 commented
> windows CI doesn't pass either: `D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(142,17): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj] D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(142,17): error C2220: the following warning is treated as an error [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj] D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(264,4): error C2065: 'RTC_CODEC_AAC': undeclared identifier [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj] D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(271,17): error C2078: too many initializers [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj] D:\a\obs-studio\obs-studio\plugins\obs-webrtc\whip-output.cpp(275,3): error C3861: 'rtcSetAACPacketizationHandler': identifier not found [D:\a\obs-studio\obs-studio\build_x64\plugins\obs-webrtc\obs-webrtc.vcxproj]`

fixed

2023-09-07 02:42 UTC, troman123 commented
> Thanks for your contribution. There are some formal issues.
> 
> * Please fill the template, especially motivation and tests.
> * Also run clang-format on your code.
> * your commit has no message. A description is mandatory.
> 
> In particular, tests with our various aac encoders would be useful:
> 
> * FFmpeg aac
> * coreaudio
> * fdk-aac
> 
> You'll also have to fix the CI issues. Check the CI logs ; seems flatpak and macos do not build.

done

2024-01-29 20:57 UTC, Sean-Der commented
@troman123 Would you mind rebasing this PR? Master now has the obs-deps you need!

2024-05-07 11:04 UTC, troman123 commented
> @troman123 Would you mind rebasing this PR? Master now has the obs-deps you need!

Sorry, the pr conflict has been resolved now.

2024-05-07 11:07 UTC, troman123 commented
@Sean-Der  @RytoEX

2024-05-07 12:36 UTC, MarcoMayCry commented
Tested on MacOS and works. (FFmpeg AAC / CoreAudio AAC)
More, WHIP HEVC #10159  has been tested and works. (Apple VT HEVC Hardware Encoder)

<img width="995" alt="image" src="https://github.com/obsproject/obs-studio/assets/79976248/d6a41161-8472-4647-9d14-3ddb9209d4c0">

2024-05-24 02:59 UTC, troman123 commented
@Sean-Der @RytoEX I have rebased the master. can be ready for merging now. thank you.

2024-08-23 18:16 UTC, RytoEX requested changes
Quick scan. I might need someone else who understands WebRTC/WHIP to clarify and clean up the code comments.

2024-08-23 18:16 UTC, RytoEX commented on plugins/obs-webrtc/whip-output.cpp
> +
Why is this just adding a large comment block?

2024-08-23 18:16 UTC, RytoEX commented on plugins/obs-webrtc/whip-output.cpp
> -
Don't remove this line.

2024-08-23 18:16 UTC, RytoEX commented on plugins/obs-webrtc/whip-output.cpp
> +		if (object_type == 22 /*AOT_ER_BSAC*/)
I would rather see these `object_type` values as an enum.

2024-08-23 18:16 UTC, RytoEX commented on plugins/obs-webrtc/whip-output.cpp
> +	//no support AOT_ALS
```suggestion
	// no support AOT_ALS
```

2024-08-23 18:20 UTC, Sean-Der commented
Sorry I didn't look at this sooner!

Would it be possible to put non-OBS specific code upstream? Other projects could benefit from this, and want to keep the OBS+WebRTC code maintainable.

2026-09-09 17:11 UTC, Warchamp7 commented
This PR is being closed due to being stale with unresolved feedback or merge conflicts.

Please understand that as a project we have limited resources and we cannot always give submissions the attention they deserve in a timely fashion.

If you would still like to submit these changes, please open a new PR and include a mention of the original submission.

2026-09-09 17:11 UTC, closed without merging