obs-qsv11: Fix target usage migration string comparisons
obsproject/obs-studio pull request #9596
Opened 2023-09-14 22:10 UTC by gxalpha

### Description

Fixes problems with the astrcmpi logic, as well as a typo that said "vertfast" instead "veryfast".
Also makes the method a void because it always returns true and isn't checked anyways.

### Motivation and Context

Fixes https://github.com/obsproject/obs-studio/issues/9574.

### How Has This Been Tested?

Hasn't.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-09-14 23:12 UTC, RytoEX commented
Was looking into this myself. While these changes are fine, I think the core issue is that `update_targetusage` is only called via `update_settings`, which means that the target usage is not actually updated until that is invoked. If you start an encoder session, then `update_settings` is called, which calls `update_params`, which calls `update_targetusage` and internally sets the appropriate TU but doesn't change the UI. `update_latency`, `update_enhancements`, and `update_ratecontrol` are all called in `rate_control_modified` (those first two are also called in `update_params`). If we call `update_targetusage` from `rate_control_modified` like the others, it works fine in that the UI value is now updated.

2023-09-15 06:15 UTC, tytan652 commented on plugins/obs-qsv11/obs-qsv11.c
> +	    astrcmpi(target_usage, "quality") == 0)
```suggestion
	if ((astrcmpi(target_usage, "veryslow") == 0) ||
	    (astrcmpi(target_usage, "quality") == 0))
```

2023-09-15 06:16 UTC, tytan652 commented on plugins/obs-qsv11/obs-qsv11.c
> +		 astrcmpi(target_usage, "balanced") == 0)
```suggestion
	else if ((astrcmpi(target_usage, "medium") == 0) ||
		 (astrcmpi(target_usage, "balanced") == 0))
```

2023-09-15 06:16 UTC, tytan652 commented on plugins/obs-qsv11/obs-qsv11.c
> +		 astrcmpi(target_usage, "speed") == 0)
```suggestion
	else if ((astrcmpi(target_usage, "veryfast") == 0) ||
		 (astrcmpi(target_usage, "speed") == 0))
```

2023-09-15 06:19 UTC, tytan652 requested changes
`(astrcmpi || astrcmpi) == 0` is really bad because the returned 0 is casted as false but if one of the `astrcmpi` returns something different than 0 we get a cast to true and so even if one if them return 0/false the other returns true and so the `||` makes a true from both and is not equal to 0

2023-09-15 06:29 UTC, derrod commented
I'm not sure what you're saying, the code is doing `astrcmpi(...) == 0 || astrcmpi(...) == 0`, not `(astrcmpi || astrcmpi) == 0`.

2023-09-15 06:55 UTC, tytan652 commented
Priorities in this situation are messy, feel free to resolve them.

2023-09-15 11:55 UTC, gxalpha commented
@tytan652 For reference, C++ operator precedence can be checked here: https://en.cppreference.com/w/cpp/language/operator_precedence
Equality is group 10, logical OR is group 14, so equality will be evaluated first.

@RytoEX do you want me to add another call to `update_targetusage` to this PR or do you consider that to be standalone? I could unlink the open issue in the latter case.

2023-09-15 12:06 UTC, tytan652 approved these changes
The function looks good to me

2023-09-15 15:43 UTC, RytoEX commented
> @tytan652 For reference, C++ operator precedence can be checked here: https://en.cppreference.com/w/cpp/language/operator_precedence Equality is group 10, logical OR is group 14, so equality will be evaluated first.
> 
> @RytoEX do you want me to add another call to `update_targetusage` to this PR or do you consider that to be standalone? I could unlink the open issue in the latter case.

Let's keep the scope small and just fix the obvious errors here. We can handle adding `update_targetusage` to `rate_control_modified` in a separate PR.

2023-09-16 21:33 UTC, merged