linux-v4l2: add support for linear alpha blending
obsproject/obs-studio pull request #9620
Opened 2023-09-21 20:56 UTC by SludgePhD

### Description

This copies the linear alpha settings UI and translation strings from `image-source` and applies the setting to the V4L2 `obs_source_frame`.

### Motivation and Context

I am supplying non-premultiplied alpha to OBS, but OBS seems to be converting the frame to premulitplied alpha, and then render it as if it *wasn't* premulitplied, which gives a very wrong look. With this setting enabled, it looks correct.

I am not sure why this is called "linear" alpha in OBS - to my knowledge alpha is always *linear*.

### How Has This Been Tested?

By trying it with a v4l2loopback source, AR24 format, non-premultiplied alpha.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.
  - (could not find any)

2023-09-21 20:58 UTC, tytan652 commented
Remove all the translations except the en-US one, those are done through Crowdin.

2023-09-21 20:58 UTC, tytan652 requested changes
Remove all the translations except the en-US one, those are done through Crowdin.

2023-09-21 20:59 UTC, gxalpha requested changes
Please do not modify any ini files besides en-US. Any and all changes to them will get lost, translations are provided via our Crowdin.

2023-09-21 21:00 UTC, derrod commented
Also, don't modify libobs here.

2023-09-21 21:05 UTC, tytan652 commented
Also you are modifying the the source property UI, please provide screenshots like it was asked in PR template.

2023-09-21 21:19 UTC, GeorgesStavracas commented
Which devices provide images with an alpha channel?

2023-09-21 21:24 UTC, SludgePhD commented
> Which devices provide images with an alpha channel?

I don't know of any, I use this with v4l2loopback to transfer image data from another application.

2023-09-21 21:30 UTC, Warchamp7 commented
> > Which devices provide images with an alpha channel?
> 
> I don't know of any, I use this with v4l2loopback to transfer image data from another application.

This sounds like a particularly niche use case that is specific to your workflow. Is there any reason you don't simply make an alpha-supporting copy of the linux-v4l2 source for your own usage?

2023-09-21 21:37 UTC, SludgePhD commented
I am not sure why correct handling of the alpha channel is considered a "niche" use case – why does the V4L2 source support pixel formats with alpha channel at all, if the only way they can be displayed incorrectly handles the alpha channel?

2023-10-10 01:12 UTC, derrod commented
Instead of making this an option we should probably just always add the flag like we do in win-dshow[^1] because there probably is no situation where ingested alpha wouldn't require this. That'll turn it into a one line change.

[^1]: https://github.com/obsproject/obs-studio/blob/e85b257562f19e30fd89bcebf14dd37ccfdf69f3/plugins/win-dshow/win-dshow.cpp#L570

2023-10-14 23:10 UTC, Lain-B commented
I'd just say enable it all the time and remove the option. Would make the PR more simple and I don't see a case where we would want it otherwise to be perfectly honest.

2023-10-14 23:11 UTC, Lain-B requested changes
Requesting to be changed to just remove the option and make this always on with frame->flags.

2023-10-14 23:18 UTC, SludgePhD commented
Okay, I've updated the PR to make that change

2023-10-14 23:22 UTC, GeorgesStavracas approved these changes

2023-10-14 23:22 UTC, merged