mac-capture: Don't crash when migrating unknown display IDs
obsproject/obs-studio pull request #9631
Opened 2023-09-25 19:54 UTC by gxalpha

### Description

The current code assumes that a display UUID can be created with the stored ID, but that's not always the case, e.g. when the user doesn't have the display connected. As such, we need to null check this, and fall back to the invalid ID (0) when the ID cannot be migrated.

The current code also only migrates on source creation, which yields weird behaviour where if the user opens properties and then cancels it would still show the first display, but only for the session. This is why the code was factored out of the creation function and now is always used when an ID needs to be acquired from OBS Data settings, including when the source is updated.

The deprecated display capture still doesn't like when the display doesn't exist (it returns false/NULL on creation leading to the source basically being "dead" and the user not able to do anything with it but delete it), but this is the same on 29.1 and I'm not too worried about that source anyways.

### Motivation and Context

Got reports of crashes in mac-capture when the UUID gets created.
This can be reproduced easily by (first removing "display_uuid" if it exists and then) setting the "display" setting in the scene collection json to a number higher than the number of connected displays.

### How Has This Been Tested?

macOS 14
Tested that with a variety of different settings (existing "display", nonexistent "display", existing "display_uuid", nonexistent "display_uuid", and combinations of the keys) that previous behavior is restored, where when the display isn't found, nothing is shown but the properties let you select one of the available displays.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-09-25 20:09 UTC, PatTheMav commented
So the crash is not related to an invalid UUID, but an invalid C-string being passed into the CoreFoundation method generating a `CFUUIDRef`?

2023-09-25 20:36 UTC, gxalpha commented
With the crash that I can reproduces (and where the crash stack pretty much matches the one in the report I've seen) `CGDisplayCreateUUIDFromDisplayID` returns `NULL` (because the `display_id` refers to a display that the system doesn't know), which is then passed into `CFUUIDCreateString` which crashes.

I'm not sure what you mean exactly with "invalid UUID" - are you referring to a string that's not formatted as a UUID or to a UUID that the system doesn't know? Although neither of these cases appear to crash on master on my system.

2023-09-25 21:01 UTC, PatTheMav commented
Ok, so the crash is limited to cases of migrating from the old displayID-based setting to the UUID-based setting but with an invalid displayID, got it.

2023-09-25 21:01 UTC, PatTheMav approved these changes

2023-09-26 17:36 UTC, RytoEX commented
Does this fix #9606?

2023-09-26 17:46 UTC, gxalpha commented
Yes.

2023-09-26 17:51 UTC, RytoEX requested changes

2023-09-26 17:51 UTC, RytoEX commented on plugins/mac-capture/window-utils.h
> +/** Get the display ID of a display and simultaniously migrate pre-30.0 display IDs to 30.0 UUIDs.
```suggestion
/** Get the display ID of a display and simultaneously migrate pre-30.0 display IDs to 30.0 UUIDs.
```

2023-09-27 07:05 UTC, gxalpha commented on plugins/mac-capture/window-utils.h
> +/** Get the display ID of a display and simultaniously migrate pre-30.0 display IDs to 30.0 UUIDs.
Thanks.

2023-09-28 17:27 UTC, RytoEX approved these changes

2023-09-28 18:25 UTC, merged