libobs: Distinguish sceneitem hotkeys by id
obsproject/obs-studio pull request #9643
Opened 2023-09-28 20:30 UTC by derrod

### Description

Use the locally unique ID of a scene item for its hotkey(s) rather than the name, which will conflict when multiple sceneitems for the same source exist.

### Motivation and Context

Fixes #9639

### How Has This Been Tested?

Verified hotkeys are now saved and loaded correctly.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-09-28 20:45 UTC, tt2468 commented
Just going to note that this is likely to break some obs-websocket scripts out there, but I quite honestly don't care since there's significantly better options for controlling hotkeys than triggering hotkeys via obs-websocket requests.

2023-09-29 04:22 UTC, Penwy commented
Tested on Ubuntu 22.04.
Correctly fixes the intended issue.
No additional issues noticed.

2023-09-29 17:00 UTC, derrod commented
> Edit : I was hasty and mistaken. Reordering sceneitems messes with hotkey attribution.
> 
> Steps to reproduce :
> 
> * have a scene with two items (don't need to be the same source)
> * attribute different show/hide hotkeys to them
> * switch their order in the list
> * close, reopen
> * the hotkeys have been swapped around

This should now be fixed, alongisde another issue relating to hotkeys when moving things in/out of groups.

2023-10-02 22:35 UTC, RytoEX commented
@Penwy does the recent force-push fix the issues you noted?

2023-10-05 15:37 UTC, RytoEX requested changes
Commit message nit:
*  reodering -> reordering

2023-10-07 23:19 UTC, Lain-B approved these changes

2023-10-08 00:00 UTC, merged