win-wasapi: Use wasapi resampler when capturing processes & set hnsPeriodicity and hnsBufferDuration to 0.
obsproject/obs-studio pull request #9807
Opened 2023-11-05 10:26 UTC by pkviet

### Description
After a while, cracks and distortions are heard when trying to capture application audio.
See: https://github.com/obsproject/obs-studio/issues/8064
As a potentially mitigating factor, we let wasapi deal with resampling and channel mixing by enabling some AUDCLNT_STREAMFLAGS.
The sdk specifies also that: `For a shared-mode stream that uses event-driven buffering, the caller must set both hnsPeriodicity and hnsBufferDuration to 0.`
We set both to 0 as a result.

**Help needed**
This patch is in need of testers.
Test builds are available from CI.
If you're hit by the bug in #8064 , please test & report your results as a comment to this PR.

### Motivation and Context
Try to fix a bug.

### How Has This Been Tested?
A few people are reporting it seems to fix the issue for them.
But we need more testing; hence this PR to allow test builds to be more easily distributed.

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2023-11-05 20:22 UTC, SuslikV commented
Likely it does not - for me the behavior is the same, phase shifts, gaps etc, few leaks in the log (I usually, see them only from CI artifacts, for me it is strange, but anyway), VirtualBox environment.
Significance of this info is low and I don't want to spam the issue thread with additional posts, so I posted it here.

2023-11-07 17:46 UTC, RytoEX requested changes
Commit message nit:
* wasapi -> WASAPI (when written by itself)

The commit message subject is too long. You can use a more generic commit message subject and go into details in the commit message body, or else split the commit into two commits and have different commit messages.

The change to set hnsPeriodicity to 0 (hnsBufferDuration was already set to 0) matches the recommendation from the Microsoft Docs (as we discussed off-thread), so that _seems_ fine. Seeking other reviews concerning the other changes, or the PR in general.

2023-11-07 17:46 UTC, RytoEX commented on plugins/win-wasapi/win-wasapi.cpp
> +	res = client->Initialize(AUDCLNT_SHAREMODE_SHARED, flags, 0, 0, pFormat,
Nit: add a line break between the `if` contents and this statement.

2023-11-07 19:38 UTC, pkviet commented
So the PR doesn't seem to fix the bug  although there were some good initial reports.

2023-11-09 19:38 UTC, RytoEX requested changes
Commit message nits.

The first word after the prefix should be a present-tense verb.

distorsions -> distortions
wasapi -> WASAPI
sdk -> SDK

2023-11-10 10:04 UTC, pkviet commented
> Commit message nits.
> 
> The first word after the prefix should be a present-tense verb.
> 
> distorsions -> distortions wasapi -> WASAPI sdk -> SDK

Fixed

2024-03-24 12:31 UTC, ilsubyeega commented
I tested it for half a day and it didn't work though. The artifact from above was expired, so I built the patch against the latest commit.

2024-03-24 20:52 UTC, RytoEX commented
> I tested it for half a day and it didn't work though. The artifact from above was expired, so I built the patch against the latest commit.

This PR was simply an attempt at following the documentation to see if it would fix the issue. Per [pkviet's comment](https://github.com/obsproject/obs-studio/pull/9807#issuecomment-1799775505), it didn't:
> So the PR doesn't seem to fix the bug although there were some good initial reports.

2025-08-22 23:30 UTC, pkviet commented
Closing as the bug was found to be on MS side.

2025-08-22 23:30 UTC, closed without merging

2025-08-22 23:46 UTC, RytoEX commented
> AUDCLNT_STREAMFLAGS. The sdk specifies also that: `For a shared-mode stream that uses event-driven buffering, the caller must set both hnsPeriodicity and hnsBufferDuration to 0.` hnsBufferDuration was non-zero so we set it to 0.
> 
> **Sidenote:** Windows sdk sample is clearly wrong and doesn't follow its own SDK. 🙃 Firstly, it passes AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM as hnsPeriodicity; secondly, it sets a non-zero hnsBufferDuration although the code uses AUDCLNT_SHAREMODE_SHARED & AUDCLNT_STREAMFLAGS_EVENTCALLBACK (which imply event-driven buffering in shared mode).
> 
> [1] https://github.com/microsoft/Windows-classic-samples/blob/ac06e54a15e9a62443e400fffff190fb978ea586/Samples/ApplicationLoopback/cpp/LoopbackCapture.cpp#L105-L110

For posterity, my efforts to get the docs on this point corrected did not succeed. Perhaps someone else will have better luck.